### ISSUE TITLE
(Question) How to Save Flow Rate Settings

### ISSUE THREAD

**Issue by OwenD30** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#105]
Hello, 

I didn't know where I could ask questions so I'm just doing it this way. Is there a way to save flow rate settings so I don't have to do it manually every time before a print? I tried "Save to EPROM" but it didn't save after I switched the power off. If this isn't a feature, maybe you could add it in the future :-) 

Anyway, nice work and I love your firmware!

**Comment by knutwurst** [comment]
Hi @OwenD30 ,
thank you very much for your input :) 
I'll think about it :D Saving this value is not supported at the moment and has to be changed before every print.
