### ISSUE TITLE
MEGA_X JUNCTION_DEVIATION_MM is wrong

### ISSUE THREAD

**Issue by razor5k** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#112]
JUNCTION_DEVIATION_MM must be 0.016 instead of 0.16

Reason:

d = 0.4 * jerk^2/a_Printing
jerk = 4mm/s
a_Printing = 400mm/s^2
--> d = 0.4 * 16(mm/s)^2 / 400mm/s^2 = 0.016mm

Link how to calculate junction deviation:
http://blog.kyneticcnc.com/2018/10/computing-junction-deviation-for-marlin.html

**Comment by knutwurst** [comment]
Since Version 1.1.6, Junction Deviation is disabled and I switched back to classic jerk, because the slow 16Mhz CPU can not handle the JD calculations without issues.

But... I changed the Value so anyone who's interested in using JD can use it out of the box :)

Thanks!
