### ISSUE TITLE
Frage - M73 Support einschalten mit Original Anycubic i3 Mega Touch Display

### ISSUE THREAD

**Issue by ToTXR4Y** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#114]
Moin moin,

ich hab bei meinem Anycubic i3 Mega eigentlich "nur" eine Frage zum M73 Befehl. Ich benutze den SuperSlicer und generiere damit im Code die M73 Befehle. Im Standard sind diese ja in der Marlin deaktiviert, da das Display vom Any das sowieso nicht darstellen kann.

Ich nutze aber OctoPrint, der von den M73 Befehlen ja theoretisch profitieren könnte. Ich hab nun versucht über den LCD_SET Parameter das ganze in der Marlin "freizugeben". Dann meckert er aber beim erstellen der Firmware natürlich einiges was das Display betrifft an. Ich hatte die "configuration_adv.h" angepasst.

Gibt es da etwas was ich beachten muss um das ganze für OctoPrint zu realisieren? Am Touch ist es mir eigentlich egal, aber ich würde es gerne im OP sehen ;-) Das Touch wird vermutlich bald eh gegen ein 12864 Display ausgetauscht, da muss ich dann in der Firmware eh mal gucken wie ich das vernünftig eingebunden bekomme.

**Comment by knutwurst** [comment]
Moin :)
Leider ist das nicht möglich, da hier die Restzeit in Marlin gesetzt werden würde. Klingt alles cool und wäre auch kein Problem, gäbe es da nicht den Anycubic Touchscreen :/ 

Der Grund steht hier (ganz unten): https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/wiki/FAQ-(deutsch)

Ich kann schauen, ob man das umgehen kann, aber ich fürchte, dass das nichts wird.
