### ISSUE TITLE
[BUG] MEGA_S_DGUS  does not display the temperature change after removing the filament

### ISSUE THREAD

**Issue by availov** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#118]
Printer: Anycubic-i3-MEGA-S
Release: 1.1.9

### Bug Description

After removing the filament, no change in nozzle temperature is displayed (E0 Temp). Restarting the printer corrects the problem. 

### My Configurations

default

### Steps to Reproduce

1. [Tools->Filament>Filament remove]
2. [Press stop button]
3. [The nozzle temperature sensor freezes, in fact the nozzle cools down.]
4. [The printer cannot read the memory card]

**Comment by knutwurst** [comment]
This is a known Bug with the genuine Mega X DGUS II TFT (not the new clone). After waiting too long, the display itself hangs/crashes. You could Update your TFT Firmware: https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/wiki/Types-of-Anycubic-Touchscreens
