### ISSUE TITLE
Fystec Mini 12864 LCD Panel

### ISSUE THREAD

**Issue by WeltenbummlerKA** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#121]
Integration Fysetc 12864 LCD Displays

### Description

Hello Knutwurst,
may it is possible that you integrate the Fyetc V1.2 16864 LCD Panel together with TMC2208 steppers in your firmware? I had broken my original Anycubic LCD. The Fysetc is much cheaper and shown all information given by the marlin firmware.
My skills in programming aren't so good and I have the fear to broken something.

Best regards Michael

**Comment by knutwurst** [comment]
Nope. I'm sorry. The whole point of this firmware is the support of the Anycubic Touchscreens. If you need to use your 16864 Display with rotary encoder, you should go for the official marlin firmware.
