### ISSUE TITLE
MEGA S TMC BLTOUCH DOESN'T WORK

### ISSUE THREAD

**Issue by wuyonghuahk** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#127]
When the bltouch needle touchs the bed, Z axis don't stop at all. It can work well by 1.1.9 firmware.I test serival times,but it steel dosn't work.

**Comment by knutwurst** [comment]
Which firmware version do you use? Which one works, which doesn't?

**Comment by wuyonghuahk** [comment]
Now,I use 1.1.9.&nbsp;&nbsp;&nbsp;&nbsp; 2.0 doesn't work.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月21日(星期三) 下午4:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S] MEGA S TMC BLTOUCH DOESN'T WORK (#127)





 
Which firmware version do you use? Which one works, which doesn't?

**Comment by knutwurst** [comment]
1.2.0 Alpha or beta?

Thank you for your input! I'll take a look into that.

**Comment by wuyonghuahk** [comment]
1.2.0 Alpha




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Oliver ***@***.***&gt;; 
发送时间: 2021年4月21日(星期三) 下午4:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S] MEGA S TMC BLTOUCH DOESN&#39;T WORK (#127)





 
1.2.0 Alpha or beta?
 
Thank you for your input! I'll take a look into that.

**Comment by knutwurst** [comment]
Does the problem sill persist in 1.2.0-beta.1?

**Comment by wuyonghuahk** [comment]
yes, bltouch doesn't work.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Oliver ***@***.***&gt;; 
发送时间: 2021年4月21日(星期三) 下午4:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S] MEGA S TMC BLTOUCH DOESN&#39;T WORK (#127)





 
Does the problem sill persist in 1.2.0-beta.1?

**Comment by knutwurst** [comment]
Ok, thank you very much! I'll look into that!

**Comment by wuyonghuahk** [comment]
Not at all. I hope you can fix the issue.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Oliver ***@***.***&gt;; 
发送时间: 2021年4月21日(星期三) 下午4:47
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S] MEGA S TMC BLTOUCH DOESN&#39;T WORK (#127)





 
Ok, thank you very much! I'll look into that!

**Comment by knutwurst** [comment]
Can you tell me which version you used exactly? The complete filename helps a lot.

**Comment by wuyonghuahk** [comment]
I had used the two versions. 




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Oliver ***@***.***&gt;; 
发送时间: 2021年4月21日(星期三) 下午5:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S] MEGA S TMC BLTOUCH DOESN&#39;T WORK (#127)





 
Can you tell me which version you used exactly? The complete filename helps a lot.

**Comment by wuyonghuahk** [comment]
I use TMC2209.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Oliver ***@***.***&gt;; 
发送时间: 2021年4月21日(星期三) 下午5:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S] MEGA S TMC BLTOUCH DOESN&#39;T WORK (#127)





 
Can you tell me which version you used exactly? The complete filename helps a lot.

**Comment by knutwurst** [comment]
@wuyonghuahk can you please tell me the filename of the firmware you used?

**Comment by wuyonghuahk** [comment]
MEGA_S_TMC_BLT_10_v1.2.0-Alpha.3 and MEGA_S_TMC_BLT_10_v1.2.0-beta.1




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Oliver ***@***.***&gt;; 
发送时间: 2021年4月21日(星期三) 下午5:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S] MEGA S TMC BLTOUCH DOESN&#39;T WORK (#127)





 
@wuyonghuahk can you please tell me the filename of the firmware you used?

**Comment by knutwurst** [comment]
Please try the attached hotfix firmware it this solves your issue :) 
[MEGA_S_TMC_BLT_10_v1.2.0-b1hotfix1.hex.zip](https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/files/6349835/MEGA_S_TMC_BLT_10_v1.2.0-b1hotfix1.hex.zip)

**Comment by wuyonghuahk** [comment]
ok, I'll try.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Oliver ***@***.***&gt;; 
发送时间: 2021年4月21日(星期三) 下午5:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S] MEGA S TMC BLTOUCH DOESN&#39;T WORK (#127)





 
Please try the attached hotfix firmware it this solves your issue :)
 MEGA_S_TMC_BLT_10_v1.2.0-b1hotfix1.hex.zip

**Comment by wuyonghuahk** [comment]
BLTOUCH doesn‘t work.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Oliver ***@***.***&gt;; 
发送时间: 2021年4月21日(星期三) 下午5:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S] MEGA S TMC BLTOUCH DOESN&#39;T WORK (#127)





 
Please try the attached hotfix firmware it this solves your issue :)
 MEGA_S_TMC_BLT_10_v1.2.0-b1hotfix1.hex.zip

**Comment by wuyonghuahk** [comment]
I made a video, but I couldn't send it by email.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Oliver ***@***.***&gt;; 
发送时间: 2021年4月21日(星期三) 下午5:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S] MEGA S TMC BLTOUCH DOESN&#39;T WORK (#127)





 
Please try the attached hotfix firmware it this solves your issue :)
 MEGA_S_TMC_BLT_10_v1.2.0-b1hotfix1.hex.zip

**Comment by knutwurst** [comment]
That's because we are not communicating via email. It's the github Issue here: https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/issues/127

You can upload zip files if you want, but I thing I don't need a video.

Here is a new possible fix. Please try it out: 
[MEGA_S_TMC_BLT_10_v1.2.0-b1hotfix2.hex.zip](https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/files/6350155/MEGA_S_TMC_BLT_10_v1.2.0-b1hotfix2.hex.zip)

**Comment by wuyonghuahk** [comment]
It works,thank you very much!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Oliver ***@***.***&gt;; 
发送时间: 2021年4月21日(星期三) 晚上6:36
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S] MEGA S TMC BLTOUCH DOESN&#39;T WORK (#127)





 
That's because we are not communicating via email. It's the github Issue here: #127
 
You can upload zip files if you want, but I thing I don't need a video.
 
Here is a new possible fix. Please try it out:
 MEGA_S_TMC_BLT_10_v1.2.0-b1hotfix2.hex.zip

**Comment by wuyonghuahk** [comment]
what's the problem？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Oliver ***@***.***&gt;; 
发送时间: 2021年4月21日(星期三) 晚上6:36
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S] MEGA S TMC BLTOUCH DOESN&#39;T WORK (#127)





 
That's because we are not communicating via email. It's the github Issue here: #127
 
You can upload zip files if you want, but I thing I don't need a video.
 
Here is a new possible fix. Please try it out:
 MEGA_S_TMC_BLT_10_v1.2.0-b1hotfix2.hex.zip

**Comment by knutwurst** [comment]
It seems like the the software-mode for the Sensor does not work on all (older) models. Original BLTouch 3.1 works fine, but there are some issues when it comes to pulse lengths on other BLTouch models or clones.

I'll merge the fix into the official sources now and build a 1.2.0-beta.2.

Thank you very much for your help and the fast replies! 

Have an nice day <3

**Comment by wuyonghuahk** [comment]
I use the 3D touch. Bltouch is expensive.&nbsp;



---Original---
From: "Oliver ***@***.***&gt;
Date: Wed, Apr 21, 2021 18:50 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S] MEGA S TMC BLTOUCH DOESN'T WORK (#127)




 
It seems like the the software-mode for the Sensor does not work on all (older) models. Original BLTouch 3.1 works fine, but there are some issues when it comes to pulse lengths on other BLTouch models or clones.
 
I'll merge the fix into the official sources now and build a 1.2.0-beta.2.
 
Thank you very much for your help and the fast replies!
 
Have an nice day <3

**Comment by knutwurst** [comment]
Yes, that was my thought :) 
The first beta only works with original BLTouch v3.

**Comment by wuyonghuahk** [comment]
got it.&nbsp;



---Original---
From: "Oliver ***@***.***&gt;
Date: Wed, Apr 21, 2021 18:55 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S] MEGA S TMC BLTOUCH DOESN'T WORK (#127)




 
Yes, that was my thought :)
 The first beta only works with original BLTouch v3.
