### ISSUE TITLE
BL-Touch Problem

### ISSUE THREAD

**Issue by ar84** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#131]
Hallo 

Ich habe das Problem das beim Auto-Bed-Leveling, egal ob über Display am Drucker oder per Repetier, der Sensor an die erste Position fährt 2x ein aus fährt und dann stehen bleibt.

Was kann ich tun?

Recv:19:53:03.275: 0: <Special Menu>
Recv:19:53:11.984: Special Menu: BLTouch Leveling
Recv:19:53:23.742: X:0.00 Y:0.00 Z:0.00 E:0.00 Count X:0 Y:0 Z:0
Recv:19:53:31.841: Error:!! STOP called because of BLTouch error - restart with M999
Recv:19:53:31.841: Error:Probing Failed
Recv:19:53:31.841: X:0.00 Y:25.00 Z:12.10 E:0.00 Count X:0 Y:2000 Z:4840
Recv:19:53:31.877: echo:Settings Stored (712 bytes; crc 13489)

**Comment by knutwurst** [comment]
Hallo,

so gern ich helfe und so leid es mir tut, aber dies ist ein Firmware-Bugtracker für Fehler in der Firmware. Das von dir geschilderte Problem ist zu 99% hausgemacht durch einen nicht korrekt eingestellten Z-Offset oder einem defekten Sensor. 

Diese Frage wurde aber schon mehrfach sowohl in der BLTouch Anleitung als auch in den FAQ behandelt. https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/wiki

**Comment by ar84** [comment]
Hallo.
Sorry hatte vergessen den Post zu schließen. Fehler gefunden.
Gruss
