### ISSUE TITLE
extruder not working 

### ISSUE THREAD

**Issue by joloman2** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#132]
hey

i have a problem my extrudere does not turn wen i tell it to i have checked the wires with a multiemeter. but if i use the menu and try loading the filament it does not turn for some reason firmware MEGA_X_DGUS_BLT_10_v1.2.0-b1hotfix2.hex

regards 

joloman2

**Comment by knutwurst** [comment]
Please use the 1.1.9 release version. The Beta Versions are not suitable for daily use.
