### ISSUE TITLE
[BUG] After FW Update CHIRON_v1.2.0-beta.2.hex --> ERROR: "Lack of Filament"

### ISSUE THREAD

**Issue by ThomasNeefe** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#138]
Hello Oliver,

i have ugraded my chiron with your FW CHIRON_v1.2.0-beta.2.hex. 
After the firware update i got this error in the display "lack of filament". 
Ich checked also CHIRON_v1.2.0-**beta.1**.hex --> the same problem. 
When i go back to customer firmware (V1.3.0), the issue disappears.

Do you havea solution?
Regards,
Thomas

**Comment by SteFiD93** [comment]
i have the exact same problem .. but it does .. from the first versions for the chiron (it was not officially supported by this firmware yet)

the only way is to go to the special menu in sdcard and select the item to disable the sensor

**Comment by pevorchiron** [comment]
Hello Oliver,

I updated my Chiron to version 1.2.0 beta4 - still the same issue with filament sensor is present. With stock firmware the filament sensor works fine. Hope there will be a fix soon be available.

**Comment by knutwurst** [comment]
Fixed in 1.2.0 Beta 5
