### ISSUE TITLE
[FR] (Please update part links on BL touch installation page)

### ISSUE THREAD

**Issue by bassamanator** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#139]
I have all the parts except for the servo cable extensions.

Is this what I'm looking for: [aliexpress link](https://www.aliexpress.com/item/4000864020412.html), ~~[aliexpress link](https://www.aliexpress.com/item/4000242973966.html), [link2](https://www.aliexpress.com/item/4000860773329.html), [link3](https://www.aliexpress.com/item/33056360513.html)~~.

Also, will 2 x 100 cm extensions be ok?

Thanks!

**Comment by knutwurst** [comment]
Hi @bassamanator ,
since I got mostly negative feedback on affiliate links, I removed them completely ... I just forgot to do so on the english translated page. Sorry.

Yes, the Link you provided ist totally fine. Everything should work as expected. :)

**Comment by bassamanator** [comment]
I'd like to integrate you into my aliexpress and forget about it. How do I do that?

**Comment by bassamanator** [comment]
Bump.
