### ISSUE TITLE
[BUG] does not probing Chiron beta3

### ISSUE THREAD

**Issue by SteFiD93** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#147]
when you go to the menu to auto-level he comes home .. but he stops there .. and the display shows "probing ..."
obviously I mean in the chiron menu of the prin not in the special menu (sdcard menu)

**Comment by knutwurst** [comment]
Yes, this is a known issue and I'm trying my best to fix it. In the meantime, please use Beta 2 with manual mesh bed leveling (via special menu).
