### ISSUE TITLE
[BUG] Unknown board - no info on wiki

### ISSUE THREAD

**Issue by JernejL** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#149]
### Bug Description

Trouble finding wiki info - bltouch wiki page says i have to use correct version ( 10, 11 ) but there is no info on how you actually find out the version on the wiki, i have a i3 mega X bought in january this year. 

### Steps to Reproduce

1. https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/wiki/BLTouch-Installation-(english)
2. There is a chapter about "It is important to note which board you have (TRIGORILLA_14 v1.0 or v1.1), since the pin assignment has changed here."
3. There is no info on how to find out which board you have. 

**Expected behavior:** Page with pictures or some kind of instructions

**Actual behavior:** No info :( 

#### Additional Information

* See https://i.imgur.com/3ZXK70O.png - the only marking about version i could find is this, it says "trigorilla board v 0.0.2" so it seems not to match anything you have on wiki.

**Comment by Jack77777777** [comment]
You can find it out if you follow this:
https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/wiki/BLTouch-Installation-(english)#install-the-firmware

**Comment by JernejL** [comment]
This is bizzare, can i find out version in another way? using picture comparison or gcode command?

**Comment by knutwurst** [comment]
Unfortunately, there is no official way to find out which motherboard it really is, as Anycubic has not documented this. Sometimes the label says 1.0 or 0.0.1 or 0.0.2. Unfortunately, this does not provide any information about the pin assignment of the servo port.

The easiest way for me (as also described in the instructions) to try it out. First with the _10 and then with the _11.

**Comment by Datafreak** [comment]
I had the same issue with sa simmilar 0.0.2 board.
The FIrmware with "_10" was correct for mine.

**Comment by JernejL** [comment]
Main issue i have is that instructions say that that pin assignment has changed between those trigorilla board versions, so if i can't find out which board i have it will fry bl-touch if not connected properly? there is no clear picture in tutorial on how the servo port looks like on the board and how wires get connected to it. 
 
Should i just orient cabling based on markings on board (if i find any) and then try one or the other firmware versions?

**Comment by knutwurst** [comment]
No, nothing happens. The assignment for the servo pin that has already been soldered has only changed. In the worst case, the BLTouch just won't work. So when you do test 2, the tip has to be extended. If that doesn't happen, just take the other firmware.

**Comment by JernejL** [comment]
I've started actual installation now and will follow most of the manual. 
 
The STL to mount bltouch linked to on thingiverse printed well, however when i mounted the bltouch to it the probe point did not protrude further than the nozzle, is this maybe some new issue? 
 
Bltouch is not original but clone. i've added M3 nuts to get it to protrude further, do i need to adjust some configuration for this?

**Comment by Datafreak** [comment]
The linked [Mount](https://www.thingiverse.com/thing:2824005) for the STL is for older BL-Touch Sensors.

You could try: [Anycubic I3 Mega BLTouch V3 Mount](https://www.thingiverse.com/thing:3660135) for newer BL-Touch Sensors like v3.1
Or one of the other Remixes wich are linked on Thingiverse.

**Comment by JernejL** [comment]
Is there anything to adjust if i just put in 2 washers? seems like tutorial will need update too :)

**Comment by JernejL** [comment]
Thanks @Datafreak , I've printed the other mount that you suggested and that worked perfectly. 
 
In the end i used _10 firmware and also had to use DGUS version that is not in stable release, so i'm now running MEGA_X_DGUS_BLT_10_v1.2.0-beta.4 and this worked well with my version. 
 
Here is my wiring, i hope this is clear as you can follow wire colors from bltouch to the head and also to the board itself. 
 
![photo_2021-06-14_07-20-27](https://user-images.githubusercontent.com/1741375/121842639-05af1400-cce1-11eb-8aaa-0a0f0b5fdfc7.jpg)
![photo_2021-06-14_07-20-26](https://user-images.githubusercontent.com/1741375/121842640-0647aa80-cce1-11eb-9d27-c476543bf9c0.jpg)
![photo_2021-06-14_07-20-24](https://user-images.githubusercontent.com/1741375/121842641-06e04100-cce1-11eb-989a-9040f16ca595.jpg)
![photo_2021-06-14_07-22-44](https://user-images.githubusercontent.com/1741375/121842799-56267180-cce1-11eb-8880-edd599af6897.jpg)
