### ISSUE TITLE
v 1.1.4 special menu keeps prompting no SD card when you navigate (without the SD card).

### ISSUE THREAD

**Issue by brunoosti** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#15]
v 1.1.4 special menu keeps prompting no SD card when you navigate (without the SD card).

**Comment by knutwurst** [comment]
I know. In the 1.1.4 it only works with the "new" TFT, not the old one or the Mega X. The issue is already fixed and will be released with the 1.1.5 Version.
