### ISSUE TITLE
BLTouch (CN clone 3Dtouch)  an Anycubic I3 Mega Pro/Tastpin fährt nicht aus

### ISSUE THREAD

**Issue by faitesvosjeux** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#153]
Anycubic I3 Mega Pro, Mainboard Trigorilla V0.0.2, KW MEGA_P BLT 1.2 beta 3/MEGA BLT 11 1.2 Beta 3

3DTouch nach Anweisung mit Halter aus Thingiverse verbaut, Verkabelung zu D11 (auf Mainboard "S1 " beschriftet) gelegt, auf Polarität geachtet und 5V/GND entsprechend vertauscht. 3DTouch fährt nach Einschalten Pin 4x ein & aus, Leuchtdioden rot & blau an. Bei Ansteuerung über das Spezial-Menu wird erst die Home-Position angefahren, kurze Zeit später die erste Position zum Leveln. Hotend bleibt dann stehen, drei aufsteigende Pieptöne in Reihenfolge. Tastpin fährt nicht aus. Auch Befehle M280 P0 S10 oder M280 P0 S90 über Pronterface bringen den Pin nicht zum Ausfahren. Any ideas?

**Comment by Datafreak** [comment]
HI @faitesvosjeux,

du nutzt die Firmware mit "11". Funktioniert bei dir der BLTouch bei der Firmware mit "10"?

Gruß,
Datafreak

**Comment by faitesvosjeux** [comment]
Hallo Datafreak,

Vers. "10" auch ausprobiert, damit wird die Nozzle gnadenlos ins Druckbett gedrückt...

**Comment by Datafreak** [comment]
Also fährt bei Version "10" der PIN vom BLTouch nicht aus.
Bei Version "11" bekommst du den Fehler.

Zeit dir Pronterface bzw. das Terminal in Octoprint einen Fehler an, wenn die Pieptöne kommen?

**Comment by faitesvosjeux** [comment]
Bei Version "10" fährt der Pin auch nicht aus, aber die Nozzle ins Druckbett. Nein, keine Fehler im Pronterface, auch kein Echo, wenn der Befehl zum Absenken manuell abgesetzt wird.

**Comment by MaGe-1** [comment]
Hast du den Signalpin vom BLTouch nach Anleitung angeschlossen oder direkt auf das Board geführt`?

**Comment by faitesvosjeux** [comment]
Ja, da die Platine meines Hotends etwas unterschieldich ist, entsprechend zwei zusätzliche Pins aufgelötet, die zu D11 (auf Mainborad "S1 beschriftet") führen.

**Comment by knutwurst** [comment]
> Ja, da die Platine meines Hotends etwas unterschieldich ist, entsprechend zwei zusätzliche Pins aufgelötet, die zu D11 (auf Mainborad "S1 beschriftet") führen.

Dann liegt da der Fehler. Der pin fährt über den Servo-Port aus. Wenn das Signal oben nicht ankommt, macht der BLTouch nichts. Bei der gemeinsamen Masse ist vermutlich der Spannungsabfall zu groß.

**Comment by faitesvosjeux** [comment]
Und wie kann man das dann ggf. heilen?

**Comment by knutwurst** [comment]
Indem man wie in der Anleitung ein Kabel legt?

**Comment by faitesvosjeux** [comment]
Die Pins sind über ein eigenes Kabel auf das Mainboard an D11 (Meinboard "S1") geführt.

**Comment by MaGe-1** [comment]
Ansonsten mal die beta 2 probieren... Fehler ist bei mir ähnlich.

**Comment by faitesvosjeux** [comment]
Ich habe beta 1 & Beta 2 probiert, keine Änderung.

**Comment by knutwurst** [comment]
Ist das Problem mittlerweile gelöst? In dem [Beginner's Guide](https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/wiki/Beginner's-Guide-(Deutsch)) habe ich auch noch mal alle Mainboards aufgelistet zur Identifikation.
