### ISSUE TITLE
[FR] Any plans to update to later versions of Mariln - like current 2.0.8.x?

### ISSUE THREAD

**Issue by MrBill1234** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#156]
Is there any plan to merge your code with newer versions of Marlin?

**Comment by knutwurst** [comment]
No.. not really. In the past I took some newer features from never Marlin versions and ported them to my custom firmware, but I changed so much in regards to the Anycubic Touchscreens, that a simple "update" won't work. It would take me days or weeks to implement everything and I would still not know, if everything works the same way without any issues.

If you want, you can do it yourself. I'd really appreciate that! But for me, as a single developer with only some hours free time...
