### ISSUE TITLE
Default values from original firmware - Mega X

### ISSUE THREAD

**Issue by Sydney1101** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#16]
> echo:V1.2.6
 1.1.0-RC8
echo: Last Updated: 2016-12-06 12:00 | Author: (Jolly, xxxxxxxx.CO.)
Compiled: Nov  5 2019
echo: Free Memory: 3123  PlannerBufferBytes: 1168
echo:V29 stored settings retrieved (398 bytes)
echo:Steps per unit:
echo:  M92 X80.00 Y80.00 Z800.00 E400.00
echo:Maximum feedrates (mm/s):
echo:  M203 X120.00 Y120.00 Z20.00 E80.00
echo:Maximum Acceleration (mm/s2):
echo:  M201 X400 Y400 Z60 E10000
echo:Accelerations: P=printing, R=retract and T=travel
echo:  M204 P400.00 R3000.00 T400.00
echo:Advanced variables: S=Min feedrate (mm/s), T=Min travel feedrate (mm/s), B=minimum segment time (ms), X=maximum XY jerk (mm/s),  Z=maximum Z jerk (mm/s),  E=maximum E jerk (mm/s)
echo:  M205 S0.00 T0.00 B20000 X4.00 Y4.00 Z0.10 E8.00
echo:Home offset (mm)
echo:  M206 X0.00 Y0.00 Z0.00
echo:Z2 Endstop adjustment (mm):
echo:  M666 Z0.00
echo:Material heatup parameters:
echo:  M145 S0 H180 B70 F0
  M145 S1 H240 B110 F0
echo:PID settings:
echo:  M301 P20.00 I0.30 D150.00
echo:  M304 P60.00 I0.30 D30.00
echo:Filament settings: Disabled
echo:  M200 D1.75
echo:  M200 D0

**Comment by knutwurst** [comment]
Thank you!
