### ISSUE TITLE
[FR] (feature request title)

### ISSUE THREAD

**Issue by phyex0** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#161]
Hey, I'm sorry I actually want to mail you but I didn't see it. However, I'd like to ask you about Anycubic Vyper.  Are you going to develop any software for it? Or current software is suitable for it?

**Comment by knutwurst** [comment]
Nope. The Viper uses a custom board with a 72Mhz STM32 CPU. That's not possible.
