### ISSUE TITLE
[FR] Version for Mega S with BMG extruder

### ISSUE THREAD

**Issue by condor125** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#162]
### Description

I have the Mega S with BMG extruder, could you please make the firmware available for this combo? Thanks!

**Comment by knutwurst** [comment]
The Feature is already in there. You only need to compile it by yourself with PlatformIO and set the environment variable **-DKNUTWURST_BMG**

**Comment by Jack77777777** [comment]
I have a BMG Clone from Trianglelab and just changed the E-Steps through terminal. Should i change anything in the firmware and compile ?

**Comment by knutwurst** [comment]
@Jack77777777 if your Extruder runs in the correct direction, then no... you don't need to. But with the Flag, everything is done for you... correct direction for your printer, speed, gear reduction etc.

Just add it to your printer config and compile.
![Bildschirmfoto 2021-06-18 um 08 30 54](https://user-images.githubusercontent.com/36196269/122516992-c26de180-d00f-11eb-90d4-759fb699b482.jpg)

**Comment by Jack77777777** [comment]
I swapped the pins to correct the direction. Would you recommend to swap back and let the firmware do it ?

**Comment by knutwurst** [comment]
@Jack77777777 you can do whatever you like :) I doesn't make any difference at all. :)
