### ISSUE TITLE
QUESTION: Automatic Z Offset Save/Restore

### ISSUE THREAD

**Issue by Jack77777777** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#167]
Can someone explain me the new feature Automatic Z Offset Save/Restore ?
I can´t find anxthing about it in the printer settings/Special menu.

And: Can i set a label Question instead of issue ?

**Comment by knutwurst** [comment]
This only applies to the Chiron with integrated ABL feature. You don't need to set the offset in your slicer, like in the stock firmware.

**Comment by Jack77777777** [comment]
Thanks for the clarification
