### ISSUE TITLE
[BUG] (Thermistor temperature error)

### ISSUE THREAD

**Issue by DaniLeyend** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#168]
### Bug Description

The Hotend Temperature is displayed at 300º constantly.

### Steps to Reproduce

1. Download the source code. (Leatest version)
2. Change the Configuration.h file in line 488 #define TEMP_SENSOR_0 **1047** according to my thermistor
https://es.aliexpress.com/item/32859917151.html (it is the correct value)
4. Compile the firmware with Platformio in Microsoft Visual Studio
5. Flash the firmware (Chiron .hex) with XLoader to my 3D Printer Anycubic Chiron

**Expected behavior:** 

The thermistor marks the correct temperature Approx 20º same as the bed

**Actual behavior:** 

The Hotend thermistor temperature is displayed at 300º constantly.

#### Additional Information
I have tried other firmware and the thermistor temperature was working fine with this setting. (By the way, this is by far the best firmware and the most updated I have seen, I do not know how I have been able to live without it so far, but need to set up correctly that seeting).
Help please, I am not sure if i am messing up with something

![20210628_180742](https://user-images.githubusercontent.com/86618465/123672190-583f1300-d83f-11eb-95e7-0443b05ff435.jpg)
![screenshot](https://user-images.githubusercontent.com/86618465/123672349-7f95e000-d83f-11eb-8276-8a21e2ba0468.png)
![Configuration](https://user-images.githubusercontent.com/86618465/123672448-9b998180-d83f-11eb-9563-3fafde9b643f.png)
![Configuration_adv](https://user-images.githubusercontent.com/86618465/123672452-9c321800-d83f-11eb-88a1-97e2d2b189fd.png)
The last 2 files are my Configuration.h and Configuration_adv_h renamed to .png if necessary

**Comment by DaniLeyend** [comment]
I just changed the thermistor for a different one, I have recompiled the firmware and apparently everithing works fine

**Comment by knutwurst** [comment]
I'm glad that everything works fine ;)
