### ISSUE TITLE
Pause and Resume printing after filament change isn't working at all

### ISSUE THREAD

**Issue by Mrinmoyst1** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#169]
### Pause and Resume printing with filament change isn't working at all....

I paused my print after the filament ran out and then fed the new one on my Mega S. After that when I pressed continue, only the monitor was saying that the printer was running but the nozzle didn't move at all. No progress bar was seen. It disappeared totally. I think there are some bugs. Please solve the issue. Also try to introduce resume printing after power loss. I had this feature in the stock firmware and it worked like a charm. Your firmware is really great and better than any others currently available. Please introduce this feature and solve the issue as soon as you can.

**Comment by JernejL** [comment]
pausing and resuming is broken completely, my mega x will never offer to resume after pausing, it shows the "command sent" message forever.

**Comment by knutwurst** [comment]
This is a duplication. Please see #34 .
