### ISSUE TITLE
[QUESTION] Homing X=2, Not 0

### ISSUE THREAD

**Issue by Jack77777777** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#172]
I have Knutwurst 1.2.0 installed on my i3 Mega S. After homing X the head goes to X=2. Is this a feature or a bug ?

**Comment by Esquilo007** [comment]
Same here and I really like it, because so the endstops aren't triggered all the time... y is the same I think

**Comment by knutwurst** [comment]
Hi, yes. That the so called "homing backoff" which moves the print head away from the endstops after homing. (2mm in X and Y) so the endstop switches should last longer. 

I shouldn't be a problem during print, but if you experience any issues, please let me know.

**Comment by Jack77777777** [comment]
Great feature
