### ISSUE TITLE
[BUG] 1.2.0 breaks pause feature on i3 mega X

### ISSUE THREAD

**Issue by JernejL** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#177]
### Bug Description

As well as what is mentioned here ( https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/issues/169 ) that pause during filament change is broken, so is pause feature itself - when pressing pause on printing screen it gets permanently stuck in "command has been sent, waiting for response" screen. 
 
![photo_2021-07-27_07-42-47](https://user-images.githubusercontent.com/1741375/127101761-747e086d-7b6d-4bea-a185-69e45f6d17fe.jpg)

### Steps to Reproduce

1. Start printing
2. When printing begins, press pause

**Expected behavior:** Printer pauses and allows resuming

**Actual behavior:** Printer pauses and is stuck in command sent state. 

#### Additional Information

Printer is i3 mega X with newest knutwurst 1.2.0 firmware, modified with bltouch, filament sensor is disabled. 
Printing from sd card.

**Comment by knutwurst** [comment]
This is a known bug. Please see #34.
