### ISSUE TITLE
[FR] Enable host action commands

### ISSUE THREAD

**Issue by TeDsWeb** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#179]
I think enabling marlins host action commands and the host prompt support could be a great benefit for those who using octoprint or similar because this should enable these hosts to recognize for example that the filament runout sensor is triggered or not.

**Comment by knutwurst** [comment]
Hi @TeDsWeb 
I don't know exactly what you mean. Do you need M118 support for the ActionTrigger Plugin in Octoprint? I'll have a look at that... if that's not what you need, let me know :)

**Comment by TeDsWeb** [comment]
I think that the M118 support should do the trick and is probably the same kind of trigger.
