### ISSUE TITLE
[BUG] M0 for pause printing not working

### ISSUE THREAD

**Issue by jbrandek** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#182]
I tested the pause printing for filament change M0 but no show on printers screen to continue with printing and nozzle cools down...

Don't know if its the correct code to use for filament change, but i saw on the features that it supports pause at printing.

Please let me know if there if i should use another code to do that or printer do not support to show on screen

PS: I have octoprint so i can resume it over there but it should work without another device no?

**Comment by knutwurst** [comment]
Hi @jbrandek ,
Please take a look at the official [Marlin Documentation SD Pause Command](https://marlinfw.org/docs/gcode/M025.html). When you use M0, the printer stops the print - because it's just a stop which can not be resumed. Instead use M25.

Best,
Olli
