### ISSUE TITLE
[FR] New hotend board for mega pro ver. 0.0.3, how to connect bltouch?

### ISSUE THREAD

**Issue by poulsp** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#183]
### Description
How to connect bltouch to this hotend board, any ideas?
I'm talking about the ground and signal.
![bottom](https://user-images.githubusercontent.com/4759224/129114100-788a0320-561a-41ee-bc7a-b9ec2ab6f869.jpg)

![top](https://user-images.githubusercontent.com/4759224/129114122-f07f33ed-a63c-4e57-a22e-5e580c107e64.jpg)

**Comment by knutwurst** [comment]
There should be no problem following the official instructions. The pinout is the same.
