### ISSUE TITLE
The filament detection switch doesn't do anything

### ISSUE THREAD

**Issue by InoxDragoon** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#187]
### Description

Please add proper Filament Detection to the firmware. All I get is a message on the screen stating "unusual filament status", or something to that effect.

### Feature Workflow

1. Extruder pulls filament past the detection switch ("Empty spool").
2. Filament switch triggers a M206 command (lift about 1mm, then home X and Y Axis).
3. User manually changes filament.
4. User presses resume on the screen or within OctoPrint.
5. Printer homes in on previous print position.
5. Printer resumes printing.

**Comment by knutwurst** [comment]
The Filamentsensor is wired to the TFT at the front. So Octoprint doesn't know about it. The only workaround is to wire the Filament sensor to another pin and up to Octoprint or directly to the Pi.

If you print via SD, the sensor works as expected.
