### ISSUE TITLE
[FR] Expose additional UART pins for ESP3D

### ISSUE THREAD

**Issue by PapeCoding** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#194]
### Description

Out on GitHub there is another repository which enables a lot of printers to have wifi access. It is called [ESP3D](https://github.com/luc-github/ESP3D). They even have a [tutorial ](https://github.com/luc-github/ESP3D/wiki/Trigorilla) on how to get it working with the Trigorilla board. Unfortunately, this requires hijacking the UART pins from the USB port and soldering directly to the main board. Is it possible to somehow expose some already pre-soldered header pins on the board as UART pins to use with the ESP3D?

### Feature Workflow

1. Flash ESP3D board
2. Solder Jumper wires to the board
3. Put them somewhere on the board

#### Additional Information

* Especially interesting would be to still maintain the USB functionality while ESP3D is running.

**Comment by knutwurst** [comment]
Normally I would say: If you already have an ESP8266, you can swap the board for something fast and use RepRap firmware.

In this case I find it interesting that you can use an ESP01! That's really cool and I didn't know it before.

A second serial interface is theoretically possible directly. I just have to see which pins can be used for this.

Anyway, you made me curious ;)

**Comment by knutwurst** [comment]
@PapeCoding , I added an additional port which shares the command queue so it should work with USB simultaneously. The Pins are D16/D17 on the EXP1 header which are unused in most anycubic printers.

**Comment by knutwurst** [comment]
Hi.. I did some testing and..... it works!
The feature will be included in the next release.

![20210912_202433](https://user-images.githubusercontent.com/36196269/132998782-8dd080b8-0ba3-4068-88a2-7b7bde2f2930.jpg)

![Bildschirmfoto 2021-09-12 um 20 27 45](https://user-images.githubusercontent.com/36196269/132998716-14aa8f81-1c7d-4054-8a84-32e1f702122f.jpg)


![Bildschirmfoto 2021-09-12 um 20 27 57](https://user-images.githubusercontent.com/36196269/132998721-24fdf0d0-0173-4018-8de4-ac697f1c4f71.jpg)

**Comment by Esquilo007** [comment]
Cool feature 👍 I will also try this and give feedback

**Comment by PapeCoding** [comment]
Oh, wow, thank you @knutwurst!

I did not expect it to be integrated that fast! I am on holiday and will check it out next time I am on the printer :)

**Comment by knutwurst** [comment]
I would say: It's done :) -> https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/wiki/WLAN-Installation-(deutsch)

Currently only in german... but for now, I'm happy with the result.
