### ISSUE TITLE
[BUG] Fehler in der Dateiliste

### ISSUE THREAD

**Issue by wassereimer86** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#197]
Ich verwende die 1.3.0.-beta.2

Druck-Menü
![1](https://cloud.randnotizen.org/s/DCQSa1AyzG1CU4V/download)
Seite 2
![2](https://cloud.randnotizen.org/s/z2CUPSmosaTnTC9/download)
Leere dritte Seite (?)
![3](https://cloud.randnotizen.org/s/PlSdBeKRF2Jvfog/download)
Zurück zu Seite 2 - jetzt mit Anzeigefehlern
![4](https://cloud.randnotizen.org/s/BPdjXktXgVXJy13/download)
Erste Seite
![5](https://cloud.randnotizen.org/s/zDoqhT8uHPqDH5R/download)

**Comment by knutwurst** [comment]
Interessant... hast du ein Gerät über USB angeschlossen? Hast du mal versucht, die Dateiliste "langsamer" zu durchscrollen? Hast du andere SD Karten versucht? Tritt das nur mit der neuen 1.3.0 auf, oder auch schon vorher? 

Danke :)

**Comment by wassereimer86** [comment]
Das passiert ohne angeschlossenes USB. Ja, das scrollen hab ich eben langsam versucht - ändert nichts. Selbst mit 10 Sekunden Pause. Andere SD Karten in dem Format habe ich leider nicht. Mit der alten FW ist es mir zumindest nicht aufgefallen. Das heiß0t aber nicht unbedingt was, da ich erst seit einer kurzen Zeit mehrere Dateien auf der SD Karte habe und dadurch scrollen muss. Vorher hab ich es nicht versucht, weil da nichts war.

**Comment by HaGueRe** [comment]
Kann es sein, daß deine Dateiliste noch Umlaute oder gewisse Sonderzeichen enthält? Umlaute, Bindestrich und Leerzeichen brachten bei der Stock-Firmware den Any grundsätzlich zum Absturz. Ich meine zwar, daß Oliver das schon geändert hat, aber ich würde das trotzdem mal überprüfen.

Gruß Hans

**Comment by knutwurst** [comment]
Es werden ja auch Ordner durchsucht. Das geht bei der OFW nicht. Sonderzeichen werden gefiltert und stattdessen als Unterstrich dargestellt. 

Es kann trotzdem sein, dass irgendwas zu lang, zu groß oder kaputt ist. Gerade wenn die SD Karte hängt und nicht alle Dateien fehlerfrei gelesen werden können.

Ich würde es noch mal mit einer anderen Karte versuchen. Oder einmal alles auf den PC kopieren, Karte formatieren und wieder drauf.

**Comment by wassereimer86** [comment]
Ich hab nun, mit unveränderter SD Karte, diverse Versuche durchgeführt. Länge Dateinamen angepasst, Leerzeichen entfernt, Punkte, große Dateien entfernt etc. Ich habe nun ein Beispiel gefunden an dem es reproduzierbar bei mir auftritt. 3 Dateien = Fehlerhafte anzeige (wenn es keine zweite Seite geben sollte), 4 Dateien = kein Fehler. Ich glaube es könnte ein Fehler in der Seitenberechnung vorliegen?

![1](https://cloud.randnotizen.org/s/AuVGjXRyeqrci4g/download)
![2](https://cloud.randnotizen.org/s/LqLK7OuMy7bR1Mb/download)

**Comment by knutwurst** [comment]
Ohh... AAHH.... fuck..... 
Jetzt weiß ich auch, wo das Problem liegt! 

Ich hatte es auf meiner Todo-Liste, und hab es dann vergessen :/
Ich kümmere mich drum!
![Bildschirmfoto 2021-09-17 um 16 25 04](https://user-images.githubusercontent.com/36196269/133799664-277ba6d2-dbee-4837-8486-6ada8af2cce2.jpg)

**Comment by knutwurst** [comment]
Ist gefixed und kommt in die nächste Version. ;)
