### ISSUE TITLE
Whether more test points can be added to the automatic leveling matrix to increase the leveling accuracy and whether the detection speed can be adjustedWhether more test points can be added to the automatic leveling matrix to increase the leveling accuracy  whether the detection speed can be adjusted

### ISSUE THREAD

**Issue by Hua-Fen** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#203]
### Feature Workflow

1. [First Action]
2. [Second Action]
3. [and so on...]

#### Additional Information

* Provide pictures or links that demonstrate a similar feature or concept.

**Comment by knutwurst** [comment]
Hello,
Yes. of course. You only need to set up your parameters: https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/blob/04fcfa3b3058e1cd65763bea108ac1ec157b169b/Marlin/Configuration.h#L1747

But you need to compile the firmware by yourself.
