### ISSUE TITLE
Z2_DRIVER_TYPE  missing?

### ISSUE THREAD

**Issue by XoBoR** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#206]
Hi, first of all Dankeschön for this nice working firmware, saved me a lot of time!

Can it be that you are missing the definition of the driver type for the second Z driver, at least the MegaX has two Z axis steppers.

**Comment by Esquilo007** [comment]
It should not be Z2, but E1 as far as I know for the second driver

**Comment by XoBoR** [comment]
> It should not be Z2, but E1 as far as I know for the second driver

It's indeed connected to the Port labeled E1, but Marlin should still treat it as Z2 through the pin definition, I think.

**Comment by knutwurst** [comment]
> It's indeed connected to the Port labeled E1, but Marlin should still treat it as Z2 through the pin definition, I think.

Nope, the pin definitions indicate which ports the board has. What this port is used for will be decided later. So you have to define for the E1 port what is installed there, if you use it. In the pin definitions, the Trigorilla Board does not have a Z2.

**Comment by XoBoR** [comment]
> > It's indeed connected to the Port labeled E1, but Marlin should still treat it as Z2 through the pin definition, I think.
> 
> Nope, the pin definitions indicate which ports the board has. What this port is used for will be decided later. So you have to define for the E1 port what is installed there, if you use it. In the pin definitions, the Trigorilla Board does not have a Z2.

thanks for the clarification! 

I'm gonna close the issue.
