### ISSUE TITLE
[FR] Thermal runaway protection settings

### ISSUE THREAD

**Issue by TheOneWhoseUsernameWasTaken** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#213]
### Make thermal runaway protection configurable

I like to put some glue from a glue stick on my print bed to get better adhesion. However, if I do that while everything is still cold, then, by the time the printing starts, the glue has already dried out. I tend to get better results if I heat up the bed (and nozzle) in OctoPrint first, then apply the glue to the hot bed, then immediately start the print.

The problem is that the fresh glue will cool down the print bed a little bit, and that will trigger the thermal runaway protection. The printer stops the heaters and disconnects, the print bed and nozzle begin to cool off. I have to reconnect and get another (smaller) delay until the printing can start. It's not a mission critical problem, but annoying.

I was wondering if it was possible to make the TRP a little bit less sensitive, perhaps even configurable through a menu setting.

Alternatively, you could make it so TRP can be completely disabled, but I kind of like the idea of having a fail-safe in case something goes horribly wrong. I just want it to not trip during my normal workflow.

### Feature Workflow

1. Go into settings menu, select something like "thermal runaway protection".
2. Allow setting the parameters (e.g. enabled/disabled, hysteresis, time interval within which recovery is allowed, whatever).
3. TRP then follows those settings.

#### Additional Information

* Using Anycubic i3 Mega S.
* Relatively new to the world of 3D printing, so please pardon my ignorance.

**Comment by knutwurst** [comment]
The TRP is configurable within the source code. If you need some more "relaxed" settings, you unfortunately have to compile your own firmware for your application.

Usually, however, it is sufficient to carry out a PID tuning.
