### ISSUE TITLE
[BUG] Enabling TMC debugger and m122 does not actually allow the m122 command to function

### ISSUE THREAD

**Issue by Mavericks5252** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#216]
Ok, After flashing the board with a compiled version of the source code for the mega x dgus blt 10 I still am unable to get m122 to function. This is an issue because my stepper drivers appear to be fine both visually and resistances. None of my motors will turn and the motherboard is functioning properly as far as I can tell. I can still heat up the extruder and bed but the motors are non responsive.

**Comment by knutwurst** [comment]
Any updates?
