### ISSUE TITLE
[BUG] M42 I0 J0 not working

### ISSUE THREAD

**Issue by CactusChaos** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#217]
### Bug Description

When running "M42 IX JY" with any value from 0-4 for X and Y,
 the printer does not move to the correct mesh leveling position instead the servos keep turning and don't stop.

### Steps to Reproduce

1. Pronterface -> "M42 I0 J0"

**Expected behavior:** [What you expect to happen]
Move to mesh level position one

**Actual behavior:** [What actually happens]
Servos do not stop and grind at the end of their range of motion 

#### Additional Information
I3 Mega S, with TMC2209, running latest TMC firmware

**Comment by knutwurst** [comment]
Any updates?

**Comment by CactusChaos** [comment]
Sorry didn't see the reply ;( I will test it out shortly
