### ISSUE TITLE
[BUG] Stops printing at random layers

### ISSUE THREAD

**Issue by vleeuwenmenno** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#218]
### Bug Description

My AnyCubic i3 Mega S stops printing at a random layer.
I tried the same sketch on different locations and sometimes it just stops printing and stays where it is.

The temps show 200/200 60/60 but in reality the printer is coolling down and retrying the same print will cause the printer just stalling again but on a different level without any real pattern when it stops exactly.

### Steps to Reproduce

1. Put STL on SD Card
2. Try printing and wait

**Expected behavior:**

The print should proceed until it finishes.

**Actual behavior:** 

Print stops halfway or sometimes even earlier, nozzle cools down at it's last location it just stops dead in its tracks.

**Comment by knutwurst** [comment]
Any Updates?

**Comment by vleeuwenmenno** [comment]
This can be closed yes.

To close off the issue, the issue persists to exist randomly but less often after reorganising all my wiring so it's likely there's some wire that is broken or connection that is weak. But in any way it seems to indeed be hardware related and not firmware.
