### ISSUE TITLE
[FR] Support Anycubic 4 max Pro version 1?

### ISSUE THREAD

**Issue by kennethgomez01** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#221]
Hi, Just wondering if this firmware support for 4 max pro v1 not 2? Does this also has bltouch enabled already?

**Comment by hanebuechenes** [comment]
I read that i can use it for 4max pro 1? How?

**Comment by kennethgomez01** [comment]
> I read that i can use it for 4max pro 1? How?

Sorry what I mean, is this firmware works to any cubic 4 max pro?. Anyhow I have a firmware that works for 4 max pro v1.

**Comment by hanebuechenes** [comment]
I think you can use this for all 4max versions, but maybe you need some modifications.. i dont know. i have V1 and want to have this firmware on it. do you have this 1.3.1 version here for 4max 1?

**Comment by kennethgomez01** [comment]
@hanebuechenes I have the marlin 2.0. Let me give you a tip since this does not support the z offset wizzard for 4max pro(spent almost 2 weeks to do z offset) , don't trust videos(anycubic i3) they are not helpfl, you need to trust your eyesight.

**Comment by hanebuechenes** [comment]
So i tried the version here 1.3.1, i found it as a compiled file. Seems to work good only the Y axis is wrong dierction, have to change this.

**Comment by kennethgomez01** [comment]
the firmware I use has no problem. Take a note that the wiring must not replace the z limit switch.

**Comment by kennethgomez01** [comment]
@hanebuechenes how did you solve the z-axis going down and stuck there when pressing "Home All" ?

**Comment by hanebuechenes** [comment]
Compiled new. Change the value Form Y Axis. Load the Standard values after Install in Print Special Menü!

**Comment by kennethgomez01** [comment]
@hanebuechenes If its ok can you send me the actual line code?

**Comment by kennethgomez01** [comment]
because I don't know whic Y axis from the code are you refering too.

**Comment by hanebuechenes** [comment]
So, i changed:
configuration.h
Line 1765 ff. for the printbedsize
Line 1533 for the Y axis direction

**Comment by kennethgomez01** [comment]
@hanebuechenes to clarify this solved the z axis(up & down of the bed)?

**Comment by kennethgomez01** [comment]
can you copy the actual change here please.

**Comment by hanebuechenes** [comment]
I dont know exactly anymore.. Sorry. I think, the loading of the standard values and saving this to eeprom solved this problem... Maybe it is because of the wrong endstop is coded wrong..

**Comment by hanebuechenes** [comment]
For changing Y direction (or other directions, if wrong):

#if ENABLED(KNUTWURST_4MAX)
        // Invert the stepper direction. Change (or reverse the motor connector) if an axis goes the wrong way.
        #define INVERT_X_DIR false // set to true for stock drivers or TMC2208 with reversed connectors
        #define INVERT_Y_DIR **true** // set to false for stock drivers or TMC2208 with reversed connectors
        #define INVERT_Z_DIR false // set to false for stock drivers or TMC2208 with reversed connectors

**Comment by hanebuechenes** [comment]
Maybe you must look here:

// @section homing

//#define NO_MOTION_BEFORE_HOMING // Inhibit movement until all axes have been homed

//#define UNKNOWN_Z_NO_RAISE      // Don't raise Z (lower the bed) if Z is "unknown." For beds that fall when Z is powered off.

//#define Z_HOMING_HEIGHT  4      // (mm) Minimal Z height before homing (G28) for Z clearance above the bed, clamps, ...
                                  // Be sure to have this much clearance over your Z_MAX_POS to prevent grinding.

//#define Z_AFTER_HOMING  10      // (mm) Height to move to after homing Z

// Direction of endstops when homing; 1=MAX, -1=MIN
// :[-1,1]
#define X_HOME_DIR -1
#define Y_HOME_DIR -1
#define Z_HOME_DIR -1

**Comment by kennethgomez01** [comment]
so how does bltouch do to your print from 4 mac pro? Thanks for the info.

**Comment by kennethgomez01** [comment]
@hanebuechenes  do you still have the copy of config file that works to you? Sorry its allot to ask, for this type of printer its hard to find for support

**Comment by hanebuechenes** [comment]
Yes, i think my actual file is running fine!

**Comment by kennethgomez01** [comment]
can you sent it through here if its ok @hanebuechenes ?

**Comment by hanebuechenes** [comment]
[Configuration.zip](https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/files/7458256/Configuration.zip)

**Comment by kennethgomez01** [comment]
thank you very much!

**Comment by hanebuechenes** [comment]
But remember to load factory defaults and save them to eeprom!

**Comment by kennethgomez01** [comment]
I mean I have the marlin 2.0 working with bltouch is just that the z offset is hard to config

**Comment by kennethgomez01** [comment]
I've been doing z-offset for 2 weeks, in some point in the bed the prints is not sticking.

**Comment by kennethgomez01** [comment]
@hanebuechenes what is your wiring looks like?

**Comment by hanebuechenes** [comment]
Ok.. i only made 4 point leveling and my prints are perfect!

**Comment by hanebuechenes** [comment]
My printer is complete stock. No changes.

**Comment by kennethgomez01** [comment]
@hanebuechenes wiring of bltouch sorry not clarifying that.

**Comment by hanebuechenes** [comment]
I dont have. i make manual leveling :) just oldschool.

**Comment by kennethgomez01** [comment]
so why return to manual if bltouch works for you?

**Comment by hanebuechenes** [comment]
No sorry, that was misunderstanding. I never had BLtouch running.

**Comment by kennethgomez01** [comment]
Oh.

**Comment by knutwurst** [comment]
@hanebuechenes can you tell me exactly what type of printer you have? I thought, the 4MAX had a different ürint bed size... Please have a look at the original Anycubic sources: https://github.com/ANYCUBIC-3D/4MAX/blob/9b36eb13a2f908d09cf3a486035a81b88a7bd576/Configuration.h#L758

So as I understand... Y must be inverted and the build volume is the same as the 4MAX Pro 2.0?

Thanks in advance. I'll reflect your changes in the next version ;)

**Comment by hanebuechenes** [comment]
I have 4Max pro 1
In this files the bedsize is wrong, so i had to change. also the axis direction. everything else seems to work (till now)..

**Comment by knutwurst** [comment]
Ahhh Wait... The 4MAX Pro 1 isn't the same as the 4MAX, right?

**Comment by hanebuechenes** [comment]
.. i think it is. Its just the first version. And then came V2.
Maybe this version also would work. i will check the differences.
This one i have: [https://www.anycubic.com/products/anycubic-4max-pro-3d-printer?variant=32416392773763](https://www.anycubic.com/products/anycubic-4max-pro-3d-printer?variant=32416392773763)

**Comment by knutwurst** [comment]
I thought there were 3 printers of the 4MAX family... 
4MAX = Something weird
4MAX Pro v1 and v2 ... the v2 has a direct drive and a case light...

And that's the reason I did not manage to get all configurations right :D

**Comment by hanebuechenes** [comment]
Ah ok :) so no, the V1 has the same case design. just some little changes, i dont know exactly now.

**Comment by knutwurst** [comment]
This is the original 4MAX (non-pro!)
https://3duss.de/product/anycubic-4max-formax-3d-drucker/

![Bildschirmfoto 2021-11-02 um 08 32 27](https://user-images.githubusercontent.com/36196269/139804202-ce4d400d-8c8e-4dc0-bbd8-70f631a5aaab.jpg)

**Comment by hanebuechenes** [comment]
Oh Cool, this ine looks nice! Is it from metal?

**Comment by knutwurst** [comment]
I think so. I don't know this printer :D 
But my firmware includes this configuration... 

4MAX (for the original non-pro)
4MAXP2 (for both, the Pro v1 and v2)

**Comment by hanebuechenes** [comment]
Nice code you made, easy to compile, easy to understand. A lot of knowledge down in the comments! Thanks alot!

**Comment by knutwurst** [comment]
Thanks very much!
But it's not just my merit. 3D printing lives from the community and without so many people like you who helped me with testing and figuring out configurations, it wouldn't have come this far :)

**Comment by hanebuechenes** [comment]
Thats true, but your project is really cool. so if i can help i will. i have some i3 megas and this 4max. i like anycube printers because of the axis constructions (the old models). so lets see what will come.  i´m in this 3d printing stuff since 3 weeks, so :)

**Comment by knutwurst** [comment]
Implemented in the current release 1.4.0 Beta 1. (See https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/releases)

**Comment by kennethgomez01** [comment]
@knutwurst do you manage  to help me how to enable bltouch and configuration? Because somehow whenever I plug bltouch as z_switch, and press "Home" the bed is going down increments 2 and never move up, but probe is fown waiting to touch the surface.

**Comment by kennethgomez01** [comment]
@knutwurst and complicated to communicate and understand this repository written  in Germannot English

**Comment by Erik262** [comment]
Maybe I will contribute to the 4Max Pro V1 part incl. BLTouch Wiring documentation etc. Since knutwurst is already using the newest Marlin Firmware, so I don't have to do that part on my repository xD.

But I'm really wondering why the 4MPV1 (4 Max Pro Version 1) config is used as the same as the 4MPV2 config? 
And the settings, especially for the acceleration part, are pretty high, in my opinion. Or are these settings taken from alfrank?

@knutwurst Willst du mich vielleicht bitte in die Facebook-Gruppe beitreten lassen?

**Comment by kennethgomez01** [comment]
@Erik262 what is the difference of this firmware and by pocketjogny firmware? Is these firmware more advance than johney version?

**Comment by Erik262** [comment]
> @Erik262 what is the difference of this firmware and by pocketjogny firmware? Is these firmware more advance than johney version?

This here, has the newest stuff. Stick to this one. Have you already tried the given firmware here?

**Comment by kennethgomez01** [comment]
@Erik262 no, I use pocketjohny, can you tell me which to enable config for 4max pro v1 including bltouch, as most are written in german.

**Comment by kennethgomez01** [comment]
I can't compile its always telling me `                 from C:\Users\Kenneth Gomez\Downloads\Marlin-2-0-x-Anycubic-i3-MEGA-S-master\Marlin-2-0-x-Anycubic-i3-MEGA-S-master\Marlin\src\MarlinCore.cpp:31:
C:\Users\Kenneth Gomez\Downloads\Marlin-2-0-x-Anycubic-i3-MEGA-S-master\Marlin-2-0-x-Anycubic-i3-MEGA-S-master\Marlin\src\MarlinCore.cpp:306:52: error: size of array 'sensitive_pins' is not an integral constant-expression
     static const pin_t (&sensitive_pins)[pincount] PROGMEM = OnlyPins<SENSITIVE_PINS>::table;
                                                    ^
C:\Users\Kenneth Gomez\Downloads\Marlin-2-0-x-Anycubic-i3-MEGA-S-master\Marlin-2-0-x-Anycubic-i3-MEGA-S-master\Marlin\src\MarlinCore.cpp:306:85: error: could not convert template argument 'X_STEP_PIN' from '<type error>' to 'signed char'
     static const pin_t (&sensitive_pins)[pincount] PROGMEM = OnlyPins<SENSITIVE_PINS>::table;
                                                                                     ^
C:\Users\Kenneth Gomez\Downloads\Marlin-2-0-x-Anycubic-i3-MEGA-S-master\Marlin-2-0-x-Anycubic-i3-MEGA-S-master\Marlin\src\MarlinCore.cpp:306:85: error: could not convert template argument 'X_DIR_PIN' from '<type error>' to 'signed char'
C:\Users\Kenneth Gomez\Downloads\Marlin-2-0-x-Anycubic-i3-MEGA-S-master\Marlin-2-0-x-Anycubic-i3-MEGA-S-master\Marlin\src\MarlinCore.cpp:306:85: error: could not convert template argument 'Y_STEP_PIN' from '<type error>' to 'signed char'
C:\Users\Kenneth Gomez\Downloads\Marlin-2-0-x-Anycubic-i3-MEGA-S-master\Marlin-2-0-x-Anycubic-i3-MEGA-S-master\Marlin\src\MarlinCore.cpp:306:85: error: could not convert template argument 'Y_DIR_PIN' from '<type error>' to 'signed char'
C:\Users\Kenneth Gomez\Downloads\Marlin-2-0-x-Anycubic-i3-MEGA-S-master\Marlin-2-0-x-Anycubic-i3-MEGA-S-master\Marlin\src\MarlinCore.cpp:306:85: error: could not convert template argument 'Z_STEP_PIN' from '<type error>' to 'signed char'
C:\Users\Kenneth Gomez\Downloads\Marlin-2-0-x-Anycubic-i3-MEGA-S-master\Marlin-2-0-x-Anycubic-i3-MEGA-S-master\Marlin\src\MarlinCore.cpp:306:85: error: could not convert template argument 'Z_DIR_PIN' from '<type error>' to 'signed char'
exit status 1
Error compiling for board Arduino Mega or Mega 2560.
`

**Comment by Erik262** [comment]
@kennethgomez01 I could try to build a BLTouch Version with KnutWurst Firmware this weekend. **BUT I CANT** promise you if it works for you because I'm not near my printer until Christmas. So, therefore, I can't test it. At Christmas, I will try to build a BLTouch Version of the 4Max Pro V1. on my own machine and do a pull request on GitHub.

**Comment by knutwurst** [comment]
@Erik262 it should be really straight forward when you know a suitable PIN for the Sensor (black/white wire). Everything else is already there within the KNUTWURST_BLTOUCH tree. I just didn't enable it, since I don't own a 4MAX Printer so I can not test it.

**Comment by Erik262** [comment]
@knutwurst So you mean I only have to put the "-DKNUTWURST_BLTOUCH" flag from "build_unflags" to "build_flags" and I'm done and my printer is ready to touch the printbed? xD (of course if the offset is correct etc.)

I'm already in the group, but thanks!

**Comment by knutwurst** [comment]
@Erik262 correct :D I mean... that "should" do the trick. It might need some more detailed configuration and at some points there are only default values for MEGA, MEGA_S etc but in general.. yes.

It also would be a good Idea to create a new PlatformIO profile like 4MAXP2_BLT.

**Comment by Erik262** [comment]
@knutwurst If so, really nice work! 👌

**Comment by knutwurst** [comment]
@Erik262 I just added the (completely untested!) BLTouch build environments. See 62479aa.
The fine tuning (offset, Pinout etc) is up to you :D

**Comment by kennethgomez01** [comment]
@knutwurst thanks for reponse, I am trying every marlin version that works for my printer, since I am having very difficult weeks(2 weeks) straight calibarting my z offset, as some part of the the bed is not sticking at all.

**Comment by Erik262** [comment]
@knutwurst That must be a nice feeling when everything works! I'm pretty sure it will! I can't wait to test this on my machine.

@kennethgomez01 let us know whether it works!

**Comment by kennethgomez01** [comment]
@Erik262 lucky for you it only takes time for your machine z-offset to set, and print perfectly. I am really having trouble having my first layer to stick on some parts of the bed for almost 3 weeks.

**Comment by Erik262** [comment]
@kennethgomez01 You are sure that this is a BLTouch related problem? Please show us some pictures of your first layer prints.

**Comment by kennethgomez01** [comment]
yes, as in the left side of the bed its perfect, its always in middle to right is having the adhesion problem. Buildplate is clean with paper towel soak in 99% alcohol. I did follow a video online about z-offset. But how many times I made it to work, I always having issue with adhesion. Sure I will publish a video later today to show you guys what I am having with it.

**Comment by Erik262** [comment]
@kennethgomez01 The other thing that you can do is to provide a mesh after bed leveling. Use pronterface and do:

1. G28 
2. G29
3. M500
4. M420 S1

And upload a picture.

Shoul look like this:
       0        1        2        3        4        5        6        7        8        9       10       11       12
 0 +0.03500 -0.02855 -0.09156 -0.15566 -0.22250 -0.29867 -0.38125 -0.45758 -0.51500 -0.54590 -0.55844 -0.56363 -0.57250
 1 +0.01869 -0.01856 -0.05355 -0.09305 -0.14383 -0.21602 -0.30324 -0.38746 -0.45064 -0.48415 -0.49888 -0.50610 -0.51707
 2 +0.00234 -0.00695 -0.01215 -0.02553 -0.05938 -0.12765 -0.22023 -0.31329 -0.38297 -0.41951 -0.43676 -0.44629 -0.45969
 3 -0.01393 +0.00144 +0.02248 +0.03217 +0.01352 -0.05072 -0.14723 -0.24723 -0.32193 -0.36066 -0.37977 -0.39103 -0.40621
 4 -0.03000 +0.00178 +0.04016 +0.06533 +0.05750 -0.00240 -0.09922 -0.20143 -0.27750 -0.31633 -0.33563 -0.34711 -0.36250
 5 -0.04428 -0.00747 +0.03596 +0.06615 +0.06324 +0.00837 -0.08337 -0.18082 -0.25285 -0.28864 -0.30564 -0.31512 -0.32836
 6 -0.05734 -0.02364 +0.01604 +0.04376 +0.04156 -0.00781 -0.09062 -0.17835 -0.24250 -0.27303 -0.28596 -0.29184 -0.30125
 7 -0.07236 -0.04528 -0.01310 +0.00888 +0.00535 -0.03877 -0.11166 -0.18823 -0.24340 -0.26810 -0.27650

**Comment by kennethgomez01** [comment]
@Erik262 I don't know if this is part of the problem, but the hotend temperature sometimes has greater than the preset temperature for example, hotend is set to 250, and the temperature went up 260(lowering down afterwards) my thermistor/cermic heat element is new and my heat block has silicone socks.

**Comment by Erik262** [comment]
Poketjonnys firmware works pretty well. I already printed with that firmware for over 200+ hours without any issues. Have you heard something about PID tuning? I think you made a lot of beginner mistakes like erasing the EEPROM after each flash etc.

**Comment by kennethgomez01** [comment]
@Erik262 what I do to each flash is M502 & M500

**Comment by kennethgomez01** [comment]
@Erik262 I've heared about PID before, but as I am no expert, I have no Idea how to use it.

**Comment by Erik262** [comment]
> @Erik262 I've heared about PID before, but as I am no expert, I have no Idea how to use it.

https://marlinfw.org/docs/gcode/M303.html

**Comment by kennethgomez01** [comment]
@Erik262 Error reported by printer
Your printer's firmware reported an error. Due to that OctoPrint will disconnect. Reported error: !! KILL caused by too much inactive time - current command: M303 E0 S250 C7 - Printer halted. kill() called!

**Comment by kennethgomez01** [comment]
Error:MAXTEMP triggered, system stopped! Heater_ID: 0
Recv: Error:Printer halted. kill() called!
Changing monitoring state from "Printing" to "Error"

**Comment by kennethgomez01** [comment]
@Erik262  `Bilinear Leveling Grid:
Recv:       0      1      2
Recv:  0 +0.152 +0.060 +0.045
Recv:  1 -0.033 -0.076 -0.018
Recv:  2 -0.018 -0.010 +0.044
Recv: 
Recv: X:270.00 Y:205.00 Z:11.79 E:37.35 Count X:27000 Y:16400 Z:9464`

**Comment by Erik262** [comment]
@kennethgomez01 You probably need a more dense grid, try this:

G28
G29 F50 L50 R250 B190
M500
M420 S1

check your print.

**Comment by kennethgomez01** [comment]
@Erik262 I got 5 x 5 points, z-offset of value -1.65 adhere everything in the left, but once it prints to the right, it starts everything messy again. Slicer(Cura) I tried both with adhesion but still not adhesive.

**Comment by kennethgomez01** [comment]
@Erik262 Using bed visualizer plugin in octoprint, the bed its almost flat, so hardware(bltouch) is working, it seems that when it comes to printing, there's delay reading mesh which maybe the reason in some part of the bed is unleveled..

**Comment by Erik262** [comment]
@kennethgomez01 I think you doing your mesh leveling, but for some reason, you don't save it or retrieve it for later printing. Show me your startscript please.

**Comment by kennethgomez01** [comment]
`G21 ; set units to millimeters
G90 ; absolute positioning
G1 F3600 ; set standard speed
M107 ; turn all fans off
G28 X Y ; home X and Y axis
G28 Z ; home Z axis
M140 S{material_bed_temperature} ; set bed temperature
M190 S{material_bed_temperature} ; wait for bed temperature
G29 ;autolevel
M500 ;save data
M420 S1 ;retrieve mesh
M300 S1108 P105 ;play melody
M300 S1661 P210 ; play melody
G1 X-5 Y5.0
G1 Z0
M104 S{material_print_temperature} ; set hotend temperature
M109 S{material_print_temperature} ; wait for hotend temperature
G92 E0.0 ; reset extruder distance position
G1 X-5 Y40.0 ; wipe nozzle on brass brush
G1 X-5 Y5.0 ; wipe nozzle on brass brush
G1 X-5 Y40.0 ; wipe nozzle on brass brush
G1 X-5 Y5.0 ; wipe nozzle on brass brush
G1 X0.0 Y5.0 Z0.25 ; set starting point
G1 Y60.0 E4.5 F1000.0 ; print intro line
G1 Y100.0 E21.5 F1000.0 ; print intro line
G92 E0.0 ; reset extruder distance position`

**Comment by Erik262** [comment]
Everything seems to be okay. Where did you install your BLTouch? The last thing I could imagine would be a wrong Nozzle_to_probe_offset. Until then, only pictures and or videos can help to get further. BTW, send me what you get with M503 and please in the formatted way or a file (file.txt or something)

**Comment by kennethgomez01** [comment]
@Erik262 I just drill a hole on the extruder box as yours, the bltouch act as z-min and remove the z-min switch.

**Comment by kennethgomez01** [comment]
@Erik262 also even I did the PID autotune, I believe there is a problem on the firmware that makes the temperature not constant, for example I set to 250, every minute it so goes to 230 - 252 c

**Comment by kennethgomez01** [comment]
- [Recv: echo:; Linear Units:
Recv:   G21 ; (mm)
Recv: echo:; Temperature Units:
Recv: echo:  M149 C ; Units in Celsius
Recv: echo:; Filament settings (Disabled):
Recv: echo:  M200 S0 D1.75
Recv: echo:; Steps per unit:
Recv: echo:  M92 X100.00 Y80.00 Z800.00 E422.00
Recv: echo:; Max feedrates (units/s):
Recv: echo:  M203 X150.00 Y150.00 Z25.00 E30.00
Recv: echo:; Max Acceleration (units/s2):
Recv: echo:  M201 X2000.00 Y2000.00 Z60.00 E10000.00
Recv: echo:; Acceleration (units/s2) (P<print-accel> R<retract-accel> T<travel-accel>):
Recv: echo:  M204 P300.00 R1500.00 T300.00
Recv: echo:; Advanced (B<min_segment_time_us> S<min_feedrate> T<min_travel_feedrate> J<junc_dev>):
Recv: echo:  M205 B20000.00 S0.00 T0.00 J0.02
Recv: echo:; Home offset:
Recv: echo:  M206 X0.00 Y0.00 Z0.00
Recv: echo:; Auto Bed Leveling:
Recv: echo:  M420 S0 Z10.00 ; Leveling OFF
Recv: echo:  G29 W I0 J0 Z0.11375
Recv: echo:  G29 W I1 J0 Z0.05875
Recv: echo:  G29 W I2 J0 Z0.01500
Recv: echo:  G29 W I3 J0 Z0.02125
Recv: echo:  G29 W I4 J0 Z0.02750
Recv: echo:  G29 W I0 J1 Z0.01250
Recv: echo:  G29 W I1 J1 Z-0.06500
Recv: echo:  G29 W I2 J1 Z-0.08250
Recv: echo:  G29 W I3 J1 Z-0.05750
Recv: echo:  G29 W I4 J1 Z-0.00750
Recv: echo:  G29 W I0 J2 Z-0.03875
Recv: echo:  G29 W I1 J2 Z-0.09375
Recv: echo:  G29 W I2 J2 Z-0.10750
Recv: echo:  G29 W I3 J2 Z-0.06500
Recv: echo:  G29 W I4 J2 Z-0.05375
Recv: echo:  G29 W I0 J3 Z-0.04750
Recv: echo:  G29 W I1 J3 Z-0.06875
Recv: echo:  G29 W I2 J3 Z-0.06500
Recv: echo:  G29 W I3 J3 Z-0.03625
Recv: echo:  G29 W I4 J3 Z-0.01125
Recv: echo:  G29 W I0 J4 Z-0.00625
Recv: echo:  G29 W I1 J4 Z-0.05125
Recv: echo:  G29 W I2 J4 Z-0.02375
Recv: echo:  G29 W I3 J4 Z-0.00250
Recv: echo:  G29 W I4 J4 Z0.03500
Recv: echo:; Hotend PID:
Recv: echo:  M301 P29.75 I2.58 D85.91
Recv: echo:; Bed PID:
Recv: echo:echo:  M304 P251.78 I49.57 D319.73
Recv: echo:; Z-Probe Offset:
Recv: echo:  M851 X0.00 Y-47.77 Z-1.65 ; (mm)
Recv: echo:; Filament load/unload:
Recv: echo:  M603 L538.00 U555.00 ; (mm)
Recv: ok ]

**Comment by kennethgomez01** [comment]
Also is it ok to power pi 4 directly to trigorilla board 5v pins? Because I think when since I powered it up directly to the board, it start acting like this.

**Comment by Erik262** [comment]
Well, I'm sorry, I don't know what everything you have done so far. From the software perspective, it seems everything to be okay. At this point, you have to figure out by yourself what happens wrongly.

**Comment by kennethgomez01** [comment]
@Erik262 no problem, thank you anyway. I also kinda solve the issue about temperature, it seems that removing sd card directly from the printer removes this bug.
