### ISSUE TITLE
4 Max Pro V1 Thermisistor issue

### ISSUE THREAD

**Issue by kennethgomez01** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#224]
I was having a problem with thermisitor value fluctuate, even I change my thermisistor multiple times, and did PID autune for both bed and hotend

`Error reported by printer
Your printer's firmware reported an error. Due to that the ongoing print job will be cancelled. Reported error: MAXTEMP triggered, system stopped! Heater_ID: E0 -`

**Comment by knutwurst** [comment]
Do you know what kind of thermistor the 4MAX Pro V1 uses? If it is different from the 4MAX Pro V2 there might be the issue :/ 

This is why it is still "Beta" ;) 

You could change the Thermistor in the Firmware or tra the 4MAX (non-pro) Firmware to test the temperature. Please be aware that your printer will not work correctly with the non-pro FW.

**Comment by kennethgomez01** [comment]
@knutwurst I fixed this issue, mostly the error occur when sdcard is plug to the 3D printer, and mange it to work with octoprint alone. But thanks for response.
