### ISSUE TITLE
[BUG] Filament in/filament out can not be stoped via TFT menu

### ISSUE THREAD

**Issue by vmax1145** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#230]
### Bug Description

Filament in and filament out with old blue-white TFT screen can not be stopped.

### Steps to Reproduce

1. Go to TFT menu  Tools->Filament on tft screen and press  Filament IN 
2. wait for extruder temperature reach 180 or more
3. Press Filament IN or Filament OUT 
4. Then Press Stop 

**Expected behavior:** Filament loading/unloading expected to be stopped immidiately. (as in stock firmware)

**Actual behavior:** Filament continue loading untill standard loading length step ends.

#### Additional Information
Printer: MEGA S, 
TFT screen: blue-white  , 
Motherboard: Trigorilla 1.1,  
firmware:  MEGA_S_v1.4.0-b3.hex  ( downloaded here )

* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by vmax1145** [comment]
Any ideas how to fix this?

**Comment by knutwurst** [comment]
Fixed in 1.4.0 Beta 5 ;)
