### ISSUE TITLE
[FR] G2/G3 arc support?

### ISSUE THREAD

**Issue by MrBill1234** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#231]
### Description

G2/G3 Arc Support 

### Feature Workflow

For use with Arc Welder plugin

#### Additional Information

None

**Comment by knutwurst** [comment]
Um... This is already supported since v1.3.0

**Comment by MrBill1234** [comment]
Ah ok, thank you.  Maybe add to FAQ, or features list?

I believe you included MeatPack too - may be worth adding a list of enabled (and disabled) marlin features in this build.
