### ISSUE TITLE
[BUG] Wrong placeholders in recommended Cura start code

### ISSUE THREAD

**Issue by JWRu** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#232]
"material_bed_temperature" should be replaced by "material_bed_temperature_layer_0" and "material_print_temperature" by "material_print_temperature_layer_0".
Otherwise Cura first layer temperature settings will be ignored.

**Comment by knutwurst** [comment]
Oh, good to know! Thanks!

**Comment by knutwurst** [comment]
Done: https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/wiki/Cura-Start--and-Endcode-with-preheat-and-purge-line
