### ISSUE TITLE
Zip file version

### ISSUE THREAD

**Issue by MTB4LIF3** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#236]
I tried to download the zip and edit it in arduino. I set the printer as Mega x and board as trigorilla 14 I unabled use controller fan. After uploading there was no special menu or temprature. Is this a error of me or of the program?

**Comment by knutwurst** [comment]
Firmware compilation is only possible via PlatformIO. See: https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/wiki
