### ISSUE TITLE
[FR] (Mega Pro Laser integration )

### ISSUE THREAD

**Issue by JMG964** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#241]
### Description

Is it possible to make the Laser of the Mega Pro working with this firmware. Would be a pleasure :) 

### Feature Workflow

1. [First Action]
2. [Second Action]
3. [and so on...]

#### Additional Information

* Provide pictures or links that demonstrate a similar feature or concept.

**Comment by knutwurst** [comment]
It is already working in the current 1.4.0 Beta, but it lacks the touchscreen implementation with the BMP scanning. But you can use other software like Lightburn to use the laser.
