### ISSUE TITLE
[BUG] Kann nicht kompiliert werden (include fehlt)

### ISSUE THREAD

**Issue by DeathmannX** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#243]
![image](https://user-images.githubusercontent.com/7075201/146681207-7d80ceb2-0d3f-4900-96f7-d4ef3f6129be.png)

Ich habe versucht die Firmware etwas anzupassen in der configuration.h um eine Bauraumheizung zu configurieren und die TMC 2208 Treiber.
Ich nutze das aktuelle Master build.

Ich habe Autobuild Marlin und PlatformIO installiert und es will einfach nix werden...
Mal so am Rande gefragt, weil ich dazu nix gefunden habe.
Die Bauraumheizung einfach über ein Mosfet an den "Heater 1" anschließen richtig?

Liebe Grüße und ein frohes Weihnachtsfest.

**Comment by knutwurst** [comment]
Das ist kein Bug. Bitte benutze kein MarlinAutoBuild und schaue einmal in's Wiki: https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/wiki
