### ISSUE TITLE
[BUG] No Sound on right (second) Z-Endstop Pin (Mega, Mega S)

### ISSUE THREAD

**Issue by xDraconix** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#244]
### Bug Description

When i homing the printer, the second Z Endstop doesnt make a beep. While i use it to adjust the right enstop screw. What must i change in the source to get that work?

German:

Der rechte Endtsop der Z Achse gibt kein BEEP aus, ich nutze dies aber um die Stellschraube zu kalibrieren. Was muss ich im Source umstellen damit mir auch dieser einen Beep ausgibt?

### Steps to Reproduce

1. Home the printer
2. no Sound on second Z Stop

**Comment by knutwurst** [comment]
Hi there,
what did you do to turn on the enstrop beeps? In fact, they are not activated at all.

And which version with which firmware variant did you compile?
