### ISSUE TITLE
[BUG] starts beeping then lifts 20mm and stops

### ISSUE THREAD

**Issue by jeff222g** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#246]
### Bug description 

<!- - print stops and unable to resume -->

### Steps to Reproduce

1.  filament sensor gets tripped or when filament sensor is turned off it just stops and makes the noise like it got tripped
2. Attempt to resume print 
3. It sits there and does not do so

**Expected behavior:** [the print should resume from where it left off]

**Actual behavior:** [it will sit until you restart the printer]

#### Additional Information
This is happening on the mega pro without BL touch. I’m sorry this is my first time using GitHub

**Comment by jeff222g** [comment]
It's happened with the filament sensor turned off as well. With the sensor turned off it just beeps with no error message and sits like you bit pause

**Comment by jeff222g** [comment]
I now see the resume feature is not possible, but am not totally sure why my print is stopping itself. I'm trying to run a 30 hours print and am worried I will waste a lot of material on random stops

**Comment by knutwurst** [comment]
Hi @jeff222g .. 
Are you sure you disabled the filament sensor before printing? it's only disabled temporary and will be re-enabled upon next boot.

The other question is: Which firmware version are you using? Start/Stop/Resume is not supported in the beta version atm.

**Comment by jeff222g** [comment]
I'm not 100% sure whether or not I turned it back off after reboot, I know before starting the print a 3rd time I made sure to hit it, but I think I'm going to bypass the filament sensor entirely and just leave a cut piece of filament in it. I am using the beta version

**Comment by makskr** [comment]
> 

Hi knutwurst . Which the last version supports pause/print for Chiron? 
I see that version 1.4.0-beta.3 has issues with filament sensor and pause/print.

**Comment by knutwurst** [comment]
Fixed in 1.4.0 Beta 5.
