### ISSUE TITLE
Chiron run out filament sensor doesn't work.

### ISSUE THREAD

**Issue by makskr** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#250]
### Bug Description

Chiron run out filament sensor doesn't work.

### Steps to Reproduce

When the filament is run out the Chiron screen shows "Lack of filament...", I press OK, then extruder heating and nothing happened.

**Expected behaviour:** Probably, when the temperature reached the needed settings, it should ask to pool in a new filament etc. 
**Actual behavior:**when the temperature reached the needed settings - nothing happens, just time on the screen goes forward.

**Comment by makskr** [comment]
Maybe need to uncomment //#define FILAMENT_RUNOUT_SENSOR ?

**Comment by knutwurst** [comment]
Fixed in 1.4.0 Beta 5

**Comment by makskr** [comment]
Thank you for your job!!
