### ISSUE TITLE
The TMC driver is replaced, but the firmware with _tmc in the name is not used. Is there any defect?

### ISSUE THREAD

**Issue by Hentioe** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#251]
Because I reversed the Dupont Wire Jumper after installing TMC drivers.
So the firmware I updated is: `MEGA_S_DGUS_v1.4.0-b3.hex`.

It is in the right direction and no problems have been found so far.  Are there any other advantages of firmware with tmc in the name besides the reverse motor direction?  In other words, what advantage I am missing.  The driver model I use is TMC 2226.

Thank you very much for your project, I also learned a lot from it.

**Comment by knutwurst** [comment]
Hi @Hentioe ,
if you use the reversed plugs with the stock firmware direction, your trinamic drivers will run in legacy mode and don't use the tmc timings. It works, but the motors can create weird whining noises.
