### ISSUE TITLE
BLtouch pin definition on alternate wiring?

### ISSUE THREAD

**Issue by FreewareFire** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#252]
Hi,

i soldered my BLtouch (clone - 3Dtouch) to my Hotend board. I used the alternate Method, using G1 G2 G3 and bridged H3-H4. So far so good. But unfortunally, it doesn't work out. The red and the blue LED is on. I used precompiled Firmware (with TMC and BLtouch - BLT_10) and also tried my self compiled. Do i need to change the Pin definitions? I followed the BLtouch installation from knutwurst. Except i used the alternate wiring method... M119 shows:

Recv:10:18:47.857: Reporting endstop status
Recv:10:18:47.857: x_min: open
Recv:10:18:47.858: y_min: open
Recv:10:18:47.858: z_min: TRIGGERED
Recv:10:18:47.858: z2_min: TRIGGERED
Recv:10:18:47.858: z_probe: open

any idea what should be wrong? M280 P0 S10 does nothing...

Kind Regards
Ralf

**Comment by knutwurst** [comment]
You don't need to change anything. You just use the precompiled BLT Version... but without further information or pictures, it is almost impossible to help. 

In most cases it's a wiring issue.
