### ISSUE TITLE
[FR] wifi not working

### ISSUE THREAD

**Issue by chevroux** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#256]
### Bug Description

No communication between WiFi module and Mega X

### Steps to Reproduce

1. configure esp module as described in the guide
2. solder module to Trigorilla 0.0.2
3. setup printer in web gui

**Expected behavior:**

Being able to configure and use the printer via web gui

**Actual behavior:**

The gui is fine, but there seems to be no communication between the module and the printer itself. The printer isn't reacting to any commands and when I try to get the printer's configuration it just shows nothing.

#### Additional Information

Baud rate is set to 500.000, rechecked that
Tried swapping RX and TX
The notification settings in the web gui only shows question marks in rectangulars

Could it be possible that they've changed the pinout for the header on trigorilla 0.0.2?
Is the wifi connectivity still disabled as of 1.3.1?
edit: seems to be disabled in the code :( I'll try to compile it myself then.

Maybe handle this bug report like a feature request - offer an additional wifi enabled version of the firmware :D

Thanks in advance!

**Comment by knutwurst** [comment]
The wifi must be activated manually in the source. The only version where it works out of the box is 1.3.0, but this causes issues with some USB webcams.
