### ISSUE TITLE
Can the laser engraving function of Mega pro be used on Mega x?

### ISSUE THREAD

**Issue by Hua-Fen** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#257]

**Comment by stklcode** [comment]
Can't see why it shouldn't. It's simply a laser diode connected to the hotend output, so if you got a laser and connect it properly, it should work equally after activating the firmware feature.

It's currently only enabled, if the environment is `KNUTWURST_MEGA_P`, so you have to change the condition to `# if EITHER(KNUTWURST_MEGA_P, KNUTWURST_MEGA_x)`. Don't know if the pinout is equal.

https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/blob/7b9e0c4e023b4533ff435551ded8a4041e2a64ba/Marlin/Configuration_adv.h#L3385-L3390
