### ISSUE TITLE
[FR] Question about cloning repo

### ISSUE THREAD

**Issue by joseaguardia** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#261]
Hi!

Sorry to write a FR for this question, but I can't find another way to contact the developer.

Does anyone know how to clone the code from a precompiled? That is, what I want is the code of, for example, knutwurst_MEGA_S_BLT_10_v1.3.1.hex

It's possible?

Thanks a lot.

**Comment by knutwurst** [comment]
You have several options. You can use your GIT client to switch to a specific TAG and use the provided codebase, or you switch the tag within github and hit the download button:
![Bildschirmfoto 2022-01-20 um 08 56 02](https://user-images.githubusercontent.com/36196269/150296842-75ff66f0-84df-41cb-816a-26ae3a93e9a3.jpg)

Also you can just download the corresponding source code for every release as zip directly under "assets":
![Bildschirmfoto 2022-01-20 um 08 56 30](https://user-images.githubusercontent.com/36196269/150296932-145970f8-b976-4738-8b83-fe36974c4b13.jpg)

**Comment by joseaguardia** [comment]
Thank you!
