### ISSUE TITLE
[FR] (bltouch on 4max pro 2 plugged into z end stop)

### ISSUE THREAD

**Issue by bigmacreejr** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#264]
HI! I'm sorry for using fr for this type of question, im currently new to posting/commenting on github so i apologize if I ramble or do something wrong, but for the life of me I cant figure out how to fix this issue ive been having with my 4max pro 2.0 with bltouch

 so I installed bltouch's white and black wires where the z- plug was, and re-organized the 3 wires and plugged those into the free servo port.
 it appears to work because when I power on the printer it retracts and extends a few times and stays glowing constantly, but whenever I go and try to do auto bed leveling (whether that be with g29 code on a 3d file gcode, or using special menu auto bed leveling) it moves the bed down a tiny bit (never bringing it back up on its own btw so after a while of attempts of trying to fix it i have to manually raise it) and the printer moves towards the left of the printer, but instead of stopping at or near the left side, it crashes into it making a god awful noise as if it was trying to go further left than it can, in which I usually turn off the printer via the switch, but if the red button on the stop is pressed it kills itself and pops up on pronterface / octoprint that it halted and killed and acts it acts like it errored meaning the file menu no longer works.

the bltouch is installed directly onto the side almost exactly like how jpmini showed in her thread was. I've also tried mesh insets up to 30 and margins up to 30 inside config_adv and tried different negative values to probe to nozzle offsets for the x and y value, but no matter what I cant seem to get past homing the the left and crashing into it, thank you for talking your time reading this and if someone can assist me that would be amazing, and if you need me to send anything just ask im willing to oblige,

**Comment by MasterYod4** [comment]
![142023750-98670638-b1dd-4a83-a95a-0f3dc9b49500](https://user-images.githubusercontent.com/16502294/153847872-6a9667f9-2d13-4856-9dc4-e493340e4463.jpg)
