### ISSUE TITLE
Y Axis Layer Shift Mega Pro[BUG]

### ISSUE THREAD

**Issue by Girdiddle** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#265]
### Bug Description

layer shift on Y axis from flat layers. Top and bottom

### Steps to Reproduce

1. Printed STL that had large flat surface and got a layer shift
2. re sliced and checked gcode. still happened
3. went to stock firmware layer shift gone on same g code

**Comment by knutwurst** [comment]
Please read the [FAQ](https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/wiki/FAQ-(english)).

In general, this has nothing to do with the firmware itself but with your hardware.
