### ISSUE TITLE
Mega X Filament Runout and Octoprint not functioning

### ISSUE THREAD

**Issue by leitenky** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#267]
### Bug Description

When using the latest 1.4.0-beta 5, the filament runout still does not pause the print.

### Steps to Reproduce

1. Setup Octoprint with pause scripts, and runout enabled (using M412 S1 in start code)
2. Start a print with filament in the sensor
3. Wait for filament to run out of the sensor

**Expected behavior:** 
Printer should initiate Pause script to allow filament reload

**Actual behavior:** 
Alert on screen pops up, and self dismisses, but print does not pause

#### Additional Information
Octoprint config:
https://www.reddit.com/r/3Dprinting/comments/l6xei2/how_to_detect_filament_runout_in_marlin_and/

**Comment by knutwurst** [comment]
Please see #187
