### ISSUE TITLE
[BUG] Unable to compile firmware with UBL enabled - i3 Mega S with TMC and BMG

### ISSUE THREAD

**Issue by Ekodas** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#277]
I have an i3 Mega S with TMC drivers, DGUS 2 screen, BMG extruder, and BL Touch installed on Pin 4 using UBL.  I have previously modified and compiled custom firmwares from version 1.16 through 1.3.0 with no problems.  Starting with 1.4.0 and also with 1.4.1, I am unable to compile firmware as soon as I enable UBL.  I have everything configured in my configuration.h and configuration_adv.h files the same as I had them with 1.3.0.  If I leave it set for bilinear leveling, the firmware will compile.  However, as soon as I disable bilinear and activate UBL, I receive the following error at the very end of compiling:

Linking .pio\build\mega2560\firmware.elf
C:\Users\Kris\AppData\Local\Temp\ccjsqgcg.ltrans17.ltrans.o: In function `unified_bed_leveling::smart_fill_wlsf(float const&)':
<artificial>:(.text+0x978): undefined reference to `finish_incremental_LSF(linear_fit_data*)'
C:\Users\Kris\AppData\Local\Temp\ccjsqgcg.ltrans17.ltrans.o: In function `unified_bed_leveling::tilt_mesh_based_on_probed_grid(bool)':
<artificial>:(.text+0x11bc): undefined reference to `finish_incremental_LSF(linear_fit_data*)' 
collect2.exe: error: ld returned 1 exit status
*** [.pio\build\mega2560\firmware.elf] Error 1
================================= [FAILED] Took 28.05 seconds =================================

Any recommendations or advice would be greatly appreciated!

Thanks!

**Comment by knutwurst** [comment]
Since UBL heavily relies on a fully working smart display controller (Like 2004 or 12864) this firmware is not intended to use UBL in the first place.

I can take a look, but to be honest... that's not a bug, because it's not supported at all.
