### ISSUE TITLE
Updated screenshot of board

### ISSUE THREAD

**Issue by HowardEdidin** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#28]
### Description

I do not see where the x, y, and z endstop connectors are plugged into

### Feature Workflow

1.When adding an external ABL one must unplug the existing end stop connector
2. It is plugged into the ABL  controller 
3. One example is EXABL from TH3D

#### Additional Information

* Provide pictures or links that demonstrate a similar feature or concept.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by knutwurst** [comment]
Hi @HowardEdidin ,
I don't think I fully understand your question. Are you missing instructions on where which plug goes? There is tons of video footage from Anycubic itself. Or what exactly are you missing?

See: https://www.youtube.com/watch?v=O-0fdBljgDo

**Comment by knutwurst** [comment]
Is this still an issue?
