### ISSUE TITLE
[BUG] 4 Point Level applies mesh leveling grid

### ISSUE THREAD

**Issue by esprudzs** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#282]
### Bug Description

When using 4 Point Level, leveling mesh is applied if available resulting in ever growing Auto Leveling mesh values if used sequentially.

### Steps to Reproduce

1. Level your bed somewhat - manually, for instance
2. Run Auto Leveling through printer menu
3. Note mesh values
4. Run 4 Point Level with a sheet of paper
5. Run Auto Leveling again
6. Note the entire grid up by approx the thickness of the sheet of paper
7. Iterate until run out of adjustment screw/spring length if you like :)

**Expected behavior:** [What you expect to happen]

No mesh offset applied, so 4 Point Leveling is true to the printer, not the current Auto Leveling mesh.

**Actual behavior:** [What actually happens]

Mesh offset is applied, so the 4 Point Leveling is true to the current Auto Leveling mesh, not the printer geometry.

#### Additional Information

Hardware: Mega_S_TMC_BLT_10, additional extruder with single nozzle setup, activated by toggling enable pins for the drivers.
Workaround: Issue M420 S0 through a terminal application before engaging 4Point Level.

**Comment by knutwurst** [comment]
Huh.. that's a good catch!
That's because the Mesh is now automatically enabled after homing. 

Thanks for finding the bug. It will me fixed in the next release!

**Comment by knutwurst** [comment]
Fixed in [1183a5b](https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/commit/1183a5b51cf196eae15f6ced065e2d76474aa549).
