### ISSUE TITLE
Any-i3 Netzteillüfter Link zu 1-1 Ersatz ungültig

### ISSUE THREAD

**Issue by Majestix67** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#284]
Hallo Oliver, ich bin neu hier, hab mir nun alles zu Deiner Firmware und BL-Touch durchgelesen. Danke für die unglaubliche Leistung die Du hier bringst. Nun zu meiner Frage und dem eigentlichen Thema.
Im Thema zum Netzteillüfter https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/wiki/Gegen-welchen-L%C3%BCfter-soll-ich-den-L%C3%BCfter-im-Netzteil-austauschen%3F hast Du ganz unten einen Aliexpress Link zu einem Alternativem Leiselüfter gesetzt der leider nicht mehr funktioniert. Wenn ich nach diesem 60mm Lüfter google bemühe scheint es den allerdings in verschiedenen Dicken von 10 bis 25mm zu geben. Ich muss diesen austauschen da meiner mit brüllen einen Lagerschaden ankündigt, und will natürlich bestellen bevor ich den Drucker zerlege. 60x60mm ist klar aber welche Dicke ist da eingebaut bzw. hat Platz?
Vielleicht kannst Du den Link aktualisieren. Vielen Dank im Voraus

**Comment by Majestix67** [comment]
Nö vader, mechanisch will ich am Netzteil nichts ändern. Brauche einen den ich 1zu1 tauschen kann, dazu muss ich aber die Abmessungen wissen. In deinem Link wird da ja ein Monster eingebaut mit gedrucktem Gehäuse.
Die Marke kenne ich, die sind klasse, das ist wie BeQuiet im PC.

**Comment by knutwurst** [comment]
Hallo @Majestix67 :)
Sorry... du hast Recht. Der Link bzw der Shop führt den Lüfter nicht mehr :( 

Ärgerlich... hab den Link jetzt aktualisiert und auch die Beschreibung angepasst, sodass man sich den Lüfter in einem Shop seiner Wahl bestellen kann. Im Grunde ist es aber einfach ein Sunon MagLev 6015 Lüfter. Also 60mm im Durchmesser und 15mm Dicke. 

[Sunon MagLev HA60151V4](https://s.click.aliexpress.com/e/_9A6mlZ)

Der mit 12V und 0,6W ist deutlich leiser aber hat kaum weniger Durchsatz als der Originale. Es gibt aber auch andere etwas lautere mit 1,3W. Das halte ich aber für übertrieben.

Olli

**Comment by Majestix67** [comment]
Vielen Dank Olli, 15mm Dicke, das wars was mir fehlte. 
Ich muss jetzt nach fast einem Jahr alle Lüfter tauschen. Fürs Mainboard hast Du ja auch einen tollen Vorschlag, einen zweiten auf die originale Halterung, da ist ein 50x50x10mm drauf, richtig? 
Wenn ich den Freund zerlege dann alles gleich mal durch. Neue FW, MK4 Halterung fürs Hotend, BL-Touch ....

**Comment by knutwurst** [comment]
Das ist eigentlich Standard mit den 15mm, aber klar... sowas sieht man von Außen ja nicht :) 
Der HA60151V41000UA99 ist übrigens am leisesten und wenn man ihn dauerhaft auf 12V betreibt, ist die Kühlung wirklich ausreichend. 

Ja, der Originale ist ein 5010, aber der vibriert heftig und ist auch richtig laut. Deswegen die 2x 40mm. Wenn du noch größere Kühlkörper auf die Motortreiber klebst, musst du noch Unterlegscheiben benutzen, damit die Lüfter nicht aufliegen.
