### ISSUE TITLE
[INFO] Would not be possible without knutwurst on affordable hardware

### ISSUE THREAD

**Issue by esprudzs** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#286]
Mega S, customized for multi material, single nozzle printing, 3DTouch, TMC2008, dual part cooling fan. Thank you!

![IMG_8608](https://user-images.githubusercontent.com/59663811/154796285-46cec65d-5224-4a3d-8b04-6e93601436bc.jpg)
![IMG_8611](https://user-images.githubusercontent.com/59663811/154796721-4813fbcf-2598-41e5-a589-ee414a4f587b.jpg)

PS Maybe an "I did this with knutwurst" section is due here :)

**Comment by knutwurst** [comment]
Many thanks!
I'm glad your printer is working so well :)

**Comment by drsurfer** [comment]
I wonder why this post is marked [BUG] and still not closed. I understand the will to praise the effort of Oliver & co., but polluting this section isn't the right way to do. Just my opinion.
