### ISSUE TITLE
[BUG] Z-offset on Chiron is not correct after auto leveling

### ISSUE THREAD

**Issue by JonasGe** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#291]
### Bug Description

When running the auto leveling with the stock probe, the Z-offset is not correct (nozzle is too high).
When I add a M420 S1 L1 to the start GCode, the nozzle crashes into the bed.

### Steps to Reproduce

1. Install FW
2. Restore default EEPROM values & save values
3. Reset mesh
4. Auto leveling with stock probe, finishes probing all points and beeps.
5. Save values in EEPROM
6. Start GCode listed on the wiki of this repo, nozzle prints in the air

**Expected behavior:** Auto-level and press print for a good quality print

**Actual behavior:** Auto-level, press print and produce plastic spaghetti.

#### Additional Information

If I add the Z-offset to the start GCode with `M851 Z-XX.XX` and M420 S1 L1, the printer works fine.
I believe you removed the M420 part from the start GCode in the wiki, was there a reason to remove it?

**Comment by knutwurst** [comment]
What firmware version are you using? M420 S1 is no longer necessary as the mesh is (or should be) automatically activated immediately after the G28.

If it doesn't, then it's a bug :/

**Comment by JonasGe** [comment]
Your latest release, 1.4.3. I'll try with removing M420 and leaving the M851.

**Comment by knutwurst** [comment]
Also the Offset should be saved when changed via the touchscreen. Strange.

**Comment by knutwurst** [comment]
Damn.. I'll check this. Thanks!

**Comment by JonasGe** [comment]
I'll paste my M503 output when my print finishes.
