### ISSUE TITLE
[BUG] Fine tune Z probe offset via Special Menu during the print, I3 Mega S

### ISSUE THREAD

**Issue by markecskace** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#292]
### Bug Description

I am using MEGA_S_TMC_BLT_10_v1.4.3 FW with Anycubic I3 Mega S and genuine Bl-touch. I am also using Octoprint.

During the print, I would like to fine tune Z probe offset via Special Menu for better first layer adhesion (Babystepping). It does not work. My current offset is 2.44 mm and I can change it via Special Menu from let say 0.0 to any number and it does not affect the height of the nozzle during the print.

I have to set z probe offset and perform autoleveling before I start the print. Only then it is properly set. 

What am I doing wrong? Is it not possible to change the Z probe offset via a Special Menu during the print? If I got it wrong, then I apologize. 

### Steps to Reproduce

1. load FW, I select "LOAD FW DEFAULTS" and "SAVE EEPROM" via Special Menu
2. set Bl touch offset, set E-steps and other stuff...
4. restart
3. perform easy 4 point level
4. "SAVE EEPROM" via Special Menu
5. start Auto leveling via Special Menu

6. Print and try to perform fine tune Z probe offset via Special Menu, hit "SAVE EEPROM" just to be sure
7. after maybe failed first level, stop the print 
8. set new z offset and again start Auto leveling via Special Menu
9. repeat the last three steps until the first layer eventually sticks to the bed.

**Expected behavior:** 
real-time fine tune Z probe offset via Special Menu during the print

**Actual behavior:** 
fine tune Z probe offset via Special Menu during the print, does not work
#### Additional Information

Thank you for all your work so far.

Send: M503
Recv: echo:; Linear Units:
Recv:   G21 ; (mm)
Recv: echo:; Temperature Units:
Recv: echo:  M149 C ; Units in Celsius
Recv: echo:; Filament settings (Disabled):
Recv: echo:  M200 S0 D1.75
Recv: echo:; Steps per unit:
Recv: echo:  M92 X80.00 Y80.00 Z400.00 E411.00
Recv: echo:; Max feedrates (units/s):
Recv: echo:  M203 X500.00 Y500.00 Z6.00 E40.00
Recv: echo:; Max Acceleration (units/s2):
Recv: echo:  M201 X3000.00 Y2000.00 Z60.00 E10000.00
Recv: echo:; Acceleration (units/s2) (P<print-accel> R<retract-accel> T<travel-accel>):
Recv: echo:  M204 P4000.00 R1500.00 T4000.00
Recv: echo:; Advanced (B<min_segment_time_us> S<min_feedrate> T<min_travel_feedrate> X<max_x_jerk> Y<max_y_jerk> Z<max_z_jerk> E<max_e_jerk>):
Recv: echo:  M205 B20000.00 S0.00 T0.00 X20.00 Y20.00 Z0.40 E10.00
Recv: echo:; Home offset:
Recv: echo:  M206 X-4.00 Y2.00 Z0.00
Recv: echo:; Auto Bed Leveling:
Recv: echo:  M420 S1 Z10.00 ; Leveling ON
Recv: echo:  G29 W I0 J0 Z-0.03500
Recv: echo:  G29 W I1 J0 Z0.07750
Recv: echo:  G29 W I2 J0 Z0.13500
Recv: echo:  G29 W I3 J0 Z0.11750
Recv: echo:  G29 W I4 J0 Z0.00750
Recv: echo:  G29 W I0 J1 Z-0.08500
Recv: echo:  G29 W I1 J1 Z0.06250
Recv: echo:  G29 W I2 J1 Z0.12250
Recv: echo:  G29 W I3 J1 Z0.13000
Recv: echo:  G29 W I4 J1 Z0.06250
Recv: echo:  G29 W I0 J2 Z-0.09500
Recv: echo:  G29 W I1 J2 Z0.08250
Recv: echo:  G29 W I2 J2 Z0.15500
Recv: echo:  G29 W I3 J2 Z0.14750
Recv: echo:  G29 W I4 J2 Z0.04000
Recv: echo:  G29 W I0 J3 Z-0.07500
Recv: echo:  G29 W I1 J3 Z0.07750
Recv: echo:  G29 W I2 J3 Z0.15250
Recv: echo:  G29 W I3 J3 Z0.15500
Recv: echo:  G29 W I4 J3 Z0.07000
Recv: echo:  G29 W I0 J4 Z-0.00500
Recv: echo:  G29 W I1 J4 Z0.15250
Recv: echo:  G29 W I2 J4 Z0.21000
Recv: echo:  G29 W I3 J4 Z0.19000
Recv: echo:  G29 W I4 J4 Z0.08000
Recv: echo:; Endstop adjustment:
Recv: echo:  M666 Z0.00
Recv: echo:; Hotend PID:
Recv: echo:  M301 P12.28 I0.75 D50.06
Recv: echo:; Bed PID:
Recv: echo:echo:  M304 P251.78 I49.57 D319.73
Recv: echo:; Z-Probe Offset:
Recv: echo:  M851 X-30.00 Y-30.00 Z-2.44 ; (mm)
Recv: echo:; Linear Advance:
Recv: echo:  M900 K0.10
Recv: echo:; Filament load/unload:
Recv: echo:  M603 L60.00 U65.00 ; (mm)
Recv: ok

**Comment by knutwurst** [comment]
The special menu entry only sets the Z-Offset for the probe. It's **not** babystepping, because the touchscreen is not working while printing from SD. 

So if you are already printing via USB anyway, you have to use babystepping here too. See: https://marlinfw.org/docs/gcode/M290.html

The Z Offset setting uses M851 internally.

**Comment by markecskace** [comment]
ver.  1.1.8 Features: Babystepping is now usable without BLTouch
ver. 1.3.0 Features: [BLTouch Z Probe offset can be adjusted via Special Menu](https://www.youtube.com/watch?v=XNBlsdDNqvQ)

I think this led me to believe that it is possible to use this feature via special menu. My bad. Thanks for clarification. 
I will try M290 instead. Is BABYSTEP_ZPROBE_OFFSET enabled or disabled?

**Comment by knutwurst** [comment]
BABYSTEP_ZPROBE_OFFSET is disabled by default but maybe it's a good idea to enable it from my side ;)

**Comment by markecskace** [comment]
Yes, please! ;)

**Comment by knutwurst** [comment]
Done ;) ->  [0eaa8f9](https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/commit/0eaa8f902f2e990bd9ec694bbc7ddf4330374bea)

**Comment by markecskace** [comment]
Thank you! I have to compile firmware for myself, right?
So I just have to check this guide: 
https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/wiki/Howto:-Firmware-mit-PlatformIO-selbst-kompilieren

**Comment by knutwurst** [comment]
It's done :) 

Uhm, yes. It will be included in the next release, but if you need it now, you need to compile it by yourself... yes ;) 
Unfortunately, I haven't had time to translate the instructions into English yet. I hope you're still okay?

**Comment by markecskace** [comment]
Yes, no problem.  I understand a little German and would like to learn something new.  The translation add-on in the browser also helps. ;)
