### ISSUE TITLE
Compilation of "MEGA_P_DGUS_BLT_10" fails with errors (Vanilla)

### ISSUE THREAD

**Issue by fully-sikh** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#295]
### Bug Description

I am following instructions from FAQ on how to compile your firmware.
Downloaded a fresh copy of the code @ 7pm 24/02/2022

### Steps to Reproduce

1. Download a fresh copy of the code from github
2. Unzip to folder called "Knutwurst"
3. Open folder in VSCode
4. Click on PlatformIO--> Project Tasks--> MEGA_PDGUS_BLT_10-->Build
5. Error message while compiling

**Expected behavior:** Code should compile and produce a .HEX file

**Actual behavior:** Error messages while compiling

#### Additional Information

Compiling .pio\build\MEGA_P_DGUS_BLT_10\src\src\module\tool_change.cpp.o
Marlin\src\module\configuration_store.cpp: In static member function 'static void MarlinSettings::postprocess()':
Marlin\src\module\configuration_store.cpp:434:12: error: 'i' was not declared in this scope
   LOOP_XYZ(i) {
            ^
Marlin\src\module\configuration_store.cpp:434:3: error: 'LOOP_XYZ' was not declared in this scope
   LOOP_XYZ(i) {
   ^~~~~~~~
Marlin\src\module\configuration_store.cpp:434:3: note: suggested alternative: 'LOOP_L_N'
   LOOP_XYZ(i) {
   ^~~~~~~~
   LOOP_L_N
Marlin\src\module\configuration_store.cpp: In static member function 'static bool MarlinSettings::_load()':
Marlin\src\module\configuration_store.cpp:1428:38: error: 'i' was not declared in this scope
         if (!validating) LOOP_XYZE_N(i) {
                                      ^
Marlin\src\module\configuration_store.cpp:1428:26: error: 'LOOP_XYZE_N' was not declared in this scope
         if (!validating) LOOP_XYZE_N(i) {
                          ^~~~~~~~~~~
Marlin\src\module\configuration_store.cpp:1428:26: note: suggested alternative: 'LOOP_S_LE_N'
         if (!validating) LOOP_XYZE_N(i) {
                          ^~~~~~~~~~~
                          LOOP_S_LE_N
Marlin\src\module\configuration_store.cpp: In static member function 'static void MarlinSettings::reset()':
Marlin\src\module\configuration_store.cpp:2418:15: error: 'i' was not declared in this scope
   LOOP_XYZE_N(i) {
               ^
compilation terminated due to -fmax-errors=5.
*** [.pio\build\MEGA_P_DGUS_BLT_10\src\src\module\configuration_store.cpp.o] Error 1
================================================================================= [FAILED] Took 22.39 seconds =================================================================================
Environment         Status    Duration
------------------  --------  ------------
MEGA_P_DGUS_BLT_10  FAILED    00:00:22.390

**Comment by fully-sikh** [comment]
Hi Champ,
Just commenting so that the issue does not automatically get closed.
Thank you

**Comment by knutwurst** [comment]
Hey, sorry for the late answer...
Do you use Windows for compiling? Does the problem persist if you try something like the plain MEGA environment?

**Comment by fully-sikh** [comment]
Hi,
I'm using Visual Studio Code on Windows 10.
I just tried compiling multiple environments: MEGA_P_DGUS, MESA_S_DGUS, MEGA_S and MEGA all failed to compile.
Below is part of the error messages from compiling the plain MEGA environment:


========================================================
Compiling .pio\build\MEGA\src\src\lcd\extui\lib\ftdi_eve_touch_ui\ftdi_eve_lib\extended\unicode\font_size_t.cpp.o
Marlin\src\lcd\HardwareSerial.cpp: In function 'void __vector_54()':
Marlin\src\lcd\HardwareSerial.cpp:92:19: warning: unused variable 'c' [-Wunused-variable]
     unsigned char c = UDR3;
                   ^
Marlin\src\lcd\HardwareSerial.cpp: In member function 'void HardwareSerialClass::begin(long unsigned int, byte)':
Marlin\src\lcd\HardwareSerial.cpp:185:11: warning: unused variable 'current_config' [-Wunused-variable]
   uint8_t current_config;
           ^~~~~~~~~~~~~~
Marlin\src\lcd\HardwareSerial.cpp: In member function 'virtual size_t HardwareSerialClass::write(uint8_t)':
Marlin\src\lcd\HardwareSerial.cpp:292:12: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   while (i == _tx_buffer->tail)
          ~~^~~~~~~~~~~~~~~~~~~
Compiling .pio\build\MEGA\src\src\lcd\extui\lib\ftdi_eve_touch_ui\ftdi_eve_lib\extended\unicode\standard_char_set.cpp.o
Compiling .pio\build\MEGA\src\src\lcd\extui\lib\ftdi_eve_touch_ui\ftdi_eve_lib\extended\unicode\unicode.cpp.o
Compiling .pio\build\MEGA\src\src\lcd\extui\lib\ftdi_eve_touch_ui\ftdi_eve_lib\extended\unicode\western_char_set.cpp.o
Compiling .pio\build\MEGA\src\src\lcd\extui\lib\ftdi_eve_touch_ui\language\language.cpp.o
Compiling .pio\build\MEGA\src\src\lcd\extui\lib\ftdi_eve_touch_ui\marlin_events.cpp.o
Compiling .pio\build\MEGA\src\src\lcd\extui\lib\ftdi_eve_touch_ui\screens\about_screen.cpp.o
Compiling .pio\build\MEGA\src\src\lcd\extui\lib\ftdi_eve_touch_ui\screens\advanced_settings_menu.cpp.o
Compiling .pio\build\MEGA\src\src\lcd\extui\lib\ftdi_eve_touch_ui\screens\alert_dialog_box.cpp.o
Compiling .pio\build\MEGA\src\src\lcd\extui\lib\ftdi_eve_touch_ui\screens\backlash_compensation_screen.cpp.o
Compiling .pio\build\MEGA\src\src\lcd\extui\lib\ftdi_eve_touch_ui\screens\base_numeric_adjustment_screen.cpp.o
Compiling .pio\build\MEGA\src\src\lcd\extui\lib\ftdi_eve_touch_ui\screens\base_screen.cpp.o
Compiling .pio\build\MEGA\src\src\lcd\extui\lib\ftdi_eve_touch_ui\screens\bio_advanced_settings.cpp.o
Compiling .pio\build\MEGA\src\src\lcd\extui\lib\ftdi_eve_touch_ui\screens\bio_confirm_home_e.cpp.o
Compiling .pio\build\MEGA\src\src\lcd\extui\lib\ftdi_eve_touch_ui\screens\bio_confirm_home_xyz.cpp.o
Compiling .pio\build\MEGA\src\src\lcd\extui\lib\ftdi_eve_touch_ui\screens\bio_main_menu.cpp.o
Compiling .pio\build\MEGA\src\src\lcd\extui\lib\ftdi_eve_touch_ui\screens\bio_printing_dialog_box.cpp.o
Compiling .pio\build\MEGA\src\src\lcd\extui\lib\ftdi_eve_touch_ui\screens\bio_status_screen.cpp.o
Compiling .pio\build\MEGA\src\src\lcd\extui\lib\ftdi_eve_touch_ui\screens\bio_tune_menu.cpp.o
In file included from Marlin\src\lcd\extui\lib\ftdi_eve_touch_ui\language\language.h:23:0,
                 from Marlin\src\lcd\extui\lib\ftdi_eve_touch_ui\language\language.cpp:25:
Marlin\src\lcd\extui\lib\ftdi_eve_touch_ui\language\language_en.h:35:0: warning: "SUPERSCRIPT_TWO" redefined
   #define SUPERSCRIPT_TWO   u8"^2"

In file included from d:\3dprinter\knutwurst\marlin\src\inc/MarlinConfig.h:53:0,
                 from d:\3dprinter\knutwurst\marlin\src\marlincore.h:24,
                 from Marlin\src\lcd\extui\lib\ftdi_eve_touch_ui\language\language.cpp:23:
d:\3dprinter\knutwurst\marlin\src\core\language.h:558:0: note: this is the location of the previous definition
 #define SUPERSCRIPT_TWO   TERN(NOT_EXTENDED_ISO10646_1_5X7, "^2", "²")

Compiling .pio\build\MEGA\src\src\lcd\extui\lib\ftdi_eve_touch_ui\screens\boot_screen.cpp.o
Compiling .pio\build\MEGA\src\src\lcd\extui\lib\ftdi_eve_touch_ui\screens\case_light_screen.cpp.o
Compiling .pio\build\MEGA\src\src\lcd\extui\lib\ftdi_eve_touch_ui\screens\change_filament_screen.cpp.o
Compiling .pio\build\MEGA\src\src\lcd\extui\lib\ftdi_eve_touch_ui\screens\confirm_abort_print_dialog_box.cpp.o
Compiling .pio\build\MEGA\src\src\lcd\extui\lib\ftdi_eve_touch_ui\screens\confirm_auto_calibration_dialog_box.cpp.o
Compiling .pio\build\MEGA\src\src\lcd\extui\lib\ftdi_eve_touch_ui\screens\confirm_erase_flash_dialog_box.cpp.o
Compiling .pio\build\MEGA\src\src\lcd\extui\lib\ftdi_eve_touch_ui\screens\confirm_start_print_dialog_box.cpp.o
Compiling .pio\build\MEGA\src\src\lcd\extui\lib\ftdi_eve_touch_ui\screens\confirm_user_request_alert_box.cpp.o
Compiling .pio\build\MEGA\src\src\lcd\extui\lib\ftdi_eve_touch_ui\screens\default_acceleration_screen.cpp.o
Compiling .pio\build\MEGA\src\src\lcd\extui\lib\ftdi_eve_touch_ui\screens\developer_menu.cpp.o
Compiling .pio\build\MEGA\src\src\lcd\extui\lib\ftdi_eve_touch_ui\screens\dialog_box_base_class.cpp.o
Compiling .pio\build\MEGA\src\src\lcd\extui\lib\ftdi_eve_touch_ui\screens\display_tuning_screen.cpp.o
Compiling .pio\build\MEGA\src\src\lcd\extui\lib\ftdi_eve_touch_ui\screens\endstop_state_screen.cpp.o
Compiling .pio\build\MEGA\src\src\lcd\extui\lib\ftdi_eve_touch_ui\screens\feedrate_percent_screen.cpp.o
Compiling .pio\build\MEGA\src\src\lcd\extui\lib\ftdi_eve_touch_ui\screens\filament_menu.cpp.o
Compiling .pio\build\MEGA\src\src\lcd\extui\lib\ftdi_eve_touch_ui\screens\filament_runout_screen.cpp.o
Compiling .pio\build\MEGA\src\src\lcd\extui\lib\ftdi_eve_touch_ui\screens\files_screen.cpp.o
Compiling .pio\build\MEGA\src\src\lcd\extui\lib\ftdi_eve_touch_ui\screens\interface_settings_screen.cpp.o
Compiling .pio\build\MEGA\src\src\lcd\extui\lib\ftdi_eve_touch_ui\screens\interface_sounds_screen.cpp.o
Compiling .pio\build\MEGA\src\src\lcd\extui\lib\ftdi_eve_touch_ui\screens\jerk_screen.cpp.o
Compiling .pio\build\MEGA\src\src\lcd\extui\lib\ftdi_eve_touch_ui\screens\junction_deviation_screen.cpp.o
Compiling .pio\build\MEGA\src\src\lcd\extui\lib\ftdi_eve_touch_ui\screens\kill_screen.cpp.o
Compiling .pio\build\MEGA\src\src\lcd\extui\lib\ftdi_eve_touch_ui\screens\language_menu.cpp.o
Compiling .pio\build\MEGA\src\src\lcd\extui\lib\ftdi_eve_touch_ui\screens\linear_advance_screen.cpp.o
Compiling .pio\build\MEGA\src\src\lcd\extui\lib\ftdi_eve_touch_ui\screens\lock_screen.cpp.o
Compiling .pio\build\MEGA\src\src\lcd\extui\lib\ftdi_eve_touch_ui\screens\main_menu.cpp.o
Compiling .pio\build\MEGA\src\src\lcd\extui\lib\ftdi_eve_touch_ui\screens\max_acceleration_screen.cpp.o
Compiling .pio\build\MEGA\src\src\lcd\extui\lib\ftdi_eve_touch_ui\screens\max_velocity_screen.cpp.o
Compiling .pio\build\MEGA\src\src\lcd\extui\lib\ftdi_eve_touch_ui\screens\media_player_screen.cpp.o
Compiling .pio\build\MEGA\src\src\lcd\extui\lib\ftdi_eve_touch_ui\screens\move_axis_screen.cpp.o
Compiling .pio\build\MEGA\src\src\lcd\extui\lib\ftdi_eve_touch_ui\screens\nozzle_offsets_screen.cpp.o
Compiling .pio\build\MEGA\src\src\lcd\extui\lib\ftdi_eve_touch_ui\screens\nudge_nozzle_screen.cpp.o
In file included from Marlin\src\lcd\extui\lib\ftdi_eve_touch_ui\screens\../language/language.h:23:0,
                 from Marlin\src\lcd\extui\lib\ftdi_eve_touch_ui\screens\language_menu.cpp:24:
Marlin\src\lcd\extui\lib\ftdi_eve_touch_ui\screens\../language/language_en.h:35:0: warning: "SUPERSCRIPT_TWO" redefined
   #define SUPERSCRIPT_TWO   u8"^2"

In file included from d:\3dprinter\knutwurst\marlin\src\inc\marlinconfig.h:53:0,
                 from d:\3dprinter\knutwurst\marlin\src\lcd\extui\ui_api.h:45,
                 from Marlin\src\lcd\extui\lib\ftdi_eve_touch_ui\screens\../compat.h:31,
                 from Marlin\src\lcd\extui\lib\ftdi_eve_touch_ui\screens\../config.h:24,
                 from Marlin\src\lcd\extui\lib\ftdi_eve_touch_ui\screens\language_menu.cpp:23:
d:\3dprinter\knutwurst\marlin\src\core\language.h:558:0: note: this is the location of the previous definition
 #define SUPERSCRIPT_TWO   TERN(NOT_EXTENDED_ISO10646_1_5X7, "^2", "²")

Compiling .pio\build\MEGA\src\src\lcd\extui\lib\ftdi_eve_touch_ui\screens\preheat_menu.cpp.o
Compiling .pio\build\MEGA\src\src\lcd\extui\lib\ftdi_eve_touch_ui\screens\preheat_timer_screen.cpp.o
Compiling .pio\build\MEGA\src\src\lcd\extui\lib\ftdi_eve_touch_ui\screens\restore_failsafe_dialog_box.cpp.o
Compiling .pio\build\MEGA\src\src\lcd\extui\lib\ftdi_eve_touch_ui\screens\save_settings_dialog_box.cpp.o
Compiling .pio\build\MEGA\src\src\lcd\extui\lib\ftdi_eve_touch_ui\screens\screens.cpp.o
Compiling .pio\build\MEGA\src\src\lcd\extui\lib\ftdi_eve_touch_ui\screens\spinner_dialog_box.cpp.o
Compiling .pio\build\MEGA\src\src\lcd\extui\lib\ftdi_eve_touch_ui\screens\statistics_screen.cpp.o
Compiling .pio\build\MEGA\src\src\lcd\extui\lib\ftdi_eve_touch_ui\screens\status_screen.cpp.o
Compiling .pio\build\MEGA\src\src\lcd\extui\lib\ftdi_eve_touch_ui\screens\stepper_bump_sensitivity_screen.cpp.o
Compiling .pio\build\MEGA\src\src\lcd\extui\lib\ftdi_eve_touch_ui\screens\stepper_current_screen.cpp.o
Compiling .pio\build\MEGA\src\src\lcd\extui\lib\ftdi_eve_touch_ui\screens\steps_screen.cpp.o
Compiling .pio\build\MEGA\src\src\lcd\extui\lib\ftdi_eve_touch_ui\screens\stress_test_screen.cpp.o
Compiling .pio\build\MEGA\src\src\lcd\extui\lib\ftdi_eve_touch_ui\screens\string_format.cpp.o
Compiling .pio\build\MEGA\src\src\lcd\extui\lib\ftdi_eve_touch_ui\screens\temperature_screen.cpp.o
Compiling .pio\build\MEGA\src\src\lcd\extui\lib\ftdi_eve_touch_ui\screens\touch_calibration_screen.cpp.o
Compiling .pio\build\MEGA\src\src\lcd\extui\lib\ftdi_eve_touch_ui\screens\touch_registers_screen.cpp.o
Compiling .pio\build\MEGA\src\src\lcd\extui\lib\ftdi_eve_touch_ui\screens\tune_menu.cpp.o
Compiling .pio\build\MEGA\src\src\lcd\extui\lib\ftdi_eve_touch_ui\screens\widget_demo_screen.cpp.o
Compiling .pio\build\MEGA\src\src\lcd\extui\lib\ftdi_eve_touch_ui\screens\z_offset_screen.cpp.o
Compiling .pio\build\MEGA\src\src\lcd\extui\lib\ftdi_eve_touch_ui\theme\sounds.cpp.o
Compiling .pio\build\MEGA\src\src\lcd\extui\ui_api.cpp.o
Compiling .pio\build\MEGA\src\src\lcd\extui_dgus_lcd.cpp.o
Compiling .pio\build\MEGA\src\src\lcd\extui_example.cpp.o
Compiling .pio\build\MEGA\src\src\lcd\extui_malyan_lcd.cpp.o
Compiling .pio\build\MEGA\src\src\lcd\fontutils.cpp.o
Compiling .pio\build\MEGA\src\src\lcd\lcdprint.cpp.o
Compiling .pio\build\MEGA\src\src\lcd\marlinui.cpp.o
Compiling .pio\build\MEGA\src\src\lcd\ultralcd.cpp.o
Compiling .pio\build\MEGA\src\src\libs\buzzer.cpp.o
Compiling .pio\build\MEGA\src\src\libs\crc16.cpp.o
Compiling .pio\build\MEGA\src\src\libs\heatshrink\heatshrink_decoder.cpp.o
Compiling .pio\build\MEGA\src\src\libs\hex_print_routines.cpp.o
Compiling .pio\build\MEGA\src\src\libs\nozzle.cpp.o
Compiling .pio\build\MEGA\src\src\libs\numtostr.cpp.o
Compiling .pio\build\MEGA\src\src\libs\stopwatch.cpp.o
Compiling .pio\build\MEGA\src\src\libs\vector_3.cpp.o
Compiling .pio\build\MEGA\src\src\module\configuration_store.cpp.o
Compiling .pio\build\MEGA\src\src\module\delta.cpp.o
Compiling .pio\build\MEGA\src\src\module\endstops.cpp.o
Compiling .pio\build\MEGA\src\src\module\motion.cpp.o
Compiling .pio\build\MEGA\src\src\module\planner.cpp.o
Compiling .pio\build\MEGA\src\src\module\planner_bezier.cpp.o
Compiling .pio\build\MEGA\src\src\module\polargraph.cpp.o
Compiling .pio\build\MEGA\src\src\module\printcounter.cpp.o
Compiling .pio\build\MEGA\src\src\module\probe.cpp.o
Compiling .pio\build\MEGA\src\src\module\scara.cpp.o
Compiling .pio\build\MEGA\src\src\module\servo.cpp.o
Compiling .pio\build\MEGA\src\src\module\settings.cpp.o
In file included from Marlin\src\module\../lcd/anycubic_touchscreen.h:30:0,
                 from Marlin\src\module\configuration_store.cpp:54:
Marlin/./src/feature/bedlevel/abl/abl.h:43:0: warning: "_GET_MESH_X" redefined
 #define _GET_MESH_X(I) float(bilinear_start.x + (I) * bilinear_grid_spacing.x)

In file included from Marlin/./src/feature/bedlevel/bedlevel.h:69:0,
                 from Marlin\src\module\../lcd/anycubic_touchscreen.h:29,
                 from Marlin\src\module\configuration_store.cpp:54:
Marlin/./src/feature/bedlevel/mbl/mesh_bed_leveling.h:37:0: note: this is the location of the previous definition
 #define _GET_MESH_X(I) mbl.index_to_xpos[I]

In file included from Marlin\src\module\../lcd/anycubic_touchscreen.h:30:0,
                 from Marlin\src\module\configuration_store.cpp:54:
Marlin/./src/feature/bedlevel/abl/abl.h:44:0: warning: "_GET_MESH_Y" redefined
 #define _GET_MESH_Y(J) float(bilinear_start.y + (J) * bilinear_grid_spacing.y)

In file included from Marlin/./src/feature/bedlevel/bedlevel.h:69:0,
                 from Marlin\src\module\../lcd/anycubic_touchscreen.h:29,
                 from Marlin\src\module\configuration_store.cpp:54:
Marlin/./src/feature/bedlevel/mbl/mesh_bed_leveling.h:38:0: note: this is the location of the previous definition
 #define _GET_MESH_Y(J) mbl.index_to_ypos[J]

In file included from Marlin\src\module\../lcd/anycubic_touchscreen.h:30:0,
                 from Marlin\src\module\configuration_store.cpp:54:
Marlin/./src/feature/bedlevel/abl/abl.h:45:0: warning: "Z_VALUES_ARR" redefined
 #define Z_VALUES_ARR  z_values

In file included from Marlin/./src/feature/bedlevel/bedlevel.h:69:0,
                 from Marlin\src\module\../lcd/anycubic_touchscreen.h:29,
                 from Marlin\src\module\configuration_store.cpp:54:
Marlin/./src/feature/bedlevel/mbl/mesh_bed_leveling.h:39:0: note: this is the location of the previous definition
 #define Z_VALUES_ARR mbl.z_values

Compiling .pio\build\MEGA\src\src\module\stepper.cpp.o
Compiling .pio\build\MEGA\src\src\module\stepper\indirection.cpp.o
Compiling .pio\build\MEGA\src\src\module\stepper\trinamic.cpp.o
Compiling .pio\build\MEGA\src\src\module\temperature.cpp.o
Compiling .pio\build\MEGA\src\src\module\tool_change.cpp.o
Marlin\src\module\configuration_store.cpp: In static member function 'static void MarlinSettings::postprocess()':
Marlin\src\module\configuration_store.cpp:434:12: error: 'i' was not declared in this scope
   LOOP_XYZ(i) {
            ^
Marlin\src\module\configuration_store.cpp:434:3: error: 'LOOP_XYZ' was not declared in this scope
   LOOP_XYZ(i) {
   ^~~~~~~~
Marlin\src\module\configuration_store.cpp:434:3: note: suggested alternative: 'LOOP_L_N'
   LOOP_XYZ(i) {
   ^~~~~~~~
   LOOP_L_N
Marlin\src\module\configuration_store.cpp: In static member function 'static bool MarlinSettings::_load()':
Marlin\src\module\configuration_store.cpp:1428:38: error: 'i' was not declared in this scope
         if (!validating) LOOP_XYZE_N(i) {
                                      ^
Marlin\src\module\configuration_store.cpp:1428:26: error: 'LOOP_XYZE_N' was not declared in this scope
         if (!validating) LOOP_XYZE_N(i) {
                          ^~~~~~~~~~~
Marlin\src\module\configuration_store.cpp:1428:26: note: suggested alternative: 'LOOP_S_LE_N'
         if (!validating) LOOP_XYZE_N(i) {
                          ^~~~~~~~~~~
                          LOOP_S_LE_N
Marlin\src\module\configuration_store.cpp: In static member function 'static void MarlinSettings::reset()':
Marlin\src\module\configuration_store.cpp:2418:15: error: 'i' was not declared in this scope
   LOOP_XYZE_N(i) {
               ^
compilation terminated due to -fmax-errors=5.
*** [.pio\build\MEGA\src\src\module\configuration_store.cpp.o] Error 1
In file included from Marlin\src\module\../lcd/anycubic_touchscreen.h:30:0,
                 from Marlin\src\module\settings.cpp:52:
Marlin/./src/feature/bedlevel/abl/abl.h:43:0: warning: "_GET_MESH_X" redefined
 #define _GET_MESH_X(I) float(bilinear_start.x + (I) * bilinear_grid_spacing.x)

In file included from Marlin/./src/feature/bedlevel/bedlevel.h:69:0,
                 from Marlin\src\module\../lcd/anycubic_touchscreen.h:29,
                 from Marlin\src\module\settings.cpp:52:
Marlin/./src/feature/bedlevel/mbl/mesh_bed_leveling.h:37:0: note: this is the location of the previous definition
 #define _GET_MESH_X(I) mbl.index_to_xpos[I]

In file included from Marlin\src\module\../lcd/anycubic_touchscreen.h:30:0,
                 from Marlin\src\module\settings.cpp:52:
Marlin/./src/feature/bedlevel/abl/abl.h:44:0: warning: "_GET_MESH_Y" redefined
 #define _GET_MESH_Y(J) float(bilinear_start.y + (J) * bilinear_grid_spacing.y)

In file included from Marlin/./src/feature/bedlevel/bedlevel.h:69:0,
                 from Marlin\src\module\../lcd/anycubic_touchscreen.h:29,
                 from Marlin\src\module\settings.cpp:52:
Marlin/./src/feature/bedlevel/mbl/mesh_bed_leveling.h:38:0: note: this is the location of the previous definition
 #define _GET_MESH_Y(J) mbl.index_to_ypos[J]

In file included from Marlin\src\module\../lcd/anycubic_touchscreen.h:30:0,
                 from Marlin\src\module\settings.cpp:52:
Marlin/./src/feature/bedlevel/abl/abl.h:45:0: warning: "Z_VALUES_ARR" redefined
 #define Z_VALUES_ARR  z_values

In file included from Marlin/./src/feature/bedlevel/bedlevel.h:69:0,
                 from Marlin\src\module\../lcd/anycubic_touchscreen.h:29,
                 from Marlin\src\module\settings.cpp:52:
Marlin/./src/feature/bedlevel/mbl/mesh_bed_leveling.h:39:0: note: this is the location of the previous definition
 #define Z_VALUES_ARR mbl.z_values

================================================================ [FAILED] Took 22.08 seconds ================================================================

Environment    Status    Duration
-------------  --------  ------------
MEGA           FAILED    00:00:22.076
=========================================================== 1 failed, 0 succeeded in 00:00:22.076 =========================================================== 
The terminal process "C:\Users\DeepVansh\.platformio\penv\Scripts\platformio.exe 'run', '--environment', 'MEGA'" terminated with exit code: 1.
===============================================
Thank you in advance champ

**Comment by knutwurst** [comment]
Please open the i3_mega_envs.ini and add this to your configuration:
`build_unflags = -Werror=all`

So "-Werror=all" is also in the list of build_unflags.

**Comment by fully-sikh** [comment]
"i3_mega_envs.ini" is not available in the INI folder (latest pull from github), I added the  "-Werror=all" into couple of environments (MEGA. MEGA_P_DGUS, MEGA_P_DGUS_BLT10) within file "i3_mega.ini" in the INI folder.

The build succeeded for all three environments.

Thank you for resolving the issue.
