### ISSUE TITLE
[FR] M115 to show full Marlin version number

### ISSUE THREAD

**Issue by MrBill1234** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#296]
### Description

M115 to show full Marlin version number

### Feature Workflow

M115 command shows this:

Send: M115
Recv: FIRMWARE_NAME:Marlin 2.0.x (knutwurst, Github) (Feb 18 2022 13:26:03) SOURCE_CODE_URL:github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S PROTOCOL_VERSION:1.0 MACHINE_TYPE:Knutwurst's Anycubic Printer EXTRUDER_COUNT:1 UUID:b6153152-86fb-4cd8-bda7-91c6a04c467d

Some software (such as Arcwelder plugin on Octoprint) has the option to check if your firmware is compatible.  At the moment it picks up:

Version:
2.0.x

Which is taken from the M115 output.

I believe we're on 2.0.9.2?  If so - could the full version be hardcoded into each new build so that any software which queries it will know exactly what version of firmware they are talking to. 

#### Additional Information

None

**Comment by Kevinrob** [comment]
@MrBill1234 I made a PR for this one https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/pull/298
