### ISSUE TITLE
Layer shift on Mega X with 1.1.7-beta.1

### ISSUE THREAD

**Issue by shaddowlink** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#30]
I recently updated to 1.1.7-beta.1, loaded FW-defaults and saved. I got horrible layer shifts in the Y-axis at unregular intervals (approx. every 3-20 layers), with random amount of shift. Also always at different positions with the same model. (X and Z axis are totally fine)

here is a pic:
![layer shift (1)](https://user-images.githubusercontent.com/4293045/96036163-5fb2bd80-0e64-11eb-8768-6a226e6e1091.jpg)
another model:
![layer shift (2)](https://user-images.githubusercontent.com/4293045/96036167-604b5400-0e64-11eb-8642-8e96dd69918d.jpg)

In the release notes I saw that this version is supposed to fix this issue, but for me it causes it. 

A downgrade to 1.1.6, loading Fw-defaults fixed this for me and my printer is running again like it is supposed to. 
tried several print settings and models before figuring it out. 

I have TMC2209 installed.

**Comment by knutwurst** [comment]
Wow! That's crazy! I haven't seen a Mega X with layer shifts yet. Funny that it occurs with the 1.1.7 for you and not with 1.1.6. There will be a Beta 2 over the weekend. Maybe you would like to try this version as well? I'd be pleased :)

Thank you very much!

**Comment by shaddowlink** [comment]
I only print via SD card for now. Plan to update with Octoprint over usb at some point.

Ofc I will try the new beta then.

Is there an option to collect debugging data that would be useful for you?

**Comment by Sydney1101** [comment]
I have no problems with the beta 1 version on my Mega X with TMC and Octoprint. It coud be a acceleration problem... What are the values for M201 and M204? Which slicer do you use?

**Comment by knutwurst** [comment]
Beta 2 is out now. ;) 

Please open a new Issue if the problem persists and link to this one.
