### ISSUE TITLE
Erweiterung der Lasergravurfläche beim Anycubic Mega Pro[FR] (feature request title)

### ISSUE THREAD

**Issue by Patzomat** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#306]
Hallo Knutwurst,

die Lasergravurfläche ist beim Mega Pro in der Y-Achse ja auf 140mm beschränkt anstatt orginal 210mm.
Gibt es eine Möglichkeit diese Beschränkung in der originalen Firmeware aufzuheben?

Beste Grüße
Patzomat

**Comment by oooBuGooo** [comment]
In der original Firmware kannst du es leider nicht umstellen.
Mit Knutwurst und Lightburn kannst du die komplette Fläche vom Druckbett nutzen.

**Comment by Patzomat** [comment]
Kann man dann auch Bilder bmps Lasern.
Ich hatte da was gelesen, dass man dann nur die Bewegung das Lasers und die Intensität per gcode steuern kann?!

**Comment by oooBuGooo** [comment]
Ja man kann auch Bilder gravieren doch gibt es da momentan noch eine kleine Einschränkung.
Der Laser verringert kurz die Geschwindigkeit wenn er den Laser an und ausschaltet.
Dadurch dauert das gravieren sehr lange.
Ausschneiden funktioniert aber super.

**Comment by Patzomat** [comment]
Ok dann muss ich mir das nochmal anschauen.
Danke!

**Comment by oooBuGooo** [comment]
Sehr gerne

**Comment by oooBuGooo** [comment]
@Patzomat Es währe super wenn du den Chat schließt wenn dein Problem gelöst ist. :-)
