### ISSUE TITLE
Homing mit 2mm Abstand ;   Homing with 2mm distance

### ISSUE THREAD

**Issue by oooBuGooo** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#309]
Beim Homing Fährt der Druckkopf gegen die endschalter und fährt dann ca. 2mm von diesem weg.
Dadurch wird der druckraum etwas kleiner, Kann man das anpassen?

When homing, the print head moves against the limit switches and then moves about 2mm away from it.
This makes the pressure room a little smaller, Can you adjust that?

**Comment by knutwurst** [comment]
Of course:
Configuration_adv.h -> HOMING_BACKOFF_POST_MM
