### ISSUE TITLE
Bei Achsbewegung werden die Endschalter ignoriert [BUG] (short description)

### ISSUE THREAD

**Issue by DerTrollo** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#312]
### Bug Description

Anycubic I3 Mega 
Ist man im Move Axis, werden außer beim Homing, die Endschalter ignoriert. 

### Steps to Reproduce

1. Druckkopf über Home in die Endpositionen fahren lassen.
2. z.B. Druckkopf um 10mm anheben und wieder um 1mm senken.
3. Druckkopf jetzt wieder 10mm absenken.

**Expected behavior:** 
Der Druckkopf sollte sich jetzt nur um 9mm senken, da er vom Endschalter gestoppt wird.
Er fährt jedoch die vollen 10mm und drückt die Nozzle ins Druckbett und verbiegt im schlimmsten Fall die Führungen.

Selbiges passiert auch bei der X und Y Achse.

#### Additional Information

Ich hatte zuvor eine Marlinversion 2.0.6.1 auf dem Drucker gehabt. 
Diese war auf Thingeverse beim MK4-Projekt dabei. 
https://www.thingiverse.com/thing:3537449
Dort gab es das Problem nicht.

Liebe Grüße,
Der Trollo

**Comment by H132022** [comment]
Hello, in my case I can say that in two mega S with a dark screen and the firmware MEGA_S_DGUS_v1.4.3.hex, when moving the axes from the printer menu, pronterface, octoprint, when it reaches the final switch it ignores them and hits the engine, I have tried previous versions and it also happens.
