### ISSUE TITLE
extruder heater anycubic i3 mega

### ISSUE THREAD

**Issue by rafurius** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#317]
it seems that the pid tune is not saved

1. configure the pid (autotune hotend)
2. the tune pid of the hotend is not saved or improved

**Comment by Dogfroster** [comment]
Works normal for me. What does the console say, is it going through or breaks it?
Otherwise try manually.
M106 S190
M303 E0 S210 C15 U1
When it runs Save with M500
M106 S0
