### ISSUE TITLE
[FR] M808

### ISSUE THREAD

**Issue by GITdan80** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#325]
### Description

Bitte M808 Repeat-Funktion hinzufügen

### Feature Workflow

Laut Marlin Wiki ist in Marlin 2.0.8 die Repeat-Funktion M808 enthalten.
Zum Einlaufen von neuen Achsen oder um zu testen, ob die Motoren oder Stepper Treiber ein Temperaturproblem haben, wäre diese Funktion sehr nützlich, da man sehr einfach endlose Fahrweg-Schleifen programmieren könnte.

**Comment by stklcode** [comment]
Ist laut Konfiguration nicht ausgeschlossen. Funktioniert der Befehl nicht?

https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/blob/e3a2aeb4cf9498f51d2fc71d9f8c0d3bf92104c5/platformio.ini#L282

**Comment by GITdan80** [comment]
Hallo,

Ja, ich habs mehrfach ausprobiert und M808 wird jedes Mal ignoriert.
Das Flashen deiner Firmware hat aber auf jeden Fall funktioniert. Danach lade ich auch immer die Firmware  defaults,  speichere und starte den Drucker neu.
Wenn ich eine Schleife mit 100 Wiederholungen schreibe, fährt der Drucker nur 1x hin und her und bleibt anschließend stehen.

LG, Daniel

Am 8. Mai 2022 22:23:08 MESZ schrieb Stefan Kalscheuer ***@***.***>:
