### ISSUE TITLE
i3-MEGA-S Button Filament In

### ISSUE THREAD

**Issue by WeberKay** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#333]
Hi,

erstmal vielen Dank für diese tolle Firmware und Doku dazu. Jedoch habe ich ein Problem:

- wenn ich den Button Filament In am Display drücke, ist die eingestellte Geschwindigkeit für den Extruder viel zu hoch, wo kann ich diese im Quellcode ändern? 

Vielen Dank.

Gruß

**Comment by knutwurst** [comment]
https://marlinfw.org/docs/gcode/M203.html

**Comment by WeberKay** [comment]
Danke
