### ISSUE TITLE
WLAN nachrüsten ohne löten ...

### ISSUE THREAD

**Issue by RasputinBerry** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#339]
Hallo zusammen,

unter der gesteckten Platine (für SD Karte u.ä.) sind die Kontakte Tx, Rx, Vcc und GND als PIN herausgeführt.
Um den aufwendige Board Ausbau zu umgehen habe ich ein paar Steckkonakte "gebastelt". 
Dabei habe ich versehentlich den Stecker D42 (Bezeichnung an der Platine an der Gehäuse Schnittstelle) gezogen und kann nun nicht mehr nachvollziehen wohin damit ...

[Steckerproblem.pdf](https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/files/8870027/Steckerproblem.pdf)

Ich habe einige Bilder des TriGorilla V0.0.2 gefunden, aber der für mich interessante Bereich ist immer irgendwie verdeckt.

Danke für die Lösung in Wort oder besser als Bild ...

_(Bitte nicht steinigen weil das hier nicht wirklich ein "Feature request" ist, sondern ein "Verbesserungsvorschlag"  ... ansonsten pure Verzweiflung ...)_

**Comment by knutwurst** [comment]
Ich glaube das einfachste ist das hier: 
[TriGoRiLLa_PINs.pdf](https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/files/8870231/TriGoRiLLa_PINs.pdf)


D42 ist der Y Endstop. Das ist aber nicht derselbe auf dem Foto rechts. Der müsste eigentlich direkt hinten zum Schalter für das Heizbett gehen. Und er gehört links auf den AUX Header.
