### ISSUE TITLE
How to relocate runout sensor and enable it?

### ISSUE THREAD

**Issue by EasyG0ing1** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#347]
This isn't a bug report or a feature request. I just have a question.

If I want to move my filament run-out sensor away from the TFT in my Mega X, how do I go about finding an available port on the main board, and how do I enable the runout sensor so that Marlin sends the notification to OctoPrint via the Host Action Commands?

I've got a BL Touch installed so I can't use that available port ... 

Thank you,

Mike

**Comment by knutwurst** [comment]
Hi @EasyG0ing1 ,
please see #19. 

I'm sorry
