### ISSUE TITLE
Druckzeit "PopUp"-Meldung

### ISSUE THREAD

**Issue by Beo666** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#35]
v1.1.6 mit compiliter Hex: Die verbrauchte Druckzeit am Ende des Druckes ("PopUp-Meldung") wird nicht korrekt angezeigt, d.h. die Druckzeit auf dem Display ist komplett anders wie auf der PopUp-Meldung.

**Comment by knutwurst** [comment]
Darauf hab ich tatsächlich noch nie geachtet.. ich schaue mir das mal an. Danke!

**Comment by Beo666** [comment]
Super, vielen Dank. Wenn du Fragen hast oder weitere Infos brauchst, meld dich.
