### ISSUE TITLE
Is there a newer BLTouch wiring diagram for the Mega X V0.0.2  TriGorilla board?

### ISSUE THREAD

**Issue by Ri-Pete** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#352]
I bought a Mega X just recently and it has the TriGorilla board V0.0.2  without the logo and I was wondering if there are any differences I need to be aware of.
I purchased a BLTouch V3.1 and would like to install it. But before I do, I wanted to _**not**_ make any mistakes that I could avoid.
Also, does anyone know if the hot board is the same or has it also been upgraded?
![TriGorilla_V0 0 2-A](https://user-images.githubusercontent.com/74444972/182431493-7ceb385f-8434-456b-8d08-3905462efb20.jpg)

**Comment by knutwurst** [comment]
The Trigorilla 0.0.2 doesn't have a logo. Please see https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/wiki/Beginner's-Guide-(English)#trigorilla-002 .

**Comment by Ri-Pete** [comment]
OK, Thanks.
