### ISSUE TITLE
4MAX Pro v2 - Power Off am Druckende?

### ISSUE THREAD

**Issue by anjoku** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#359]
Hallo, 
hoffentlich bin ich hier nicht komplett falsch mit meiner Frage.......ich habe den 4MAX Pro v2 und würde gerne Deine Firmware einsetzen.
Leider habe ich keine Informationen gefunden, ob Deine Version auch das Power Off am Druckende unterstützt.

Beste Grüße

André

**Comment by knutwurst** [comment]
Zugegeben: Es ist schwer zu finden und in der Feature-Liste sogar undokumentiert. Aber seit der 1.4.0 gibt's das: https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/commit/0fae7ebb09c9f0cf6090898845b9509393b1e1a3

Ich hoffe, das hilft dir :)

**Comment by anjoku** [comment]
Oh danke. Das hilf mir sehr.

Dann werde ich mich dranmachen.
Danke :-)
