### ISSUE TITLE
[FR] Proper setting of Z-Offset 

### ISSUE THREAD

**Issue by yani66** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#361]
**Description**
"Only" a easier way to set the Z-Offset.

**Workflow**
1. You select "Z-Offset" it in the Special Menu. 
2. The printhead homes and get's on the Z-Offset level.
3. Now if you adjust the Z-Offset setting the printhead moves with it.
4. Check with a peace of paper if it's the right hight.
5. Press "Save and Exit"

**Comment by knutwurst** [comment]
Unfortunately, this is not possible due to the limitations of the display firmware. What you are looking for is the live offset, which can only be set when printing. Unfortunately, this only works via USB, otherwise the display is blocked.
