### ISSUE TITLE
[BUG] z2_min dauerhaft betätigt

### ISSUE THREAD

**Issue by iinovis** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#362]
### Bug Description

Hallo,
habe bei meinem Anycubic Mega Pro BLTouch nachgerüstet und die restlichen drei Treiber durch TMC2208 ersetzt. Danach habe ich die Firmware MEGA_P_DGUS_TMC_BLT_10_v1.4.4.hex installiert. Seitdem wird im Pronterface mit dem Befehl M119 der z2_min immer als "triggered" gemeldet (egal, ob ich den Schalter abziehe oder stecke, es ändert nichts). Beim Autolevel fährt die linke z-Achse nicht herunter (da der z2_min ja betätigt ist). 
Kannst Du mir helfen?

### Steps to Reproduce

1. BLTouch nachgerüstet (nach Wiki)
2. Treiber durch TMC2208 ersetzt
3. Firmware MEGA_P_DGUS_TMC_BLT_10_v1.4.4.hex installiert
4. Load Defaults
5. Write EEPROM
6. Autolevel

**Expected behavior:**
z2_min sollte sich wie z_min verhalten

**Actual behavior:**
z2_min hängt betätigt

Vielen Dank und viele Grüße,
Sebastian

**Comment by SjoerdNLD** [comment]
I had the same, one connector was wrong. see here: https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/issues/363
