### ISSUE TITLE
[FR] PT100 thermistor support

### ISSUE THREAD

**Issue by JernejL** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#372]
E3d V6 hotends that are a good upgrade for anycubic printers usually come with PT100 thermistor, can this be also supported in knutwurst firmware?

**Comment by knutwurst** [comment]
This firmware is based on Marlin, so yes. It's supported :)

**Comment by JernejL** [comment]
So, how would it be set? i thought a special build has to be made?

**Comment by knutwurst** [comment]
You need to build the firmware by yourself. Take a look at the Wiki pages. Everything you need is described here.
