### ISSUE TITLE
Bltouch funktioniert nicht

### ISSUE THREAD

**Issue by Creatorsmotion** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#377]
Ich habe Bltouch Korrekt angeschlossen am meinem Mega Pro und beim Leveln bleibt er beim ersten Punkt stehen und der Bltouch fährt aus und ein aber die Z achse Macht nichts

1. Special Menü
2. Auto Leveling 
3. Start

Pronterface:  Bed Leveling OFF
                      Fade Height OFF
Failed  to enable Bed Leveling 
Probing failed 

Habe Offset eingestellt und richtig verkabelt.
FehlerVideo:
https://photos.app.goo.gl/fMWtgxqWKynb8uor5

**Comment by hraphael** [comment]
Ich hatte das gleiche Problem, in der Anleitung steht, dass man A5 und B5 am grünen Stecker vertauschen MUSS, nachdem ich das gemacht habe hat es auf Anhieb funktioniert. 
https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/wiki/BLTouch-Installation-(deutsch)#mega-pro-verdrahtung
