### ISSUE TITLE
Are ARCs enabled? | Sind die ARC Funktionen in der Firmware aktiv?

### ISSUE THREAD

**Issue by DunklerPhoenix** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#38]
Heho,
Ich versuche gerade das OctoPrint ArcWelder Plugin zum laufen zu bringen. Sind in der Firmware die ARC Funktionen aktiv?

I'm currently trying to get the OctoPrint ArcWelder plugin to work. Are the ARC functions active in the firmware?

REF: https://github.com/FormerLurker/ArcWelderPlugin/issues/64

**Comment by DunklerPhoenix** [comment]
Ah nevermind... 

```
//
// G2/G3 Arc Support
//
#define ARC_SUPPORT                 // Disable this feature to save ~3226 bytes
#if ENABLED(ARC_SUPPORT)
  #define MM_PER_ARC_SEGMENT      0 // (mm) Length (or minimum length) of each arc segment (default: 1)
  //#define ARC_SEGMENTS_PER_R    1 // Max segment length, MM_PER = Min
  #define MIN_ARC_SEGMENTS        0 // Minimum number of segments in a complete circle (default: 24)
  //#define ARC_SEGMENTS_PER_SEC 50 // Use feedrate to choose segment length (with MM_PER_ARC_SEGMENT as the minimum)
  //#define N_ARC_CORRECTION       25 // Number of interpolated segments between corrections
  #define ARC_P_CIRCLES             // Enable the 'P' parameter to specify complete circles
  #define CNC_WORKSPACE_PLANES      // Allow G2/G3 to operate in XY, ZX, or YZ planes
#endif
```

**Comment by FormerLurker** [comment]
Not sure what will happen with a mm per arc segment of 0..  Ich habe keine Annung :). Bitte schreib mir an, ob es lauft oder nicht.

**Comment by DunklerPhoenix** [comment]
Hmm... 
@knutwurst Did you change the setting MM_PER_ARC_SEGMENT to zero?

**Comment by knutwurst** [comment]
Hi :) 
Yes, ARC Support is enabled and I changed the minimum for each segment to 0 because Someone who wanted to use a Laser ran into issues when printing small circles. This way it works because everything can be set up by the software.

Did you try it?

**Comment by DunklerPhoenix** [comment]
Yes I tried it with the Octoprint addon ArcWelder https://github.com/FormerLurker/ArcWelderPlugin/issues/64

but somehow it generates garbage. but i think it has nothing to do with the firmware. idk.
maybe my pi is trashy

**Comment by DunklerPhoenix** [comment]
@knutwurst Are you sure with the enabled Arc Support?
I get "Unknown command: G2"
![2sVt0WBcG5](https://user-images.githubusercontent.com/1261305/100140116-cb8b3b80-2e90-11eb-8fd1-26390d6a0391.png)

`FIRMWARE_NAME:Marlin 2.0.5.4 (knutwurst, Github) KNUTWURST_AI3M_VERSION:1.1.6 DISTRIBUTION_DATE:2020-09-11 SOURCE_CODE_URL:https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S PROTOCOL_VERSION:1.0 MACHINE_TYPE:Knutwurst's Anycubic i3 MEGA EXTRUDER_COUNT:1 `

**Comment by FormerLurker** [comment]
I do recommend that 2.0.6 is merged in.  Then you can change the default arc settings to this:

```
#if ENABLED(ARC_SUPPORT)
  #define MM_PER_ARC_SEGMENT      1 // (mm) Length (or minimum length) of each arc segment (default: 1)
  //#define ARC_SEGMENTS_PER_R    1 // Max segment length, MM_PER = Min
  #define MIN_ARC_SEGMENTS        24 // Minimum number of segments in a complete circle (default: 24)
  //#define ARC_SEGMENTS_PER_SEC 50 // Use feedrate to choose segment length (with MM_PER_ARC_SEGMENT as the minimum)
  #define N_ARC_CORRECTION       25 // Number of interpolated segments between corrections
  #define ARC_P_CIRCLES             // Enable the 'P' parameter to specify complete circles
  //#define CNC_WORKSPACE_PLANES      // Allow G2/G3 to operate in XY, ZX, or YZ planes
#endif
```

That should produce really nice arcs.  CNC_WORKSPACE_PLANES  probably don't need to be enabled for this build at all.    Also, a typical printer won't use P, but a laser engraver strapped to a printer just might :) I left that enabled.

**Comment by FormerLurker** [comment]
Also, @DunklerPhoenix, perhaps you downloaded and built this firmware before arcs were enabled?  Maybe they weren't always?  Also, perhaps marlin responds to a naked G2 in V<2.0.6 differently (Thinkyhead was the one who explained how to do this, but maybe he meant only in the new version).  The fact that M115 doesn't report CAP:Arcs:1 does suggest it is not enabled, but I don't know that for a fact.  The firmware checker is a brand new feature.

**Comment by CTRoulston** [comment]
Appears to no longer be active. 
Was working in a previous release. G2/G3 returns disconnects Octopi due to "unknown command", M115 doesn't report it and arcs are printed as straight lines.

**Comment by knutwurst** [comment]
@DunklerPhoenix , as far as I can see, you youse 1.1.6, in which ARC Support is not enabled. 

Please let me know if [1.1.7 Beta 2](https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/releases/tag/1.1.7-beta.2) or [1.1.7 release](https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/releases/tag/1.1.7) works for you.

Please also try both versions, since they handle G2/G3 differently.

Thanks in advance!

@CTRoulston which version did you use?

**Comment by DunklerPhoenix** [comment]
I tried version 1.1.7R yesterday and here are the images.
https://github.com/FormerLurker/ArcWelderPlugin/issues/64#issuecomment-735998625

FormerLurker is doing a check atm if its the firmware or the gcode.

**Comment by CTRoulston** [comment]
Beta 3 did not work through arc-welder. I believe 1.1.6 was working.
Sorry looking through which versions I have in my downloads folder.

**Comment by CTRoulston** [comment]
Also thank you so much everyone who has worked both on Marlin and the Mega-X branch :) Amazing to have all these great features available

**Comment by CTRoulston** [comment]
Just remembered possibly the biggest difference (other than versions numbers), arc welder/arcs were working with TMC branch, noticing issues on TMC + BLTouch branch.

**Comment by FormerLurker** [comment]
I don't see a TMC+BLTouch branch.  Was going to look and see if arcs were disabled to save space for the extra features, but don't know where to look.

**Comment by CTRoulston** [comment]
MEGA_X_TMC_BLT_10_v1.1.7.hex

**Comment by CTRoulston** [comment]
Previous working version (working as in arc-reactor worked, I never checked for G2/G3 as it was working as expected) was MEGA_X_TMC_v1.1.6.hex

**Comment by FormerLurker** [comment]
Well crap.  I don't feel like disassembling the bin, lol.  @DunklerPhoenix's firmware check strongly suggested arcs were enabled.  I did see a mm_per_arc_segment setting of 0 being discussed.  Can't say I can see how that would work though.

**Comment by CTRoulston** [comment]
@FormerLurker All good, thanks for your help. At the moment have other issues I'm addressing (signal cable came off heated bed :/) , running without arcs, fingers crossed fixed in next revision.

**Comment by DunklerPhoenix** [comment]
I'm compiling the firmware MEGA_X_BLT_11 with MM_PER_ARC_SEGMENT 1 at the moment.
Will give feedback later if it works with arcwelder.

**Comment by DunklerPhoenix** [comment]
Can confirm. MM_PER_ARC_SEGMENT 0 breaks the arc function. The first layer looks much better with 1.
I'll post the images tomorrow. need to sleep since 3h xD

**Comment by DunklerPhoenix** [comment]
Left -> Right
No Arcs (normal gcode), Arc 0mm, Arc 1mm

![PXL_20201206_080711350](https://user-images.githubusercontent.com/1261305/101274981-9e992b80-37a2-11eb-9433-4f33b5939b71.jpg)
![PXL_20201206_080656975](https://user-images.githubusercontent.com/1261305/101274982-9fca5880-37a2-11eb-9765-a1867336f2f0.jpg)

**Comment by knutwurst** [comment]
Wow! Okay... I'll reenable the function in the next release. Thank you for your help! I leave the issue open until it's fixed.

**Comment by knutwurst** [comment]
Fixed in this commit https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/commit/08a1ceed8abaf5f357595c5d2f34c90b74dc8897 and will be available in the next release.
