### ISSUE TITLE
[FR] Unsure about Z-offset

### ISSUE THREAD

**Issue by chevroux** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#381]
Sorry for not posting in the facebook group, but I don't have facebook.

I installed bltouch successfully and calculated the Z offset and set it with gcode.

Do I have to set the calculated offset in the on screen menu of the printer as well? Or is that offset added/subtracted from the offset set by gcode?

Maybe this could be made clearer in the installation instructions =)

Thanks!

**Comment by knutwurst** [comment]
Hi,
the offset-menu was introduced a long time after I wrote the installation instructions, but thanks for the hint :) 

The displayed offset is the current offset which is also set by the gcode. But it might not be refreshed if the printer is powered on and the offset changed via usb while displaying it. If you close the menu (via exit), change the offset by gcode and then re-open the menu, it should display the correct current offset.

**Comment by chevroux** [comment]
Ah, I see! Thanks a lot for the quick answer!
