### ISSUE TITLE
Anycubib I3 mega no way to disable runout sensor

### ISSUE THREAD

**Issue by effeerre75** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#385]
Form the "Special-menu" I choose the "disable fil. sensor" option, I hear the jingle and then save the EPROM settings.
When I come back to the main menu, at the bottom right always appear the error message "lack of filament"
Try with and without sensor connected. 
Triend alos to disable with M412 command via serial interface but it report that the command is unknown.
For now the only workaround I've found is to disconnect the sensor and short the two pin with a pice of wire.

Firmware is Marlin-2-0-x-Anycubic-i3-MEGA-S-master downloaded from this repo.

**Comment by HaGueRe** [comment]
Why not placing a little piece of filament into the sensor? You will never see this message again.

**Comment by effeerre75** [comment]
Because sensor operation is no longer reliable.

**Comment by Mauker1** [comment]
I'm experiencing the same issue. My sensor is no longer working as expected. Disabling it would be ideal. But I get the same problem as OP.

**Comment by Alkerion** [comment]
Easy solution : Just remove the sensor and cable, and put a jumper where the cable is connected.

**Comment by Mauker1** [comment]
Yeah, that's pretty much what I ended up doing.

**Comment by effeerre75** [comment]
hardware solution to fix a software problem… that’s pure microsoft way! 😃

**Comment by aurarius1** [comment]
Maybe a dumb question but where do I need to put to jumper on the mainboard/hub?  As I connected my runout sensor to my raspberry pi running octoprint and the disable option is not working for me as well 😅

**Comment by effeerre75** [comment]
I’ve just disconnected the cable from the sensor and put a bent there! 😃 

![59C45ACC-AFF4-4F9A-B7FC-0F9CFE3F4591](https://user-images.githubusercontent.com/16226520/206852098-b3e49c81-4529-45f6-a1e8-c447da07534c.jpeg)

**Comment by aurarius1** [comment]
Thanks, I'll do that then! 😃

**Comment by Alkerion** [comment]
You can also do that, no more cable, clean.

![2022-12-10_16-34-12](https://user-images.githubusercontent.com/34811376/206862888-14e7ea2e-5205-4001-b262-8215846ac957.jpg)

**Comment by aurarius1** [comment]
But then I'd need to replace the the connector as the remaining four cables need to be connected right?

**Comment by Alkerion** [comment]
> But then I'd need to replace the the connector as the remaining four cables need to be connected right?

You're right, my mistake, I've tweaked this printed a lot that I don't even remember what was connected here...
