### ISSUE TITLE
[BUG] Crash when exiting z offset menu if bed was never leveled before.

### ISSUE THREAD

**Issue by JernejL** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#386]
### Bug Description

Pretty much as title, if you do a fresh install and enter bltouch menu and do anything without having a valid bed leveling mesh, exitting it crashes. 
 
### Steps to Reproduce

1. Load FW defaults
2. Enter z offset menu
3. Exit z offset menu
4. Crash.

**Expected behavior:** No crash

**Actual behavior:** Crashes in a way that it does not reset heaters.

**Comment by JernejL** [comment]
This is still legit bug, not stale.

**Comment by knutwurst** [comment]
I'm on it :)
