### ISSUE TITLE
Reduce Filament In speed

### ISSUE THREAD

**Issue by Alkerion** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#395]
### Description

Is there a way to reduce the "Filament In" speed and temp (from TFT menu) ?

### Feature Workflow

On the TFT screen :

1. Press Tools
2. Press Filament
3. Press Filament in
4. Printer heat nozzle to 230°C
5. Then we can ask the extruder to insert the filament

The extruder is too fast and that create problems (damaging filament and creating dust in extruder)

The low temp at which the extruder allow filament in is also too low.

#### Additional Information

* Provide pictures or links that demonstrate a similar feature or concept.

**Comment by knutwurst** [comment]
I'll take a look :)
