### ISSUE TITLE
Access to facebook group blocked

### ISSUE THREAD

**Issue by Gregmaan** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#40]
Hi,
Why do I get blocked twice trying to get access to the facebook group?
2. attempt created a new real name account. Blocked again. Why?

**Comment by knutwurst** [comment]
Hi @Gregmaan,
I'm so sorry, but maybe your request was blocked because your profile did not contain any private information, so we assumed a fake/scam profile. I'm really sorry. Could you please try again? I unblocked your Account.
