### ISSUE TITLE
[BUG] Bad Code for Wi-Fi in firmware

### ISSUE THREAD

**Issue by wes1993** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#406]
### Bug Description

The code related to the SERIAL_PORT_2 is different from the wiki, is normal?

### Steps to Reproduce

Check the code

**Expected behavior:** 
Should be:

#define SERIAL_PORT_2 2
#define BAUDRATE_2 500000   // :[2400, 9600, 19200, 38400, 57600, 115200, 250000, 500000, 1000000] Enable to override BAUDRATE

**Actual behavior:**
Now is:
#define SERIAL_PORT_2 -1
#define BAUDRATE_2 250000   // :[2400, 9600, 19200, 38400, 57600, 115200, 250000, 500000, 1000000] Enable to override BAUDRATE

#### Additional Information

None....

**Comment by knutwurst** [comment]
@wes1993
You are absolutely right. Some changes made when updating to the Marlin upstream version have overwritten these values.
