### ISSUE TITLE
[BUG] Babystepping is tied to BLTOUCH

### ISSUE THREAD

**Issue by benspawn** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#41]
Babystepping is disabled due to it being tied to BLTOUCH configuration. 
If BLTOUCH is enabled, only then you can have BABYSTEPPING.
Cannot send M290 command via Pronterface with this current firmware configuration.

**Comment by knutwurst** [comment]
Fixed in this commit https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/commit/08a1ceed8abaf5f357595c5d2f34c90b74dc8897 and will be available in the next release.
