### ISSUE TITLE
[Question] OctoPrint M117 support possible?

### ISSUE THREAD

**Issue by F3000** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#410]
I have issues to display e.g. the layer height from a print started with OctoPrint on the display. 

Is this a bug ?

**Comment by stklcode** [comment]
> OctoPrint M117 support possible?

Not without an additional display. The _Anycubic_ displays have a fixed feature set, so AFAIK is is not possible to send arbitrary messages to it.

> I have issues to display e.g. the layer height from a print started with OctoPrint on the display.

Could you give some further description on this?
What is (not) displayed and where? Which printer? Which Marlin/Knutwurst Firmware?
And how do you think, M117 could resolve the issue?
