### ISSUE TITLE
BL Touch auto leveling error

### ISSUE THREAD

**Issue by DieserDada** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#412]
### Bug Description

3D Touch Sensor wie im Anhang angeschlossen

( https://www.youtube.com/watch?v=b8yWIWXus1U&t=548s&ab_channel=OsLee540i )

![Verkabelung Mainboard](https://user-images.githubusercontent.com/109029437/209691072-0ebb7e48-a59a-4118-ab6c-c90ffabc0946.png)

MEGA_TMC_BLT_10_v1.4.4 installiert. (Normaler I3 Mega mit TMC 2208 Treibern)

Load FW Defaults und save to EEPROM

M851 Offset eingestellt

Beim Auto leveln fährt der Drucker auf 0 und dann über den ersten Messpunkt. Mein Sensor fährt drei mal aus und ein und das wars (siehe Video im Anhang)

**Expected behavior:** 

Drucker fährt Bilinear 5x5 über die Platte und levelt sich

**Actual behavior:**

Drucker bleibt über dem ersten Punkt stehen und fährt die Messspitze nur drei mal ein und aus.
https://user-images.githubusercontent.com/109029437/209691646-626ae5a8-04a9-4e11-97b3-1ab320751b64.mp4

**Comment by c-poxi** [comment]
Hallo Dada.

Wennst den bltouch am pin 21 angeschlossen hast dann musst du das in der Firmware ändern.
https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/wiki/Howto:-Firmware-mit-PlatformIO-selbst-kompilieren

Oder du hältst dich an die bltouch Anleitung.
