### ISSUE TITLE
[FR] Documentation enhancement

### ISSUE THREAD

**Issue by github-pba** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#415]
The summary located at https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/wiki/Beginner's-Guide-(Deutsch)#24-zusammenfassung describes which firmware needs to be selected for a given display.

A similar summary should be given for the next chapter describing the main board. Four types of boards are explained, but there is no clear text description which firmware to use for which board.

For example, I would _guess_ for Trigorilla 1.0 boards, I have to use the _10 firmware, and for Trigorilla 1.1 I need _11 firmware. But I have the Trigorilla 0.0.2 board in my Anycubic Mega X from bought in Sept. 2022, so I actually do not know which firmware to use.

Thank you for enhancing the docs.

**Comment by The-Man-Is-Me** [comment]
The only reason you need to specify which board you have is if you are using a bl touch. If you are and have the 0.0.2 board you should use the 1.0 because they have the same port assignments, but I can see how that could be confusing.
