### ISSUE TITLE
M190 / M109 wait for cooling

### ISSUE THREAD

**Issue by anno0** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#418]
### Bug Description

This is a part of my start G-Code. From a print before the bed was heated for more than 60 degrees, maybe 80 degrees. In the current print I want to heat the bed "up to" 60 degrees. So in this case M190 has to wait until 60 degrees are reached. Here the print already started with a bed temperature of 68 degrees. In my opinion M190 doesn't wait during this cooling process.

G21                                        ; metric values
G90                                        ; absolute positioning
M82                                        ; set extruder to absolute mode
M107                                       ; start with the fan off
M140 S{material_bed_temperature_layer_0}   ; Start heating the bed
M190 S{material_bed_temperature_layer_0}   ; wait for bed
G4 S30                                     ; wait 30 seconds
M104 S{material_print_temperature_layer_0} ; start heating the hot end
M109 S{material_print_temperature_layer_0} ; wait for hotend
M300 S1000 P500                            ; BEEP heating done

### Steps to Reproduce

1. Heat bed for 80 degrees.
2. Start print with target bed temperature of 60 degrees.
3. **G-Code M109 shows the same behavior** 

**Expected behavior:** It should wait until the target temperature is reached.

**Actual behavior:** It doesn't wait.

**Comment by stklcode** [comment]
According to the documentation, you can set the target temperature with `R` instead of `S` to wait for cooling, too.

https://marlinfw.org/docs/gcode/M109.html:
> **Description**
> This command optionally sets a new target hot end temperature and waits for the target temperature to be reached before proceeding. If the temperature is set with S then [M109](https://marlinfw.org/docs/gcode/M109.html) waits _only when heating_. If the temperature is set with `R` then [M109](https://marlinfw.org/docs/gcode/M109.html) will also wait for the temperature to go down.
>
> **Usage:**
> `M109 [B<temp>] [F<flag>] [I<index>] [R<temp>] [S<temp>] [T<index>]`
> 
> Parameters
> * `[R<temp>]` - Target temperature (wait for cooling or heating).
> * `[S<temp>]` - Target temperature (wait only when heating).

https://marlinfw.org/docs/gcode/M190.html:
> This command optionally sets a new target temperature for the heated bed and waits for the target temperature to be reached before proceeding. If the temperature is set with `S` then it waits _only when heating_.
>
> **Usage:**
> `M190 [I<index>] [R<temp>] [S<temp>]`
> 
> Parameters
> * `[R<temp>]` - Target temperature (wait for cooling or heating).
> * `[S<temp>]` - Target temperature (wait only when heating).
