### ISSUE TITLE
[BUG] with FILAMENT_RUNOUT_SENSOR enabled compile error in MarlinCore.cpp

### ISSUE THREAD

**Issue by wseifert** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#419]
### Bug Description

With enabled FILAMENT_RUNOUT_SENSOR in Configuration.h line# 2382 when I build the Project, compile error comes:

Marlin\src\MarlinCore.cpp: In function 'void event_filament_runout()':
Marlin\src\MarlinCore.cpp:458:9: error: 'host_action_paused' was not declared in this scope
         host_action_paused(false);
         ^~~~~~~~~~~~~~~~~~
Marlin\src\MarlinCore.cpp:463:11: error: 'host_action_pause' was not declared in this scope
           host_action_pause(PSTR(ACTION_ON_FILAMENT_RUNOUT " T"), false);
           ^~~~~~~~~~~~~~~~~
*** [.pio\build\MEGA_S_TMC_BLT_10\src\src\MarlinCore.cpp.o] Error 1

With FILAMENT_RUNOUT_SENSOR disabled no compile error.

### Steps to Reproduce

1. set Project Environment: MEGA_S_TMC_BLT_10
2. enable FILAMENT_RUNOUT_SENSOR in Configuration.h line# 2382: #define FILAMENT_RUNOUT_SENSOR
3. build the Project

**Expected behavior:** compilation without error
**Actual behavior:** compile stops with error in MarlinCore.cpp:458:9

**Comment by leonel85** [comment]
I remember that runout filament is inside custom functions. It’s enabled by default. You don’t need to enable standard marlin runout.
If you want search something like ANYCUBIC_FILAMENT_RUNOUT_SENSOR
or something like that
