### ISSUE TITLE
[Question] MKS TMC2208 V2.0. Muß ich trotzdem die invertierte TMC-Version nehmen?

### ISSUE THREAD

**Issue by v-a-d-e-r** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#42]
Hi. Die MKS TMC2208 V2.0 scheint nicht gedrehte Leitungen zu haben. Muß ich die TMC-Version trotzdem nehmen und dann die Leitungen vertauschen (wollte ich eigentlich mit der V2.0 umgehen...)? Oder braucht man eine TMC-Version OHNE vertauschte Leitungen?

VG

**Comment by knutwurst** [comment]
Hallo,
wenn die Leitungen schon gedreht sind (also dem Original entsprechen) nimmst du die Nicht-TMC Version. Ansonsten die für TMC, da hier per Software die Leitungen gedreht werden.
