### ISSUE TITLE
I3 Mega S startet kein Auto-Bedleveling 

### ISSUE THREAD

**Issue by Enie1** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#426]
Mein Sensor führt den Selbsttest aus und beginnt mit G29 auch das Bedleveling.
Jedoch blinkt der Sensor nach dem ersten Messpunkt kurz mehrfach in Rot auf und bleibt anschließend Rot/blau leuchtend, ohne die Nadel erneut auszufahren.
Und der Drucker drückt meine Nozzle durch die Ultrabase.
Weiß jemand einen Rat?
Hab nun mehrfach die Anleitung befolgt, jedoch bisher ohne Erfolg.

Hi there,
my BL-Touch-Sensor starts the selftest and Starts also the Auto-Bedleveling.
But after the first Point the Sensor starts Blinking Red an Blue up to 3 times. After that my Sensor does not pull the needle out and the Lights Red and Blue are on.
I tried Many different Versions of the new Firmware, but the Result was the same.
I have no Idea and don't know what should i do.

**Comment by DominicDevelop** [comment]
Hey :) Hast du es nach der Anleitung gemacht, also mit Löten oder wie ich ohne Löten über den Pin 21?
