### ISSUE TITLE
[BUG] Print head can crash at stop sequence

### ISSUE THREAD

**Issue by anno0** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#429]
### Bug Description

In cura there is a experimental mode to print one part at time. If this mode is active and the stop sequence at the display in the print menu is activated the print head can crash at a part. I attached an image.
 

### Steps to Reproduce

1. Use print option **one at a time**  
2. Activate stop sequence at the display.

**Expected behavior:** The print head goes to the top most point which was set at the complete previous print sequence.

**Actual behavior:** The print head only homes the x axis and maybe y axis.

#### Additional Information
![stop sequence](https://user-images.githubusercontent.com/2607705/216266262-7c280b0d-0238-480e-a698-7e920fdaeada.png)

![example](https://user-images.githubusercontent.com/2607705/216282227-15893428-b51d-4a0b-9abc-cae21db16aa9.png)

**Comment by alexlinuxoid** [comment]
Yes, there is such a problem. It is possible to disable all movements along the X and Y axes when printing is stopped, and raise the extruder slightly along the Z axis.
