### ISSUE TITLE
Special Menu ist not shown if SD card is not insertet. 

### ISSUE THREAD

**Issue by DjTimeout** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#43]
In previus Versions it was not necessary to have a sd card insertet. Now the special menu ist not shown if the SD card is missing. But where are the files stored? Eeprom or sd? There ist No file generated on the SD card.

### My Configurations

**Required:** Please include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

#### Additional Information

* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by knutwurst** [comment]
Oh, you are right! That was my fault... The bug is fixed here: https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/commit/eee52d4fd8922564239b9f64111c8afac415c28b
