### ISSUE TITLE
[BUG] Input Shaping geht nicht

### ISSUE THREAD

**Issue by v-a-d-e-r** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#430]
Hallo. Geht Input Shaping nicht in der 1.5.0b3? Ich dachte das wäre in der Marlin 2.1.2 drin? Bekomme nur das hier:

>>> M593
SENDING:M593
echo:Unknown command: "M593"

**Comment by stklcode** [comment]
siehe #402

 Nur weil ein Feature theoretisch möglich ist, ist es noch lange nicht automatisch enthalten. Einiges macht keinen Sinn, weil Hardware fehlt, anderes wäre möglich. Input Shaping müsste mal jemand ausprobieren und sinnvolle Parameter ermitteln.

**Comment by v-a-d-e-r** [comment]
Ich wollte es ja mal ausprobieren. Und da die Firmware hier ja noch Beta ist, wäre das nicht schlecht mit neuen Features zum Testen ;-)
