### ISSUE TITLE
[BUG] help!!!! Tried everything can’t get the bl touch to retract checked wiring and everything is fine.

### ISSUE THREAD

**Issue by neilneedshelp** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#433]
https://user-images.githubusercontent.com/125172731/218293404-344c935e-803d-4f8c-b228-3e6e014cf1fc.MOV

https://user-images.githubusercontent.com/125172731/218293426-0a198a35-b233-48a1-a2f5-aa35d8baff8f.MOV

https://user-images.githubusercontent.com/125172731/218293443-c2a98f1a-9c3c-4207-8774-329c49a9eb63.MOV

<!--

------ PLEASE USE THIS TEMPLATE! --------

Have you read all Wiki articles in cluding the FAQ?
https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/wiki

Do you want to ask a question? Are you looking for support? Please don't post here. Instead please use one of the support links at https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/issues/new/choose

Probe not working

<probe immediately fails when attempting to due the first probe just keeps going into the bed wiring is correct and so is the firmware 

 bl touch probes and moves to next point.

Bl touch collides with bed]

*

**Comment by stklcode** [comment]
Printer?
Board version?
Firmware version and flavor?
Wiring variation?
Sensor type?

I doubt anyone can help base from the 4s video sequence without any additional information.

**Comment by neilneedshelp** [comment]
ticorgorila 0.0.2
marlin beta 1.5.0 dgus blt mega x firmware 
used the alternate wiring method but could not find a firmware for it specifically
I have a genuine blt smart on an anycubic mega x

**Comment by NoOne86** [comment]
i have the same issue i have a Anycubic i3 Mega S with Firmware MEGA_S_BLT_10_v1.4.4.hex
And wiering version 1
