### ISSUE TITLE
[BUG] Pause / Continue does not work on display

### ISSUE THREAD

**Issue by anno0** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#435]
### Bug Description

I tried to pause the print with my Mega X and DGUS  clone display. I pressed Pause button and waited until the message for stop command was disappeared. After that I cleaned the nozzle and wanted to continue the print. This process does not work for me. 

I use Release 1.4.4.

### Steps to Reproduce
1. Start print
2. Press Pause button in print menu
3. Wait a bit
4. Press continue button

**Expected behavior:** it should continue printing.

**Actual behavior:** Nothing happens. The print head stands on its homing position.

#### Additional Information

* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by knutwurst** [comment]
It's a known issue which will be fixed in the future. Please use pause via USB/Octoprint instead.
See https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/releases
