### ISSUE TITLE
[BUG] (can't compile firmware)

### ISSUE THREAD

**Issue by kdaffy** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#441]
Hi, i find your firmware great and i used the ''MEGA_TMC_BLT_10'' ΗΕΧ but i have changed temp sensor(T1000) and i want to compile a little your firmware. I saw the tutorial ''https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/wiki/Howto:-Firmware-mit-PlatformIO-selbst-kompilieren'' and i did everything it suggests. BUT when i chose my MEGA_TMC_BLT_10 and press Build the task is running but never finishes. It doesn't provide an error but it just doesn't finish. Is there any solution? Thanks!!!!

**Comment by knutwurst** [comment]
Hi @kdaffy ,
can you provide some screenshots of the log output in visual studio code?

**Comment by kdaffy** [comment]
Ok, I'll do

**Comment by kdaffy** [comment]
I attach a google driver video. After i press build it stays in ''building'' state for hours. At the beggining the cpu is at 100% for couple minutes but then it iddles, but nothing happens.

https://drive.google.com/file/d/1_ten1y6GCbGWRpBN1LvViPC7ftwPl_cE/view?usp=share_link

**Comment by knutwurst** [comment]
To be honest.. at first is looks like your computer is pretty slow. And then, something does not add up. Do you have some virus scan or personal firewall installed, which might slow down everything? I just did the same thing : https://youtu.be/sNzT8HHou60

**Comment by kdaffy** [comment]
I can assure you that my pc is not the problem as is a gamer pc and pretty quick( I built it mostly for editing my drone videos in 4k). I did this clean button you did in the video but it doesn't do this either. I'll try something with firewall or antivirus and let you know. Thanks!!!

**Comment by kdaffy** [comment]
I finally managed to build BUT in my daughter's laptop which is less slow than mine. After it compiled i went again to the 2 folders icon and in the file ''MARLIN-2-0-X-ANYCUBIC-I3-MEGA-S-1.5.0-BETA.3'' Ifound another Marlin folder in which there was a configuration.h which i changed the temp sensor to 1047. Then i went to the alien face tab and pressed again the build and after the ''SUCCESS'' I went to the folder of the ''MARLIN-2-0-X-ANYCUBIC-I3-MEGA-S-1.5.0-BETA.3/.pio/build/MEGA_TMC_BLT_10'' in my pc and took the rirmware.hex which i will flash in my printer.
I wrote all the above steps to ensure i didn't something wrong and flash wrong firmware. If you see something wrong please let me know. Thanks!!!!!

**Comment by kdaffy** [comment]
it took me the whole day to make any suggestions i found on google, BUT nothing and i had finally a success by downloading an older version of vs code(1.69.1).
