### ISSUE TITLE
[BUG] Y-Endstop not working on MEGA_X_v1.5.0-b3 (Cura Flash), works on MEGA_X_v1.4.3

### ISSUE THREAD

**Issue by Shade-0117** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#443]
Updated from Stock firmware to MEGA_X_v1.5.0-b3 using Cura 5.2.1, everything works as expected except the Y-Homing ignores the Y-Endstop.

Steps to Reproduce:
1. Flash to firmware MEGA_X_v1.5.0-b3 using Cura (5.2.1)
2. Load and Save EEPROM as per directions
3. Turn printer off
4. Turn printer on
5. Home the printer

Expected behavior:
During homing the Y-Endstop is triggered so the bed stops rearward movement. 

Actual behavior:
During homing the Y-Endstop is ignored and bed crashes.

Additional Information
After discovering the issue, I attempted to reflash without restarting the printer between Load/Save EEPROM and the same issue persisted. After this I tried flashing to MEGA_X_v1.4.3. This fixes the issue, homes properly and Y-Endstop works as expected.

**Comment by leonel85** [comment]
I have the same problem
