### ISSUE TITLE
[FR] (feature request title)

### ISSUE THREAD

**Issue by MaticSmogavec** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#444]
### Description
Printer doesn't continue printing after pause- ANYCUBIC CHIRON, with BLTOUCH
WHen using M600 it changes filament with no problem but doesn't continue printing, same when pause is pressed on TFT.

### Feature Workflow

1. Pressing pause on TFT
2. printer stops printing, goes in "park" position, it idles, bed and nozzle temp are held steady same as while printing.
3. Pressing countinue on TFT
4. nothing happens, after few moment TFT becomes iresponsive to all commands.

#### Additional Information
I get these logged in serial:

// PAUSE PRESSED:
//action:paused
//action:prompt_end
//action:prompt_begin Pause
//action:prompt_button Dismiss
//action:prompt_show
echo:Send M108 to resume
//action:prompt_end
//action:prompt_begin Nozzle Parked
//action:prompt_button Continue
//action:prompt_show
echo:busy: paused for user
echo:busy: paused for user
echo:busy: paused for user

//CONTINUE PRESSED:
echo:Send M108 to resume
//action:prompt_end
//action:prompt_begin Reheat Done
//action:prompt_button Continue
//action:prompt_show
//action:prompt_end
//action:prompt_begin Paused
//action:prompt_button PurgeMore
//action:prompt_button Continue
//action:prompt_show
echo:busy: paused for user
echo:busy: paused for user
echo:busy: paused for user
echo:busy: paused for user
echo:busy: paused for user
echo:busy: paused for user

**Comment by knutwurst** [comment]
As mentioned in the release notes, the pause/resume via tft is not possible atm.
