### ISSUE TITLE
[BUG] Using of switch KNUTWURST_MEGA_P_LASER unclear

### ISSUE THREAD

**Issue by USGNew** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#445]
### Bug Description

The description of KNUTWURST_MEGA_P_LASER said it will be set automatic, if KNUTWURST_MEGA_P is set.
This will never happen, because it is commented out.

Line 70, configuration.h
/*
 * This enables the integrated Laser engaving feature
 * in the anycubic touchscreen. It's currently only
 * supported by the Anycubic MEGA Pro and therefore it
 * is automatically set if the MEGA_P is enabled.
 *
 */
#if ENABLED(KNUTWURST_MEGA_P)
   **//** #define KNUTWURST_MEGA_P_LASER
#endif

### Steps to Reproduce

1.  version MEGA_P_DEGUS used
2.  remove comment in line 78

**Expected behavior:** [What you expect to happen]
build works or please change comment, like: not supported in the moment....

**Actual behavior:** [What actually happens]
build failed

#### Additional Information

* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by stklcode** [comment]
It effectively enables an experimental, yet incomplete port of the original Anycubic laser feature. You are right, it does not even compile at the moment.
