### ISSUE TITLE
[BUG] Input shaping not enabled in 1.5b3?

### ISSUE THREAD

**Issue by joseaguardia** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#446]
### Bug Description

When launching the M593 command, the result is "unknown command"

### Steps to Reproduce

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

#### Additional Information

* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by stklcode** [comment]
duplicate of #402
