### ISSUE TITLE
intermittent bug with 1.5 beta 3 and problem with input shaping

### ISSUE THREAD

**Issue by djepsylon** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#454]
I put in my mega pro a precompiled firmware of version 1.5 beta 3 and from time to time, when a print starts, the z-axis goes up to the maximum stop instead of doing its normal homing. and my 2nd problem is I noticed that the input shaping was not activated in the precompiled firmware so I tried to compile it myself but I have compilation errors and impossible to compile the firmware with the input shaping added in the config.adv.h while in the platformio I have well the line of the input shaper which is active. would it be possible to have a precompiled version with the input shaper for the mega pro card 1.0 and clone DGUS for the screen?

Translated with www.DeepL.com/Translator (free version)

**Comment by knutwurst** [comment]
Unfortunately, InputShaping is a very new feature that has only been implemented rudimentarily in Marlin so far.

Since I tackle all bugs first, I don't take care of new features until later. sorry

I can't help you at this point. I'm sorry.
