### ISSUE TITLE
[BUG] gcode file extension display

### ISSUE THREAD

**Issue by anno0** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#455]
### Bug Description
Display error of hidden folder. I have seen this also in another bug https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/issues/453

### Steps to Reproduce

1. Create a hidden folder on a SD card. This is normally a trash folder in Ubuntu. 
2. Insert the SD card in the printer 
3. Navigate to the print menu 

**Expected behavior:** This folder should not be shown in the print menu and even should not have a gcode file extension.

**Actual behavior:** The gcode file extension is display at position of the buttons  

![gcode extension](https://user-images.githubusercontent.com/2607705/233859647-ed938677-ccbf-42d9-be15-3759eb9e406e.jpg)

#### Additional Information
Firmware 1.5.0 beta 3
DGUS clone display

**Comment by knutwurst** [comment]
Can you compile the firmware by yourself? The issue *should* be fixed now, but is untested atm. I'll try it out if I have time and build a new Beta, but for now, the current master should work fine.

**Comment by anno0** [comment]
I do not have compiled this project yet myself but I will figure it out next week.

**Comment by anno0** [comment]
I compiled the master branch and flashed my printer. The print menu entries with gcode file extension look good again.

**Comment by knutwurst** [comment]
>I compiled the master branch and flashed my printer. The print menu entries with gcode file extension look good again.

That's great to hear. Thank you for testing!
