### ISSUE TITLE
BLT Probing via gcode

### ISSUE THREAD

**Issue by DunklerPhoenix** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#46]
Heho

is it possible to start the mesh bed leveling with bltouch via gcode?

What GCodes does the entry in special menu sent? G29?

**Comment by knutwurst** [comment]
Hi, of course you can do this. Take a look at https://marlinfw.org/docs/gcode/G029.html

The Menu sends:
G28
G29
M500
G90
G1 Z30 F4000
G1 X0 F4000
G91
M84
