### ISSUE TITLE
[BUG] (mega s no special menu)

### ISSUE THREAD

**Issue by kotarokun** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#463]
### Bug Description

In Update 1.5 beta 4 is special Menu not working anymore. I downgrade to 1.5 B3 and it works again

### Steps to Reproduce

After upgrading no special menu is working. It is standing in my display but can not accessing anymore by selecting and entering.
I have no SD card inside my mega S with bltouch and Mainboard 1.0 and no deus display
.

**Comment by v-a-d-e-r** [comment]
Can confirm this....

**Comment by knutwurst** [comment]
It works - but only when the SD card is inserted. 
The fix is WIP :)

**Comment by v-a-d-e-r** [comment]
And we can expect it before x-mas...? ;-)

**Comment by knutwurst** [comment]
Of course :D

**Comment by v-a-d-e-r** [comment]
Sounds good! 8-P
