### ISSUE TITLE
Wird BlToch nicht zu Warm? 

### ISSUE THREAD

**Issue by TigerMAST** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#466]
Hi,

Ich habe vor an mein Mega X ein BlToch einzubauen. Doch habe ich bedenken das wenn man ihn so nah an das hotend baut er zu warm wird?

**Comment by stklcode** [comment]
Was heißt "so nah"?
An der u.a. hier im Wiki vorgestellten Position im Hotend-Schlitten passt das schon. Adapterstück aus PLA ist nicht empfehlenswert, ABS funktioniert jetzt seit längerem ohne Probleme. 10h Druck bei >200°C Hotend beeindruckt den Sensor selbst nicht wirklich.

Aber im Prinzip kannst du das Teil natürlich auch weiter außen anbringen, funktioniert auch.
