### ISSUE TITLE
[BUG] Unable to change LCD language

### ISSUE THREAD

**Issue by OkiGraphics** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#47]
### Bug Description

Hi, I downloaded raw code and built it on my own with platformio. I want to have my printer in Czech language, so I added "-DLCD_LANGUAGE=cz" to _build_flags_ in [env:MEGA_S_DGUS] of _i3_mega_envs.ini_.

### My Configurations
I have Mega-S printer with new "yellow/blue" interface, so I used modified MEGA_S_DGUS environment.

### Steps to Reproduce

1.  Add "-DLCD_LANGUAGE=cz" to _build_flags_ in **[env:MEGA_S_DGUS]** of _i3_mega_envs.ini_
2.  Build
3.  Upload

**Expected behavior:**
Czech language in menu
**Actual behavior:**
English language in menu

In menu language setting still only switches between English and Chinese. I assume flashing the firmware was successful as there is "Firmware version KW-1.1.7" in info screen. Thank you for any advice.

**Comment by knutwurst** [comment]
You cannot change the display language of the TFT, as each TFT has its own controller and is not an independent display. Therefore, no display elements can be changed. See: https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/wiki/FAQ-(english)
