### ISSUE TITLE
octoprint bed visualizer

### ISSUE THREAD

**Issue by TigerMAST** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#470]
kann man den octoprint bed visualizer benutzen? 
und wenn ja wie?

**Comment by HaGueRe** [comment]
Der bed visualizer in Octoprint macht genau das, was er soll: Die im EEPROM gespeicherten Daten, die über das Mesh Bed Leveling ermittelt wurden, in einer 3D-Grafik darzustellen. Nicht mehr und nicht weniger.

**Comment by TigerMAST** [comment]
wie muss ich denn den bed visualizer in octoprint einrichten

**Comment by kgabriel-dev** [comment]
Um deine Frage zu beantworten: Ich benutze den Befehl `M420 S1 V`. Damit levelst du das Bett nicht neu, es wird also das zuletzt gemessene Mesh angezeigt.
