### ISSUE TITLE
[BUG] "Hotend temperature abnormal" warning never actually triggered

### ISSUE THREAD

**Issue by stklcode** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#475]
### Bug Description

We have a routine to check for heater errors using a timeout counter that is incremented if the temperature is out of range:

https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/blob/0981430d4be596ba4cc767ab4126921868ddb988/Marlin/src/lcd/extui/knutwurst/anycubic_touchscreen.cpp#L982-L984

The counter condition will never be true, because `HeaterCheckCount` is declared `uint16_t` which is bound to `[0, 65535]`.

https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/blob/0981430d4be596ba4cc767ab4126921868ddb988/Marlin/src/lcd/extui/knutwurst/anycubic_touchscreen.h#L230

### Steps to Reproduce

1. Let the printer under- or overheat
2. Wait some time

(no, you should probably not try this at home :wink:)

**Expected behavior:** An error "Hotend temperature abnormal..." should pop up.

**Actual behavior:** Nothing.

(no, I did not test this for real, but the behavior should be pretty straight forward from the code)

#### Additional Information

--

### Question

600.000 is pretty high. This was actually increased from 60.000 in 85bac6b3960966b49f23a694cf75562842f26e80

Should we lower the limit again or increase the counter size to `uint32_t` or similar?

**Comment by knutwurst** [comment]
To be honest - I don't know why I increased the heater check count.
Maybe it's a good Idea to lower it an test everything.
