### ISSUE TITLE
[FR] Thermister via Menü anpassen? Anycubic 4max pro 2.0

### ISSUE THREAD

**Issue by anjoku** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#480]
Themistor via Menü anpassen?

Danke für die Firmware. Ich hoffe meine Frage ist hier richtig. Facebook habe ich nicht.

Ich habe einen Anycubic 4max pro 2.0. Deine Firmware habe ich erfolgreich geflasht.
Leider wird die Hotentemperatur ca. 30 °C zu hochangezeigt. Also die tatsächliche Temperatur ist 30 °C zu gering.
Gemessen mit einem Fluke 52 Digitalthermometer. Fühler direkt im Befestigungsloch für den Thermistor und Silikonschutz drüber.
Auch gegengetestet mit einem Oberflächenfühler, direkt auf der Heizblockfläche.
Das sollte ausreichend guten Kontakt sein.

Wie kann ich den Wert am einfachsten anpassen?

**Comment by knutwurst** [comment]
Der Thermistor lässt sich nicht zur Laufzeit anpassen.
Für den 4MAX wird der Typ 11 für den Heizblock und Typ 5 für das Hotbed verwendet. Diese Werte müsstest du für deinen Drucker dann anpassen: https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/blob/af83c12790ecc522cf0046817afae46f2127cb2d/Marlin/Configuration.h#L627

Und dann natürlich die Firmware selbst kompilieren (Anleitung ist im Wiki)
