### ISSUE TITLE
[BUG] (Y Axis does not home properly with TriGorilla_V0.0.2 board)

### ISSUE THREAD

**Issue by Mave74** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#484]
### The Y Axis does not stop homing and "rattles" as the stepper loses steps because it rams against the physical end of the axis
every other firmware works fine but I've tested all of the 4MAXP2 with BLTouch and none of them worked. I had to look into the pins.h to see that the Y_endstop pin has been "rerouted" to the Z+ endstop, as described by the pinout diagrams of the said motherboard.

see line->   "#define Y_STOP_PIN                          19  // Z+" in file "pins_trigorilla_xx.h"

to fix this I had to reroute the Y endstop from D43 Aux pin to Z+ Endstop pins

- this was not detailed anywhere and it took me a while to figure out

**Comment by fiandrino** [comment]
Good morning, I have the same issue as you. I wanted to kindly ask if you could explain to me in more detail what the line is and how you modified it in the file "pins_trigorilla_xx.h." Thank you for your attention.

**Comment by Mave74** [comment]
Hello, I didnt change anything in the code because the firmware didnt work anyways because the bltouch didnt work, but i got the endstop working just by „unpinning“ the original endstop plug for Y and plugging the (yellow) signal wire to Z- or whatever i posted in the original post, since then i compiled my own firmware because this didnt work for me at att sadly

hope this helps
________________________________
Von: Giorgio Fiandrino ***@***.***>
Gesendet: Friday, August 18, 2023 6:34:25 PM
An: knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S ***@***.***>
Cc: Mave74 ***@***.***>; Author ***@***.***>
Betreff: Re: [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S] [BUG] (Y Axis does not home properly with TriGorilla_V0.0.2 board) (Issue #484)


Good morning, I have the same issue as you. I wanted to kindly ask if you could explain to me in more detail what the line is and how you modified it in the file "pins_trigorilla_xx.h." Thank you for your attention.

**Comment by knutwurst** [comment]
Fixed in the current version :)
