### ISSUE TITLE
[FR] (Sorry if I am posting this in wrong category)

### ISSUE THREAD

**Issue by StrikerP75** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#487]
Hi I am totally new to github and I have question about what HEX file I should use for Trigorilla Board Model 4 this one
![image](https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/assets/143207219/d114fd48-b174-4ea8-9798-d48f1ed1d410)
I am really sorry if I am causing some problems but I am just total newbie to 3D printing and to be honest I have no freaking idea about building marlin.

**Comment by Ingegneus** [comment]
read the beginners guide here: https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/wiki/Beginner's-Guide-(English)

if you have any specific questions after that, feel free to ask

**Comment by knutwurst** [comment]
Hi @StrikerP75 ,
yout board is something completely different. It uses the CHITU firmware and does not support Marlin afaik.
