### ISSUE TITLE
[BUG] Filament In & Filament Out commands not working (Mega S)

### ISSUE THREAD

**Issue by LucasAGranzotto** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#488]
### Bug Description

After installing MEGA_S_BLT_10_v1.5.2.hex, the commands to extrude, filament in and filament remove, either from the touchscreen or Octoprint, simply don´t work

### Steps to Reproduce

1. Flash MEGA_S_BLT_10_v1.5.2 on a Anycubic i3 Mega S with Trigorilla v0.02 PCB and stock drivers
2. Try to extrude via touchscreen Filament Menu or Octoprint Control tab page

**Expected behavior:** The selected length of filament is extruded

**Actual behavior:** Nothing happens

**Comment by knutwurst** [comment]
It's fixed in the current version
