### ISSUE TITLE
[BUG] Software endstops are ignored 

### ISSUE THREAD

**Issue by TigerMAST** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#492]
If I press Home all on the display and then move the print head in the direction of the software end stop, it is ignored. 
But if I home with the command G28 it does not happen.

**Comment by knutwurst** [comment]
That's not a bug. It's intended behaviour that the user can adjust the print head if needed. The soft endstops are used while printing.

**Comment by TigerMAST** [comment]
It is normal that when I home the printer I can move the print head so far in one direction until it reaches the end and the motor continues to rotate?

**Comment by knutwurst** [comment]
Yes, that's normal.
