### ISSUE TITLE
[question] Setting up POWER_LOSS_RECOVERY

### ISSUE THREAD

**Issue by OkiGraphics** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#51]
Hi, since I use your firmware (which I am very grateful for :+1: ) which is dedicated directly for MEGA-S, I decided to ask the question here and not on official Marlin thread.

I saw "Resumption of printing after a power failure (WiP)" in features. What exactly means work in progress here? How does it work with default Mega-S (without UPS)?  I see "POWER_LOSS_RECOVERY" in my configuration_adv  is commented-out, but as it is built by platformio that does not mean much - it is enabled by default in your firmware (e .g. included in common build flags)? I tried to send M413 to my printer but it says "unknown command", so I am confused. I will be grateful for any help in this regard. Thank you.

## My configuration:
I use [env:MEGA_S_DGUS]

**Comment by knutwurst** [comment]
As you can see, the power loss support is WiP (work in progress) but so far I have not developed any further in this direction, as the effort is very high and the benefit is very low.

Also you need to set the G5 gcode in your starcode to enable this feature.
