### ISSUE TITLE
[BUG] Mega Pro built-in bed-leveling no longer working

### ISSUE THREAD

**Issue by CraftoHohenvels** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#519]
### Bug Description
With this fw my Mega Pro will home when using the vanilla bed leveling. But if you hit next it doesn't react. Like nothing, except the stepper making noises. It works after reflashing the original fw.

### Steps to Reproduce
1. Download the [firmware](https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/releases/download/1.5.2/MEGA_P_DGUS_TMC_v1.5.2.hex)
2. Flash the firmware using OctoPrint Firmware Flasher
3. Try to use vanilla leveling

**Expected behavior:** move to the next position

**Actual behavior:** The steppers just product very silent noises, but the head doesn't move.

**Comment by stklcode** [comment]
Already fixed in #509 (not released yet)

**Comment by CraftoHohenvels** [comment]
Good to know!
