### ISSUE TITLE
[BUG] Anycubic Mega Pro keeps printing on the front right corner

### ISSUE THREAD

**Issue by Blubberland** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#526]
## Bug Description

Anycubic Mega Pro keeps printing on the front right corner, instead of the middle of the bed.

### Steps to Reproduce
The printer hasn't been modified.

Following this guide step by step to step 8(*):
https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/wiki/Beginner's-Guide-(English)
- Identidied Printer: Mega Pro (Mega S with laser, BMG extruder and TMC drivers on X and Y. The Anycubic 0.0.2 display is always used)
- identified display: 2.3 The Anycubic 0.0.2 display (DGUS clone)
- Identified Mainboard: Trigorilla 0.0.2
- Chose Printer in Cura: Anycubic i3 Mega S/Pro
- Downloaded Firmware: MEGA_P_DGUS_v1.5.3.hex (also tried v1.5.1 because someone had a problem with a newer version. The problem was unrelated to mine, but tried nonetheless)
- Installed the FW via Cura
- Loaded _default settings_ and _saved EEPROM_
- didn't changed the bed size (after trying it out and revoked later, because it printed over the edge)
- ticked _Origin at center_ (after trying it unticked)
- Adjusted _Mesh Fixes_ and _Cooling_ in Cura
- Used recommended Start and Endcode (also used the default which I assume is provided by the profile in Cura - no difference regarding this issue, which I assumed beforehand, without knowing anything about gcode)

**Expected behavior:**
Print the object in the middle of the bed

**Actual behavior:**
See bug description

### Board
![IMG_20240329_230319](https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/assets/109285352/72565554-b61e-469c-9319-2e99cdd0188b)

### Results
Pictures were made while printing without changing the bed size, because otherwise it was printed over the edge.

![IMG_20240403_165137_110](https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/assets/109285352/eeb24c9a-942a-42a9-9d2d-2198e200709f)

![IMG_20240403_172004_476](https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/assets/109285352/0465ca51-716f-41a8-bc10-0a9c1d912a01)

**Comment by Blubberland** [comment]
When using Octoprint, the following error appears, which looks like it was related to the issue:
![image](https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/assets/109285352/57a3aa01-b995-47f9-8b31-e1d38ca25e72)

I get the feeling I'm doing something wrong in Cura...

**Comment by stklcode** [comment]
> ticked Origin at center (after trying it unticked)

The actual origin is in the front left corner, not in the center.
Your object is sliced to be printed at -11mm in X/Y direction. It’s not possible to print outside the bed and you are running into (soft) endstops.

**Comment by Blubberland** [comment]
Yep, figured that. Thank you very much anyway!
Now I have to figure out why Octoprint throws Autoleveling-Errors.
