### ISSUE TITLE
[BUG] Octoprint Terminal says Printer seems to support the busy protocol, will adjust timeouts and set busy interval accordingly

### ISSUE THREAD

**Issue by xTimoDEx** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#53]
Hallo ich habe eine Frage. Ich habe deine Firmware in der version 1.1.9 installiert und ich habe einen Anycubic Megsa S mit dem TFT CLone. Während ich drucke seh ich im Terminal vermehrt 👍 `Changing monitoring state from "Operational" to "Starting"
Send: N0 M110 N0*125
Recv: ok
Changing monitoring state from "Starting" to "Printing"
Send: N1 M82*24
Recv: ok
Send: N2 G21*24
Recv: ok
Send: N3 G90*19
Recv: ok
Send: N4 M82*29
Recv: ok
Send: N5 M107*32
Recv: ok
Send: N6 M140 S60*85
Recv: ok
Send: N7 G4 S60*95
Recv:  T:200.54 /200.00 B:60.00 /60.00 @:39 B@:45
Recv:  T:200.13 /200.00 B:60.01 /60.00 @:46 B@:43
Recv: echo:busy: processing
Printer seems to support the busy protocol, will adjust timeouts and set busy interval accordingly
Recv:  T:200.00 /200.00 B:60.00 /60.00 @:47 B@:45
Recv:  T:200.00 /200.00 B:59.97 /60.00 @:46 B@:48
Recv:  T:199.97 /200.00 B:60.00 /60.00 @:46 B@:44
Recv: echo:busy: processing
Recv:  T:199.80 /200.00 B:60.01 /60.00 @:48 B@:43
Recv:  T:199.67 /200.00 B:60.00 /60.00 @:50 B@:44
Recv: echo:busy: processing
Recv:  T:199.54 /200.00 B:60.01 /60.00 @:51 B@:43
Recv:  T:199.64 /200.00 B:60.01 /60.00 @:50 B@:43
Recv:  T:199.80 /200.00 B:60.01 /60.00 @:47 B@:43
Recv: echo:busy: processing
Recv:  T:199.93 /200.00 B:60.00 /60.00 @:46 B@:44
Recv:  T:200.00 /200.00 B:60.01 /60.00 @:46 B@:43
Recv: echo:busy: processing
Recv:  T:200.00 /200.00 B:59.99 /60.00 @:46 B@:46
Recv:  T:200.00 /200.00 B:60.00 /60.00 @:47 B@:44
Recv:  T:200.00 /200.00 B:60.00 /60.00 @:47 B@:44
Recv: echo:busy: processing
Recv:  T:200.00 /200.00 B:60.00 /60.00 @:47 B@:44
Recv:  T:200.00 /200.00 B:60.01 /60.00 @:47 B@:42
Recv: echo:busy: processing
Recv:  T:200.00 /200.00 B:60.00 /60.00 @:47 B@:44
Recv:  T:200.00 /200.00 B:60.00 /60.00 @:47 B@:44
Recv:  T:200.00 /200.00 B:60.00 /60.00 @:47 B@:44
Recv: echo:busy: processing
Recv:  T:200.00 /200.00 B:59.99 /60.00 @:47 B@:45
Recv:  T:200.09 /200.00 B:60.00 /60.00 @:46 B@:44
Recv: echo:busy: processing
Recv:  T:200.22 /200.00 B:60.01 /60.00 @:44 B@:42
Recv:  T:200.09 /200.00 B:60.00 /60.00 @:46 B@:44
Recv:  T:200.04 /200.00 B:60.01 /60.00 @:46 B@:42
Recv: echo:busy: processing
Recv:  T:200.00 /200.00 B:60.00 /60.00 @:47 B@:43
Recv:  T:200.27 /200.00 B:60.00 /60.00 @:43 B@:43
Recv: echo:busy: processing
Recv:  T:200.13 /200.00 B:60.01 /60.00 @:45 B@:42
Recv:  T:200.04 /200.00 B:60.00 /60.00 @:46 B@:43
Recv:  T:200.00 /200.00 B:60.01 /60.00 @:47 B@:42
Recv: echo:busy: processing`

Das geht dann immer so weiter ist das Normal?

**Comment by knutwurst** [comment]
That's not a bug. It's intended. Also you can suppress these messages in octoprint. See: https://community.octoprint.org/t/what-is-with-all-the-recv-busy-processing-messages/5968/4
