### ISSUE TITLE
Trigorilla mainboard v1.1 bl touch Anschluss

### ISSUE THREAD

**Issue by sims-60** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#59]
Hallo,
wo am trigorilla mainboard muss ich meinen bl touch anschließen? Ich habe wahrscheinlich ein Trigorilla v1.1 mainboard (https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/issues/50#issuecomment-762755639 )
Danke

**Comment by maikkoe** [comment]
Moin,

dort sollte der Anschluss sein:
![bltouch](https://user-images.githubusercontent.com/48993339/105176727-e5aa6880-5b25-11eb-9c39-85b336ffdbc1.png)

**Comment by knutwurst** [comment]
@sims-60 schau mal in's Wiki. Dort findest du auch eine Anleitung mit Bildern :) 

Lediglich das v1.2 (0.0.3) Board wird noch nicht unterstützt. Ich arbeite aber dran.

**Comment by sims-60** [comment]
also kann ich es auf den selben stecker stecken und muss nur die firmware mit _11 draufladen?

**Comment by maikkoe** [comment]
Wichtig ist, dass du darauf achtest die Pins richtig zu belegen. Ich hab das 0.0.2 und habe die _10 installiert. Hat alles wunderbar geklappt wie in der Anleitung beschrieben, habe den Sensor selbst erst jetzt am Wochenende nachgerüstet.

**Comment by sims-60** [comment]
bei mit ist die steckerleiste auf s1 festgelötet soll ich dann _10 oder _11 nehmen

**Comment by maikkoe** [comment]
Wie du auf meinem Bild siehst, ist sie bei mir ebenfalls dort verlötet. Die _10 sollte da die richtige sein, ansonsten wenn das nicht geht, kannst du immer noch die 11er flashen

**Comment by sims-60** [comment]
und soll ich dann die pins wie in der anleitung vertauschen

**Comment by sims-60** [comment]
dachte nur das wenn ich die falsche firmware drauf flashe oder so das ich mit dann den bl touch schrotten kann

**Comment by maikkoe** [comment]
Das kann ich dir so leider aus dem Kopf nicht sagen, ich meine ich musste es bei mir machen. Auf dem Board ist aber Links eine Beschriftung was welcher Pin ist. Bei mir, von oben nach unten S/-/+

**Comment by sims-60** [comment]
danke bei mir ist es auch s - +

**Comment by maikkoe** [comment]
Kontrolliere es bitte dennoch anhand deiner Verkabelung/Sensor.

**Comment by sims-60** [comment]
iich mache erst jetzt die verkabelung xD

**Comment by sims-60** [comment]
danke funkttioniert jetzt alles habe auch die _10 firmware

**Comment by kallejoken** [comment]
Ich möchte auch gerne den bltouch nachrüsten, nun ist auf dem Mainboard v1.3 aufgedruckt, kann ich diesen nun nicht verbauen?
![16136871522443831499316997560020](https://user-images.githubusercontent.com/72359598/108429754-acf2d180-7240-11eb-9390-f78ef96db9c8.jpg)
![16136871730738468112452373523210](https://user-images.githubusercontent.com/72359598/108429810-c136ce80-7240-11eb-934e-c0bed3f8f5c6.jpg)

**Comment by sims-60** [comment]
hi

sollte denke ich gehen aber su sicht links nebem der steckerleiste +-s und am sensor ist 
weiß / orange = Signal  
schwarz / braun = Masse/Ground
rot = +5V 
muss schauen dass es extat so dann auf dem board ist
