### ISSUE TITLE
[FR] Support for 4Max Pro 2.0 (and original 4MP)

### ISSUE THREAD

**Issue by alfrankgit** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#65]
Hi! I really appreciate the effort you put into the Anycubic Mega Firmwares, since Anycubic doesn't do anything.

How about supporting the 4Max Pro (2.0 and original version) also? They have the same boards and displays.

For the 4Max Pro 2.0 I already patched your V1.1.9 in the Mega P TMC sections, see the attached Configuration.h and Configuration_adv.h. It has a BMG clone extruder, TMCs for X and Y, other thermistors. I had to disable the Anycubic Filament Sensor option.

I commented all my changes with //AFR.

But I am no programmer so I can't add a new environment to your project. But that would be nice to have, wouldn't it?

I also have three of the original 4Max Pro but none still in the original configuration, so I'm not sure what that was. IIRC it doesn't have TMCs and it definitely has the original DWIN display. But it has the Titan clone extruder. And hotend thermistor type 11. But I can test a configuration for that one too, if you can create an env for it.

PS: My native language is German.

Edit, 26.01.2021: made a few changes in speed and acceleration settings, reuploaded changed files...

[4MP_2.0_KW1.1.9.zip](https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/files/5875815/4MP_2.0_KW1.1.9.zip)

**Comment by knutwurst** [comment]
Hello,
so since the hardware seems to be the same, that wouldn't be a problem and I think it's great that you have already done the preparatory work :)

But I'm currently working on support for the Chiron - and by that I also mean support for all display functions, including leveling. There is also very strong demand for support for the Mega Pro Laser.

I'll see how quickly it goes with the 4MAX Pro, but I can't promise that I can take care of it right away. But I'll write it on my agenda :)

**Comment by alfrankgit** [comment]
Hi,
and thanks a lot for your reply and infos.

As a moderator on drucktipps3d.de I'd gladly welcome you to our forum where I already recommended your excellent firmware quite a few times.

**Comment by knutwurst** [comment]
I've included the 4MAX pro 2.0 build environment for stock and TMC. I actually don't know if all motor directions are correct, so please give me some feedback, what's not working correctly
[KW-131-4MAXPRO2.zip](https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/files/7446174/KW-131-4MAXPRO2.zip)
.

**Comment by knutwurst** [comment]
I've included the 4MAX pro 2.0 build environment for stock and TMC. I actually don't know if all motor directions are correct, so please give me some feedback, what's not working correctly
[KW-131-4MAXPRO2.zip](https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/files/7446174/KW-131-4MAXPRO2.zip)
.

**Comment by alfrankgit** [comment]
Thanks for including the 4Max Pro 2.0 now, but I can't test it myself anymore because I don't own the 4Max Pro 2.0 anymore. But there are users on drucktipps3d.de who do and are aware of your firmware and my "hacks".
https://drucktipps3d.de/forum/topic/anycubic-4max-pro-2-0/?part=23#postid-180447

**Comment by knutwurst** [comment]
@alfrankgit Maybe you can shed light on the darkness. I saw in your config that you are using the Build Environment of the MEGA_P and activate both MEGA_P, TMC and DGUS2 for it.

Are these settings for the stick 4MAX or for one in which all drivers have been substituted for TMC2208?

If you built MEGA_P_TMC for the 4MAX stock, I had a mistake in thinking and maybe the directions of the two versions (TMC and non-TMC) are now reversed  :D

I'm looking forward for some "testers" ;)

**Comment by alfrankgit** [comment]
I didn't change any physical stepper drivers on the 4Max Pro 2.0.
All my changes in the configuration files are marked with //AFR, either as a new comment to disable a line or as a comment with the original content of the line followed by a line tight the changes I made.

**Comment by knutwurst** [comment]
...then... the 4MAX_TMC version should work on stock. Let's wait for feedback. 

And thank you again for your provided config!

**Comment by JonnyHaystack** [comment]
I've been using alfrank's config with MEGA_P_TMC environment. I can test with the new environment at some point :smile:

**Comment by knutwurst** [comment]
After getting some feedback I added configurations for both, Stock and full TMC Versions. Now also for the original 4MAX Metal. 
The case light (controllable via touchscreen) should also work. Please let me know if there are any other issues. If not, I'll release the version in the upcoming days.

[KW_4MAX_4MAXPRO2_v1.3.1.zip](https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/files/7447746/KW_4MAX_4MAXPRO2_v1.3.1.zip)

**Comment by q4wey** [comment]
> After getting some feedback I added configurations for both, Stock and full TMC Versions. Now also for the original 4MAX Metal. The case light (controllable via touchscreen) should also work. Please let me know if there are any other issues. If not, I'll release the version in the upcoming days.
> 
> [KW_4MAX_4MAXPRO2_v1.3.1.zip](https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/files/7447746/KW_4MAX_4MAXPRO2_v1.3.1.zip)

I'm new to this thread and have limited experience with marlin but I tested your hex files currently I have found the file titled (4MAXP2_v1.3.1-4MP2) to work but with 2 glitches. I don't know if these glitches are unique to my machine 4maxv2
or in the firmware itself. The display will run two intro cycles on startup and the stop print button will flicker until the tool head is parked. 

I hope this info is of anyhelp.

**Comment by MasterYod4** [comment]
Hello first of all, I would like to thank you very much for your work!
I tested version 4MAXP2_v1.3.1-4MP2 on my 4Max Pro 2.0. What I noticed is that the light button now works but the normal 4 point leveling in Anycubic Menu doesn't work.
As described by q4wey, the intro runs twice but I couldn't detect the stop button flickering.

**Comment by CruisenRainerWahnsinn** [comment]
> 
> 
> Hello first of all, I would like to thank you very much for your work! I tested version 4MAXP2_v1.3.1-4MP2 on my 4Max Pro 2.0. What I noticed is that the light button now works but the normal 4 point leveling in Anycubic Menu doesn't work. As described by q4wey, the intro runs twice but I couldn't detect the stop button flickering.

Yes, same for me (tested 4MP2 stock version). The original "Leveling"-Button isn't working (like in the self compiled versions before).

@MasterYod4 
You can go to "print" -> "Special Menu" to get 4 point or even Mesh bed leveling.

**Comment by MasterYod4** [comment]
@CruisenRainerWahnsinn Thanks for the hint.

**Comment by knutwurst** [comment]
> The original "Leveling"-Button isn't working

I know... that's because it's not implemented at all. I just included the build paths and ne configurations and "hacked" the light control in. This isn't final at all. It's just a milestone. I'll take a look at anycubic's implementation of the leveling menu. If it's straight forward, i'll implement it also.

In the meantime, you can use the specialmenu like @CruisenRainerWahnsinn mentioned :)

**Comment by JonnyHaystack** [comment]
Is the filament runout sensor working? I think some other people may have got it working in forks that I've seen

**Comment by knutwurst** [comment]
@JonnyHaystack it's currently disabled until I figured out the correct pin.

**Comment by hanebuechenes** [comment]
Is there also a version for the 4max pro 1? I have one and i can test it!

**Comment by hanebuechenes** [comment]
Tested the version KW_4MAX_4MAXPRO2_v1.3.1.zip on stock 4max V1. seems to work nice, only the Y axis is wrong direction. Can i change this somewhere, or have it to be compiled again?

**Comment by CruisenRainerWahnsinn** [comment]
> 
> 
> Tested the version KW_4MAX_4MAXPRO2_v1.3.1.zip on stock 4max V1. seems to work nice, only the Y axis is wrong direction. Can i change this somewhere, or have it to be compiled again?

Which hex file did you chose of the zip? There are 4 files.

I'm not sure if it is true for the 4max (1), but if you use TMC Version of 4MP2 the direction is switched. So the TMC version of it might fix this issue.

**Comment by MasterYod4** [comment]
I played around a bit today and noticed the following:

Set flow rate - works
Preheat Ultrabase - works
4 Point Leveling - only drives up to point A, all other points are not approached
Mesh leverling - works
PID Tune Hotend - does not work
PID Tune Ultrabase - works

**Comment by Yury-MonZon** [comment]
I second what MasterYod4 said. 

Also, I've tried both TMC and non-TMC version on 4Max Pro 2.0(which has TMC installed by default). TMC version has Z axis reversed.

On both versions I can read/send commands via USB, I've tried 57.6k, 115.2k and 250k baudrate - got corrupted data. The cable and drivers are fine - I can successfully flash the board. 

Stopping the printing process from the touchscreen shows me like a thousand of popup screens that stop is done. It doesn't happen if I pause the print and then stop it.
I'm able to test multiple times, if it could be useful to developer - let me know.

**Comment by Daventrik** [comment]
i would be glad to help with testing but i didn't flashed my printer with these versions yet, still on stock but i have the "round corners" on a square and i hope that the new firmware can solve that issue since the profile tuning is not solving this. How can i help?

**Comment by knutwurst** [comment]
1.4.0 Beta 2 is out now.

**Comment by CruisenRainerWahnsinn** [comment]
> 
> 
> i would be glad to help with testing but i didn't flashed my printer with these versions yet, still on stock but i have the "round corners" on a square and i hope that the new firmware can solve that issue since the profile tuning is not solving this. How can i help?

Try setting K factor to 0.2

Send "M900 K0.20" and safe with M500
Try 190°C (if PLA)
Get a e3d V6 nozzle (fits on stock hotend)
=> big improvement

**Comment by q4wey** [comment]
> 1.4.0 Beta 2 is out now.

Tested 1.3.0 beta 2 no changed just complied and uploaded. No menu pops up in the print menu for mesh leveling etc.

**Comment by Daventrik** [comment]
> 
> 
> > i would be glad to help with testing but i didn't flashed my printer with these versions yet, still on stock but i have the "round corners" on a square and i hope that the new firmware can solve that issue since the profile tuning is not solving this. How can i help?
> 
> Try setting K factor to 0.2
> 
> Send "M900 K0.20" and safe with M500 Try 190°C (if PLA) Get a e3d V6 nozzle (fits on stock hotend) => big improvement

I will buy a e3d v6 nozzle but what would be recommended? Brass? copper plated, stainless steel? Thank you!

**Comment by Yury-MonZon** [comment]
Version 1.4.0.-b2 doesn't have linear advance support
`Unknown command: M900`

**Comment by knutwurst** [comment]
Fixed in dd169b7 and will be included in the next release.

**Comment by Yury-MonZon** [comment]
You are the man! That was quick!  Thanks a lot!
Are you planning to release 1.4.0-beta.3 with those fixes any time soon?

**Comment by q4wey** [comment]
@knutwurst 

Tested the new release 1.40.0.beta 2 today. When using the built in remove filament tool while a print is paused the filament will begin to remove but then the printer reboots so you cant resume the print.

Your doing great work on this mate, many thanks.

**Comment by knutwurst** [comment]
@Yury-MonZon dunno... I have to fix some more things as you can see ;) In the upcoming days I think. But you can check out the master branch and compile it by yourself :) 

@q4wey Does this only apply to the 4MAX Pro v2?

**Comment by CruisenRainerWahnsinn** [comment]
Didn't test the latest alphas yet. Still very happy about 1.3.1 :) already

**Concerning ENV and 4max types:**
There are several 4max out. Just wondering if env "4max" is meant to be "4max pro (1)". There should be 4max, 4max pro, and 4 max pro 2 (afaik)

**Concerning acceleation/jerk parameters that are working very nice for me:**
```
Recv: echo:; Steps per unit:
Recv: echo: M92 X100.00 Y80.00 Z800.00 E423.50
Recv: echo:; Maximum feedrates (units/s):
Recv: echo:  M203 X150.00 Y150.00 Z25.00 E30.00
Recv: echo:; Maximum Acceleration (units/s2):
Recv: echo:  M201 X2000.00 Y2000.00 Z60.00 E10000.00
Recv: echo:; Acceleration (units/s2): P<print_accel> R<retract_accel> T<travel_accel>
Recv: echo:  M204 P1500.00 R1500.00 T1500.00
Recv: echo:; Advanced: B<min_segment_time_us> S<min_feedrate> T<min_travel_feedrate> J<junc_dev>
Recv: echo:  M205 B20000.00 S0.00 T0.00 J0.02
```

![20211103_085654](https://user-images.githubusercontent.com/73447431/140614715-55b6a35f-832a-422b-8c5d-87d81d310fe1.jpg)
:

**Comment by knutwurst** [comment]
@CruisenRainerWahnsinn take a look at the Beta (not alpha). ;) All 4MAX variants should be covered. Beta 3 is on the way with more improvements.

**Comment by CruisenRainerWahnsinn** [comment]
> 
> 
> @CruisenRainerWahnsinn take a look at the Beta (not alpha). ;) All 4MAX variants should be covered. Beta 3 is on the way with more improvements.

I'll check them out 100%. Thank's a lot for your work!

**Comment by Yury-MonZon** [comment]
@CruisenRainerWahnsinn Print acceleration 1500? Looks a bit high to me. What are your print speeds with these settings? Also, how did you manage to install e3d v6 nozzle? It is longer, isn't it?

**Comment by CruisenRainerWahnsinn** [comment]
> 
> 
> @CruisenRainerWahnsinn Print acceleration 1500? Looks a bit high to me, how did you get rid of the ringing? What are your print speeds with these settings? Also, how did you manage to install e3d v6 nozzle? It is longer, isn't it?

It's working great for me like this. 

This is the latest Cura Profile I'm using (from the print you see):
https://www.dropbox.com/s/qxn14x4ppobsnq3/4MaxPro2.0_PLA_0.2mm_192C.curaprofile?dl=0

The only thing you need to dadpt to the e3d v6 nozzle, is the height of the fan duct (needs little sanding or reconstruction). The e3d v6 nozzle fits the stock hotend perfectly.

**Comment by q4wey** [comment]
> @Yury-MonZon dunno... I have to fix some more things as you can see ;) In the upcoming days I think. But you can check out the master branch and compile it by yourself :)
> 
> @q4wey Does this only apply to the 4MAX Pro v2?

yes my apologies this was tested on the 4max pro 2.0 i should have specified

**Comment by q4wey** [comment]
Tested 4MAXP2_DGUS_v1.4.0-b3.hex on the 4max pro 2.0. When printing and the pause button it pressed a message of SD pullout will pop on the screen until the printer head it parked. after the head is parked 3 beeps are made but when you try to resume the print it just wont resume.

**Comment by Yury-MonZon** [comment]
> it just wont resume
I also have this sometimes. Wondering why is this not a constant thing?

**Comment by knutwurst** [comment]
@q4wey and @Yury-MonZon are you sure that you have the DGUS variant with Anycubic 0.0.2 Display? There is a Pause/Resume bug in the original DGUS II.

**Comment by Yury-MonZon** [comment]
I'm sorry, didn't know that they are different. How do I get the model of the screen?

**Comment by CruisenRainerWahnsinn** [comment]
> 
> 
> I'm sorry, didn't know that they are different. How do I get the model of the screen?

There are some sources here:

https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/wiki/Beginner's-Guide-(English)#2-identification-of-the-display

&

https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/wiki/Types-of-Anycubic-Touchscreens

**Comment by Yury-MonZon** [comment]
@knutwurst Yeah, I have Anycubic 0.0.2 display (DGUS clone) - the text 'Ready' is sharp and small.

**Comment by luknz** [comment]
Hi, first of all thank you very much for your effort! Knutwurst has been running flawlessly on my i3 Mega for months. Today I also flashed my Anycubic 4Max Pro 2.0 with V 1.4.0-beta.3. Since then he has been making strange whistling noises when printing, like an old Internet modem. Does anyone know what could be causing this?

**Comment by Truggy** [comment]
Not sure what I did wrong. I have v002 board 4mp v2.

when I stop a print the system crashes and is ina continuous reboot until hard switch is switched off.

I have the clone screen as well - same behavior with stock steppers or all tmc 2208. Did reset and load defaults in eprom.

thanks,
John

**Comment by Yury-MonZon** [comment]
> continuous reboot until hard switch is switched off
When I do this I have multiple messages on the screen. So I use pause and then stop. And after that printer doesn't print when you start a new print.

**Comment by Truggy** [comment]
That the same as I have. Ok. Wasnt sure if something was up with the mainboard.

**Comment by dspitzer** [comment]
After a lot of fiddling I managed to install a BLTouch in the 4Max Pro 2 and with the latest master the auto levelling works perfectly - thanks a lot @knutwurst ! 

I'm using the 4MAXP2_DGUS_BLT_10 and the only parameter that I changed was the NOZZLE_TO_PROBE_OFFSET.

A few quirks that I noticed so far: After booting, the display immediately reboots (it basically shows the startup animation twice). Also, stopping a print results in a boot loop - I have to turn the printer off every time I stop a print.

**Comment by Truggy** [comment]
I get the same but I used the non blt firmware.

**Comment by SchimmelSepp** [comment]
Hey good morning,
Is it just recommended to use CURA or do i must use CURA with the Firmware from Knutwurst. Because i think Prusa works better for details & corners.

**Comment by CruisenRainerWahnsinn** [comment]
@SchimmelSepp 
Most users I crossed, were using cura, some prusa. I saw good results on both.

Concerning Display and crashes:
I recently found out that my octoprint server is solving the bugs you're describing (but the double starting animation)
My machine don't crash and i can navigate through the whole menu (on the display) the whole time - while printing and always can access the special menu, which isn't the case for non-print-server-users.

**Comment by SchimmelSepp** [comment]
> @SchimmelSepp Most users I crossed, were using cura, some prusa. I saw good results on both.
> 
> Concerning display and crashes: I recently found out that my octoprint server is solving the bugs you're describing (but the double starting animation) My machine don't crash and i can navigate through the whole menu (on the display) the whole time - while printing and always can access the special menu, which isn't the case for non-print-server-users.

Yeah, i use prusa and the result with KW-Firmware is amazing instead of the Standard. Me either had just the Problem when i hit Stop the Printer reboots it selfs 2-6 times (idk why it does sometime 2 times and sometime up to 6) but yesterday i printed for 9 Hours and it stopped and didnt finished the printing, but the printer gived me via the Display the text „Print is finished“. And the Layerd looked good and didnt hat print fails.

**Comment by Truggy** [comment]
Do we think a release 4 will happen?

**Comment by CruisenRainerWahnsinn** [comment]
@knutwurst 

Just compiled and installed the beta 4 from today on my totally stock 4MP2.

Needed to chose DGUS-Version as env, because the stock 4MP2-env had no "special menu".
Maybe it got mixed up. 

I wil run this vversion now and report all i find here.

**Comment by CruisenRainerWahnsinn** [comment]
> @knutwurst

The DGUS-Version is working fine for the 100% stock printer!
No issues so far (with octoprint involved)

**Comment by knutwurst** [comment]
There is nothing mixed up afaik. There are (older) 4MP2 printers that have an original DWIN/DGUS II display. They need the firmware without DGUS in the name. The newer printers with Anycubic 0.0.2 "DGUS Clone" need the _DGUS firmware.

That was already the case with the Mega X.

**Comment by JonnyHaystack** [comment]
That does sound like a somewhat confusing naming convention :stuck_out_tongue:

**Comment by CruisenRainerWahnsinn** [comment]
Haha, yes! 

Thanks for your work!

I'm 100% sure ja have the clone screen:
https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/wiki/Beginner's-Guide-(English)#23-the-anycubic-002-display-dgus-clone

Special menu looked like this since 1.3.0 (self compiled)
https://raw.githubusercontent.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/master/images/manual_dgus_specialmenu.jpg

Since 1.4.0b4  i have to chose DGUS to get the special menu back and it is still looking like before (not like original DWIN)
(I have a stock printer - no changes made on drivers or display)

**Comment by CruisenRainerWahnsinn** [comment]
Otoprint error message which cause "promptly stop" on 4MP2-DGUS, when using mesh bed leveling with M420 S1 in the start gcode. without the command it has no error message and prints.

```
Fehler vom Drucker gemeldet
Die Firmware Deines Druckers hat einen Fehler gemeldet. Darum hat OctoPrint die Verbindung geschlossen. Gemeldeter Fehler: Failed to enable Bed Leveling
```

**Comment by CruisenRainerWahnsinn** [comment]
#https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/issues/234

**Comment by knutwurst** [comment]
@CruisenRainerWahnsinn can you provide further information? And can you test it with 1.4.0 Beta 5?

**Comment by VegaMyssil** [comment]
First of all thank you the printer is now working properly !


I have some issue with the LED strip. When I start a print the strip goes off. Also, had to change polarity on the Extruder Motor and Z axis since there is only two TMC driver (X and Y).

**Comment by Yury-MonZon** [comment]
> First of all thank you the printer is now working properly !
> 
> I have some issue with the LED strip. When I start a print the strip goes off. Also, had to change polarity on the Extruder Motor and Z axis since there is only two TMC driver (X and Y).
> 
> (Using the compiled firmware)

You have to send a command to enable it in your start g-code:
M355 S1 P255

**Comment by VegaMyssil** [comment]
> You have to send a command to enable it in your start g-code: M355 S1 P255

Will try ! Thanks !

**Comment by iankds05** [comment]
Well I have tried all variations of the firmware including Beta 5 and none work flawlessly. The Pause/Resume is broken and if Stop print is pressed the screen goes into a loop and the whole machine has to be shut off. Corner levelling can only be done from Special menu so to be hones I have given up on the outdated Trigrollia board. I intend to strip out the electronics and install a decent 32bit controller and screen so future updates of Marlin can be installed without having to hack the firmware every single time. Why Anycubic insist on using outdated control boards when the 3D world has moved on from Mega 2560 chips beats me. The 4Max Pro could have been an awesome machine if not let down by poor support and antique electronics.

**Comment by knutwurst** [comment]
@iankds05 can you try to repruduce every issue (regarding pause/resume) on Beta 5 and create a bugticket? Maybe with a video or photos. The problem is, that I don't own a 4MAX Pro so I have to "code blindly" and listen to what people (like you) say to make it better.

The leveling function is currently not implemented yet, so the only way to level the bed is the internal 4 point and mesh leveling, which should also work... until I fugured out the internal tft functions to reverse engineer the functionality and provide full support.

Please be aware, that this firmware is still in beta state, so bugs always might occur.

**Comment by iankds05** [comment]
So thanks for the reply Oliver, but at this stage I have already started to rip out all the electronics from my 4Max Pro v2 and replace with completely new 32 bit control board and dual function TFT screen. I need a reliable "Daily Go To" enclosed printer and continually having to tinker with the firmware is not an option anymore. 
I commend you work so far, especially not having the actual hardware to soak test on. I did not use any of the binary files but compiled my own from your source code as I had replaced all the stepper drivers with TMC2209 standalone. At least with my new setup I can use UART and sensorless homing
I will post a progress report with pictures in case other tinkers want to be brave and do the same modifications.

**Comment by ausdai** [comment]
@knutwurst Thank you so much for this. I have had a lot of trouble finding information about the 4Mac Pro v2.0. Could you please clarify which version of the firmware should be used. I have a recent model that says it includes the TMC2208 stepper drivers as stock. Does this mean I need to flash this with the _TCM  using 4MAXP2_TMC_v1.4.0-b5.hex or 4MAXP2_DGUS_TMC_v1.4.0-b5.hex depending on the screen? Or should I be using the none _TCM versions?

**Comment by mjaschen** [comment]
You can just try it ;-)

1. Center the printhead in the X, Y and Z directions so that it has enough space to move around it.
2. Move the printhead little distances in X, Y and Z with the built-in control screen or with OctoPrint an take notes which direction it moves when pressing the + or - keys.
3. Install the firmware.
4. Use the built-in control screen again to move the printhead. You will then see if the directions are the same or if you need to install the `_TCM` firmware to reverse the moving directions.

**Comment by knutwurst** [comment]
@ausdai : As mentioned in the [FAQ](https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/wiki/FAQ-(english)) ;) 

But @mjaschen is also right! That's the way if you want to be absolutely sure.

**Comment by ausdai** [comment]
> @ausdai : As mentioned in the [FAQ](https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/wiki/FAQ-(english)) ;)
> 
> But @mjaschen is also right! That's the way if you want to be absolutely sure.

Thanks for letting me know. I did read the FAQ but I couldn't see anything that really answered that question specifically. Maybe I'm going blind! Thanks again, I will follow the instructions and test.

**Comment by AKharytonchyk** [comment]
Hi Gents, 

I am trying to connect RPI to a 4Max Pro 2. Though, it looks like UART3 is disabled on the motherboard. I am using the latest beta build for 4max. Might be someone has an idea how to turn it on?

**Comment by CruisenRainerWahnsinn** [comment]
After installing 1.4.0 my print bed is heating when the printer gets turned on. It is set to 0° and it's showing 0° as set, but the tempreature is increasing and never stopping. The bed is getting very hot and the display is showing the increasing temperature. (Same behavour on 1.4.1..now)

Where to start??? Replacing cables that are attached to the bed?
Ordered a mosfet too. 

![grafik](https://user-images.githubusercontent.com/73447431/153507461-3360ab7c-6271-47e2-b527-575ed4025f89.png)
![grafik](https://user-images.githubusercontent.com/73447431/153507495-e5ea1c20-730c-4755-861a-4156747302bb.png)
![grafik](https://user-images.githubusercontent.com/73447431/153507529-4598f3f3-196c-48b4-9a35-f5090604b38e.png)
![grafik](https://user-images.githubusercontent.com/73447431/153507584-2c0af57f-675d-4f69-8276-1c0c62f38f60.png)

**Comment by knutwurst** [comment]
I can't explain it either, but it seems as if the power supply generates short-term voltage spikes when the PWM frequency is too low. This "could" lead to a defect in the MOSFET, but in my opinion it is very unlikely. After all, hundreds of printers work without any problems.

It's probably a coincidence. :(

The cables do not need to be swapped. The temperature is read correctly and the bed heats up. So all cables are still fine.

The MOSFET (second photo) is probably defective and is now switching through completely.

I hope you can solve the problem. Please continue to use 1.4.1. Just to be safe.

**Comment by CruisenRainerWahnsinn** [comment]
> The MOSFET (second photo) is probably defective and is now switching through completely.
> 
> I hope you can solve the problem. Please continue to use 1.4.1. Just to be safe.

mosfet is ordred and 1.4.1 installed. still thanks for your work and keep on going!

**Comment by CruisenRainerWahnsinn** [comment]
@knutwurst Can I use 1.4.3 or should i stay on 1.4.0b5, which im using since my mosfet died? Feel like asking this time, before changing again :)

**Comment by knutwurst** [comment]
@CruisenRainerWahnsinn it's safe to update ;)
