### ISSUE TITLE
bl touch leveling 

### ISSUE THREAD

**Issue by sims-60** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#66]
hi ist es möglich mit mehr als 25 punkten das bl touch leveling auszuführen zB dann 10*10 also 100 punkte?

**Comment by knutwurst** [comment]
Hallo @sims-60,

Kurze Antwort: Ja.

Lange Antwort: Das soll jetzt nicht unhöflich/gemein klingen, aber dies ist ein Issue-Tracker, in dem (auf englisch) reproduzierbare Fehler in der Firmware festgehalten, priorisiert und bearbeitet werden. Jeder Eintrag repräsentiert hierbei einen Firmware-Bug, der programmatisch von meiner Seite aus behoben werden muss. Es ist kein Chat und kein Forum für allgemeine Fragen, daher möchte ich dich bitten, deine Frage (die ohnehin auf der Marlinfw-Seite beantwortet wurde) lieber in der zugehörigen Facebook-Supportgruppe oder in einem 3D Druck Forum zu stellen.
