### ISSUE TITLE
BUG - Printer stuck

### ISSUE THREAD

**Issue by wes1993** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#71]
Hello to everyone!!! 
I have bought from amazon the Original BLtouch V3.1:
 https://www.amazon.it/Antclabs-Bltouch-livellamento-sensore-stampante/dp/B01FFV2TOS/ref=sr_1_5?__mk_it_IT=%C3%85M%C3%85%C5%BD%C3%95%C3%91&dchild=1&keywords=bl+touch&qid=1612027158&quartzVehicle=2590-535&replacementKeywords=touch&sr=8-5

It's normal also that the red led of the bed when reach the temperature blink fast?

BUG PART --------
I have also another problem:
When the print start, after some seconds stop printing and turn off the red led of the bed, also the BLtouch from blue/red become fixed red.

LOG: 
Error:Thermal Runaway, system stopped! Heater_ID: 0
[ERROR] Error:Thermal Runaway, system stopped! Heater_ID: 0

Error:Printer halted. kill() called!
[ERROR] Error:Printer halted. kill() called!

After this the printer firmware stuck, no stop process, no update of the temperature etc.

I have seen that the HotEnd temperature from 245 degree arrive at 226 in 3/4 seconds.

Flashed the original Mega S firmware works well, but no BLtouch support :-(

P.S. i have falshed the Mega S firmware but my printer it's a Mega M with the upgraded kit
I hope someone can help me
@knutwurst Really really thanks a lot for your beautiful work!!! :-D
Best Regards
Stefano

**Comment by wes1993** [comment]
I have attached a photo of when the sensor find the final point:

![Uploading 78D3CBE3-B8BA-4D5B-AD28-ADDCFE9C98EA.jpeg…]()

**Comment by wes1993** [comment]
UPDATE!!!
I have found that with your firmware 1.1.1 with BLTouch support downloaded from here (https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/releases/tag/1.1.1) i don't have any problem!!!
So what is the difference related to the HotEnd temperature etc from 1.1.1 and1.1.9?

I really hope someone could help me!!
@knutwurst Again thanks alot for your beautiful work!!!!

**Comment by wes1993** [comment]
I think i have finally solved the problem.
I will do more test in the next days but the solution is:
Flash Firmware
Power Off Printer
Turn ON
Pronterface
M502 (Load setting from firmware)
M500 (save settings in EEPROM)
Power Off printer
Turn ON
Print

**Comment by wes1993** [comment]
I have claim victory too soon...
Same problem... the print start and after some seconds the hotend temperature go down.. from 245 to 226 degree in some seconds...

**Comment by wes1993** [comment]
NEW UPDATE:
Disabling the fan of the HotEnd seems that could print, so there is a way to make the hotend controller more faster when the temperature down?

**Comment by knutwurst** [comment]
Hi @wes1993 ,
Unfortunately, I am currently in the hospital, which is why it is difficult to respond to bug reports promptly. As far as I can see, this is not a firmware bug. Your problem is already described in the wiki or FAQ: https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/wiki/FAQ-(english)

Your fan may run at a maximum of 70% if it is the original one. With the firmware he gets more power than with the original. This is also in the FAQ. In addition, if the temperature cannot be maintained, you should either pull a silicone sock over the nozzle or do the PID tuning for your preferred temperature.

**Comment by wes1993** [comment]
Hello @knutwurst 
I am very sorry that you are in the hospital, I hope is not at all serious 🤞
Thanks again for your work and your help!! You firmware is wonderful!! :)
I have seen that in cura if I change the fan speed settings nothing change... so now I know why if I put 70%, 50% etc nothing change.
Thanks for you help!! :)
I wish you a quick recovery and sorry for my bad English... :( I’m Italian :(

**Comment by wes1993** [comment]
P.S. I have seen now the wiki... sorry for my stupid oversight
