### ISSUE TITLE
[BUG] Mesh bed leveling: not saving to EEPROM

### ISSUE THREAD

**Issue by OkiGraphics** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#72]
### Bug Description

I had to re-level the bed before large print. I re-leveled trough a special menu directly via display. After going trough all the points, I hit save to EEPROM and then end mesh bed leveling. I have restarted the printer. When I go to mesh bed leveling again, it starts again on old Z values. I tested it several times, I even made the first point way too off on purpose (so I feel no resistance), but If i start to re-level again, I feel strong resistance (as before re-leveling).

### My Configurations

"MEGA_S_DGUS_v1.1.9.hex"

### Steps to Reproduce

1. Run trough all mesh bed leveling points
2. Save to EEPROM.
3. Start mesh bed leveling again.

**Expected behavior:** [What you expect to happen]
Starting the next mesh leveling process on to positions saved to EEPROM last time. G29 S0 should return mesh points positions.
**Actual behavior:** [What actually happens]
After sending G29 S0 via Pronterface, I get **Mesh Bed Leveling has no data**.

#### Additional Information

What might by important, last time I (sucessfully) did mesh bed leveling via Pronterface.

**Comment by CruisenRainerWahnsinn** [comment]
Are there any news/solutions available to use mesh bed leveling reliably? It worked with ponterface but with octoprint it seems like mesh data got lost.

**Comment by knutwurst** [comment]
Hi @CruisenRainerWahnsinn and @OkiGraphics .
Can you please test the new 1.2.0-alpha.1 version if the issue still persists? I've fixed a mesh loading bug, but it might be another issue.

**Comment by knutwurst** [comment]
1.2.0-alpha.2 is released. Please test if the problem still persists.

**Comment by CruisenRainerWahnsinn** [comment]
> 
> 
> 1.2.0-alpha.2 is released. Please test if the problem still persists.

Tested. Thank you!

MEGA_P_TMC + config files from here: 
https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/issues/65
https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/files/5875815/4MP_2.0_KW1.1.9.zip

Still got the error when trying to print via octoprint:

![grafik](https://user-images.githubusercontent.com/73447431/114322648-9de21e80-9b21-11eb-955e-4b6209e5b51a.png)

`Recv:  T:67.84 /205.00 B:60.12 /60.00 @:127 B@:51 W:?
Recv:  T:68.45 /205.00 B:60.14 /60.00 @:127 B@:48
Recv:  T:69.68 /205.00 B:60.16 /60.00 @:127 B@:44 W:?
Recv: echo:busy: processing
Recv:  T:71.47 /205.00 B:60.17 /60.00 @:127 B@:40 W:?
Recv:  T:72.06 /205.00 B:60.23 /60.00 @:127 B@:29
Recv:  T:73.31 /205.00 B:60.24 /60.00 @:127 B@:25 W:?
Recv: echo:busy: processing
Recv:  T:75.14 /205.00 B:60.32 /60.00 @:127 B@:7 W:?
Recv:  T:76.02 /205.00 B:60.32 /60.00 @:127 B@:4
Recv:  T:77.23 /205.00 B:60.32 /60.00 @:127 B@:0 W:?
Recv: echo:busy: processing
Recv:  T:79.02 /205.00 B:60.32 /60.00 @:127 B@:0 W:?
Recv:  T:79.67 /205.00 B:60.32 /60.00 @:127 B@:0
Recv:  T:80.83 /205.00 B:60.32 /60.00 @:127 B@:0 W:?
Recv: echo:busy: processing
Recv:  T:82.62 /205.00 B:60.27 /60.00 @:127 B@:0 W:?
Recv:  T:83.18 /205.00 B:60.31 /60.00 @:127 B@:0
Recv:  T:84.37 /205.00 B:60.26 /60.00 @:127 B@:0 W:?
Recv: echo:busy: processing
Recv:  T:86.11 /205.00 B:60.18 /60.00 @:127 B@:0 W:?
Recv:  T:86.69 /205.00 B:60.16 /60.00 @:127 B@:0
Recv:  T:87.85 /205.00 B:60.16 /60.00 @:127 B@:0 W:?
Recv: echo:busy: processing
Recv:  T:89.54 /205.00 B:60.14 /60.00 @:127 B@:0 W:?
Recv:  T:90.09 /205.00 B:60.11 /60.00 @:127 B@:0
Recv:  T:91.26 /205.00 B:60.03 /60.00 @:127 B@:8 W:?
Recv: echo:busy: processing
Recv:  T:92.96 /205.00 B:60.00 /60.00 @:127 B@:11 W:?
Recv:  T:93.78 /205.00 B:59.96 /60.00 @:127 B@:17
Recv:  T:94.93 /205.00 B:59.95 /60.00 @:127 B@:18 W:?
Recv: echo:busy: processing
Recv:  T:96.60 /205.00 B:59.82 /60.00 @:127 B@:43 W:?
Recv:  T:97.18 /205.00 B:59.80 /60.00 @:127 B@:45
Recv:  T:98.29 /205.00 B:59.80 /60.00 @:127 B@:47 W:?
Recv: echo:busy: processing
Recv:  T:99.96 /205.00 B:59.78 /60.00 @:127 B@:54 W:?
Recv:  T:100.50 /205.00 B:59.77 /60.00 @:127 B@:57
Recv:  T:101.60 /205.00 B:59.72 /60.00 @:127 B@:69 W:?
Recv: echo:busy: processing
Recv:  T:103.20 /205.00 B:59.74 /60.00 @:127 B@:69 W:?
Recv:  T:103.75 /205.00 B:59.67 /60.00 @:127 B@:84
Recv:  T:104.79 /205.00 B:59.63 /60.00 @:127 B@:95 W:?
Recv: echo:busy: processing
Recv:  T:106.42 /205.00 B:59.68 /60.00 @:127 B@:92 W:?
Recv:  T:106.94 /205.00 B:59.67 /60.00 @:127 B@:97
Recv:  T:108.02 /205.00 B:59.72 /60.00 @:127 B@:92 W:?
Recv: echo:busy: processing
Recv:  T:109.85 /205.00 B:59.80 /60.00 @:127 B@:84 W:?
Recv:  T:110.38 /205.00 B:59.80 /60.00 @:127 B@:86
Recv:  T:111.45 /205.00 B:59.80 /60.00 @:127 B@:89 W:?
Recv: echo:busy: processing
Recv:  T:113.06 /205.00 B:59.85 /60.00 @:127 B@:86 W:?
Recv:  T:113.58 /205.00 B:59.87 /60.00 @:127 B@:85
Recv:  T:114.63 /205.00 B:59.96 /60.00 @:127 B@:70 W:?
Recv: echo:busy: processing
Recv:  T:116.20 /205.00 B:60.00 /60.00 @:127 B@:66 W:?
Recv:  T:116.71 /205.00 B:60.00 /60.00 @:127 B@:66
Recv:  T:117.72 /205.00 B:60.06 /60.00 @:127 B@:57 W:?
Recv: echo:busy: processing
Recv:  T:119.25 /205.00 B:60.14 /60.00 @:127 B@:42 W:?
Recv:  T:119.74 /205.00 B:60.16 /60.00 @:127 B@:39
Recv:  T:120.77 /205.00 B:60.16 /60.00 @:127 B@:38 W:?
Recv: echo:busy: processing
Recv:  T:122.25 /205.00 B:60.16 /60.00 @:127 B@:36 W:?
Recv:  T:122.77 /205.00 B:60.18 /60.00 @:127 B@:31
Recv:  T:123.75 /205.00 B:60.24 /60.00 @:127 B@:19 W:?
Recv: echo:busy: processing
Recv:  T:125.44 /205.00 B:60.26 /60.00 @:127 B@:10 W:?
Recv:  T:125.93 /205.00 B:60.27 /60.00 @:127 B@:7
Recv:  T:126.90 /205.00 B:60.26 /60.00 @:127 B@:6 W:?
Recv: echo:busy: processing
Recv:  T:128.40 /205.00 B:60.28 /60.00 @:127 B@:0 W:?
Recv:  T:128.85 /205.00 B:60.26 /60.00 @:127 B@:0
Recv:  T:129.79 /205.00 B:60.23 /60.00 @:127 B@:0 W:?
Recv: echo:busy: processing
Recv:  T:131.24 /205.00 B:60.20 /60.00 @:127 B@:0 W:?
Recv:  T:131.70 /205.00 B:60.18 /60.00 @:127 B@:2
Recv:  T:132.66 /205.00 B:60.18 /60.00 @:127 B@:0 W:?
Recv: echo:busy: processing
Recv:  T:134.03 /205.00 B:60.16 /60.00 @:127 B@:0 W:?
Recv:  T:134.47 /205.00 B:60.16 /60.00 @:127 B@:0
Recv:  T:135.41 /205.00 B:60.13 /60.00 @:127 B@:0 W:?
Recv: echo:busy: processing
Recv:  T:136.86 /205.00 B:60.02 /60.00 @:127 B@:15 W:?
Recv:  T:137.31 /205.00 B:60.00 /60.00 @:127 B@:18
Recv:  T:138.25 /205.00 B:60.00 /60.00 @:127 B@:17 W:?
Recv: echo:busy: processing
Recv:  T:139.89 /205.00 B:59.99 /60.00 @:127 B@:17 W:?
Recv:  T:140.34 /205.00 B:59.94 /60.00 @:127 B@:25
Recv:  T:141.26 /205.00 B:59.89 /60.00 @:127 B@:34 W:?
Recv: echo:busy: processing
Recv:  T:142.64 /205.00 B:59.80 /60.00 @:127 B@:51 W:?
Recv:  T:143.09 /205.00 B:59.80 /60.00 @:127 B@:51
Recv:  T:143.98 /205.00 B:59.80 /60.00 @:127 B@:53 W:?
Recv: echo:busy: processing
Recv:  T:145.31 /205.00 B:59.80 /60.00 @:127 B@:56 W:?
Recv:  T:145.80 /205.00 B:59.79 /60.00 @:127 B@:59
Recv:  T:146.68 /205.00 B:59.80 /60.00 @:127 B@:60 W:?
Recv: echo:busy: processing
Recv:  T:148.02 /205.00 B:59.80 /60.00 @:127 B@:64 W:?
Recv:  T:148.44 /205.00 B:59.78 /60.00 @:127 B@:70
Recv:  T:149.26 /205.00 B:59.78 /60.00 @:127 B@:73 W:?
Recv: echo:busy: processing
Recv:  T:150.56 /205.00 B:59.78 /60.00 @:127 B@:77 W:?
Recv:  T:151.24 /205.00 B:59.79 /60.00 @:127 B@:77
Recv:  T:152.11 /205.00 B:59.80 /60.00 @:127 B@:78 W:?
Recv: echo:busy: processing
Recv:  T:153.36 /205.00 B:59.84 /60.00 @:127 B@:76 W:?
Recv:  T:153.75 /205.00 B:59.80 /60.00 @:127 B@:84
Recv:  T:154.63 /205.00 B:59.87 /60.00 @:127 B@:76 W:?
Recv: echo:busy: processing
Recv:  T:155.91 /205.00 B:60.00 /60.00 @:127 B@:55 W:?
Recv:  T:156.35 /205.00 B:59.99 /60.00 @:127 B@:58
Recv:  T:157.25 /205.00 B:59.99 /60.00 @:127 B@:59 W:?
Recv: echo:busy: processing
Recv:  T:158.53 /205.00 B:60.00 /60.00 @:127 B@:59 W:?
Recv:  T:158.96 /205.00 B:60.02 /60.00 @:127 B@:56
Recv:  T:159.75 /205.00 B:60.10 /60.00 @:127 B@:41 W:?
Recv: echo:busy: processing
Recv:  T:161.04 /205.00 B:60.15 /60.00 @:127 B@:32 W:?
Recv:  T:161.51 /205.00 B:60.15 /60.00 @:127 B@:31
Recv:  T:162.34 /205.00 B:60.16 /60.00 @:127 B@:28 W:?
Recv: echo:busy: processing
Recv:  T:163.65 /205.00 B:60.16 /60.00 @:127 B@:26 W:?
Recv:  T:164.24 /205.00 B:60.16 /60.00 @:127 B@:25
Recv:  T:165.09 /205.00 B:60.18 /60.00 @:127 B@:19 W:?
Recv: echo:busy: processing
Recv:  T:166.41 /205.00 B:60.17 /60.00 @:127 B@:18 W:?
Recv:  T:166.82 /205.00 B:60.17 /60.00 @:127 B@:16
Recv:  T:167.62 /205.00 B:60.17 /60.00 @:127 B@:14 W:?
Recv: echo:busy: processing
Recv:  T:168.80 /205.00 B:60.16 /60.00 @:127 B@:12 W:?
Recv:  T:169.17 /205.00 B:60.17 /60.00 @:127 B@:9
Recv:  T:169.97 /205.00 B:60.16 /60.00 @:127 B@:9 W:?
Recv: echo:busy: processing
Recv:  T:171.23 /205.00 B:60.16 /60.00 @:127 B@:5 W:?
Recv:  T:171.60 /205.00 B:60.16 /60.00 @:127 B@:4
Recv:  T:172.44 /205.00 B:60.14 /60.00 @:127 B@:5 W:?
Recv: echo:busy: processing
Recv:  T:173.71 /205.00 B:60.06 /60.00 @:127 B@:16 W:?
Recv:  T:174.06 /205.00 B:60.01 /60.00 @:127 B@:24
Recv:  T:174.82 /205.00 B:60.00 /60.00 @:127 B@:25 W:?
Recv: echo:busy: processing
Recv:  T:176.04 /205.00 B:59.99 /60.00 @:127 B@:26 W:?
Recv:  T:176.67 /205.00 B:59.98 /60.00 @:127 B@:27
Recv:  T:177.40 /205.00 B:59.95 /60.00 @:127 B@:31 W:?
Recv: echo:busy: processing
Recv:  T:178.54 /205.00 B:59.91 /60.00 @:127 B@:38 W:?
Recv:  T:178.96 /205.00 B:59.89 /60.00 @:127 B@:43
Recv:  T:179.65 /205.00 B:59.84 /60.00 @:127 B@:52 W:?
Recv: echo:busy: processing
Recv:  T:180.77 /205.00 B:59.82 /60.00 @:127 B@:59 W:?
Recv:  T:181.15 /205.00 B:59.80 /60.00 @:127 B@:62
Recv:  T:181.95 /205.00 B:59.80 /60.00 @:127 B@:64 W:?
Recv: echo:busy: processing
Recv:  T:183.13 /205.00 B:59.79 /60.00 @:127 B@:70 W:?
Recv:  T:183.53 /205.00 B:59.80 /60.00 @:127 B@:69
Recv:  T:184.25 /205.00 B:59.80 /60.00 @:127 B@:71 W:?
Recv: echo:busy: processing
Recv:  T:185.39 /205.00 B:59.82 /60.00 @:127 B@:73 W:?
Recv:  T:185.83 /205.00 B:59.82 /60.00 @:127 B@:75
Recv:  T:186.61 /205.00 B:59.82 /60.00 @:127 B@:78 W:?
Recv: echo:busy: processing
Recv:  T:187.92 /205.00 B:59.89 /60.00 @:127 B@:69 W:?
Recv:  T:188.33 /205.00 B:59.90 /60.00 @:127 B@:68
Recv:  T:189.01 /205.00 B:59.95 /60.00 @:127 B@:61 W:?
Recv: echo:busy: processing
Recv:  T:190.14 /205.00 B:60.00 /60.00 @:127 B@:55 W:?
Recv:  T:190.45 /205.00 B:60.00 /60.00 @:127 B@:56
Recv:  T:191.34 /205.00 B:60.00 /60.00 @:127 B@:56 W:?
Recv: echo:busy: processing
Recv:  T:192.30 /205.00 B:60.02 /60.00 @:127 B@:54 W:?
Recv:  T:192.73 /205.00 B:60.08 /60.00 @:127 B@:43
Recv:  T:193.38 /205.00 B:60.09 /60.00 @:127 B@:42 W:?
Recv: echo:busy: processing
Recv:  T:194.49 /205.00 B:60.15 /60.00 @:127 B@:30 W:?
Recv:  T:194.83 /205.00 B:60.16 /60.00 @:127 B@:27
Recv:  T:195.45 /205.00 B:60.16 /60.00 @:77 B@:26 W:?
Recv: echo:busy: processing
Recv:  T:196.31 /205.00 B:60.16 /60.00 @:67 B@:23 W:?
Recv:  T:196.82 /205.00 B:60.16 /60.00 @:59 B@:22
Recv:  T:197.24 /205.00 B:60.17 /60.00 @:57 B@:19 W:?
Recv: echo:busy: processing
Recv:  T:198.38 /205.00 B:60.16 /60.00 @:46 B@:17 W:?
Recv:  T:198.58 /205.00 B:60.17 /60.00 @:45 B@:14
Recv:  T:199.15 /205.00 B:60.16 /60.00 @:41 B@:13 W:?
Recv: echo:busy: processing
Recv:  T:199.89 /205.00 B:60.16 /60.00 @:36 B@:10 W:?
Recv:  T:200.10 /205.00 B:60.16 /60.00 @:35 B@:8
Recv:  T:200.56 /205.00 B:60.16 /60.00 @:32 B@:6 W:?
Recv: echo:busy: processing
Recv:  T:201.11 /205.00 B:60.15 /60.00 @:31 B@:4 W:?
Recv:  T:201.11 /205.00 B:60.14 /60.00 @:34 B@:4
Recv:  T:201.70 /205.00 B:60.13 /60.00 @:28 B@:4 W:?
Recv: echo:busy: processing
Recv:  T:201.84 /205.00 B:60.01 /60.00 @:33 B@:23 W:?
Recv:  T:201.91 /205.00 B:60.01 /60.00 @:34 B@:22
Recv:  T:202.05 /205.00 B:60.01 /60.00 @:36 B@:21 W:?
Recv: echo:busy: processing
Recv:  T:202.19 /205.00 B:60.00 /60.00 @:39 B@:22 W:?
Recv:  T:202.15 /205.00 B:59.99 /60.00 @:42 B@:23
Recv:  T:202.15 /205.00 B:59.95 /60.00 @:45 B@:30 W:?
Recv: echo:busy: processing
Recv:  T:201.91 /205.00 B:59.84 /60.00 @:54 B@:50 W:?
Recv:  T:201.91 /205.00 B:59.82 /60.00 @:55 B@:55
Recv:  T:201.74 /205.00 B:59.82 /60.00 @:60 B@:56 W:?
Recv: echo:busy: processing
Recv:  T:201.67 /205.00 B:59.82 /60.00 @:63 B@:59 W:?
Recv:  T:201.63 /205.00 B:59.80 /60.00 @:65 B@:62
Recv:  T:201.42 /205.00 B:59.80 /60.00 @:70 B@:64 W:?
Recv: echo:busy: processing
Recv:  T:201.04 /205.00 B:59.80 /60.00 @:78 B@:68 W:?
Recv:  T:201.11 /205.00 B:59.80 /60.00 @:77 B@:69
Recv:  T:200.87 /205.00 B:59.80 /60.00 @:82 B@:72 W:?
Recv: echo:busy: processing
Recv:  T:200.66 /205.00 B:59.82 /60.00 @:86 B@:74 W:?
Recv:  T:200.56 /205.00 B:59.80 /60.00 @:89 B@:77
Recv:  T:200.56 /205.00 B:59.82 /60.00 @:88 B@:78 W:?
Recv: echo:busy: processing
Recv:  T:200.49 /205.00 B:59.87 /60.00 @:90 B@:73 W:?
Recv:  T:200.42 /205.00 B:59.95 /60.00 @:92 B@:60
Recv:  T:200.35 /205.00 B:59.99 /60.00 @:93 B@:55 W:?
Recv: echo:busy: processing
Recv:  T:200.21 /205.00 B:60.00 /60.00 @:97 B@:55 W:?
Recv:  T:200.31 /205.00 B:60.00 /60.00 @:95 B@:55
Recv:  T:200.31 /205.00 B:60.00 /60.00 @:96 B@:56 W:?
Recv: echo:busy: processing
Recv:  T:200.45 /205.00 B:60.06 /60.00 @:94 B@:46 W:?
Recv:  T:200.45 /205.00 B:60.08 /60.00 @:95 B@:42
Recv:  T:200.52 /205.00 B:60.12 /60.00 @:95 B@:34 W:?
Recv: echo:busy: processing
Recv:  T:200.56 /205.00 B:60.16 /60.00 @:96 B@:26 W:?
Recv:  T:200.63 /205.00 B:60.16 /60.00 @:96 B@:25
Recv:  T:200.69 /205.00 B:60.16 /60.00 @:96 B@:23 W:?
Recv: echo:busy: processing
Recv:  T:201.08 /205.00 B:60.16 /60.00 @:91 B@:21 W:?
Recv:  T:201.04 /205.00 B:60.16 /60.00 @:93 B@:20
Recv:  T:201.11 /205.00 B:60.17 /60.00 @:94 B@:16 W:?
Recv: echo:busy: processing
Recv:  T:201.60 /205.00 B:60.17 /60.00 @:87 B@:12 W:?
Recv:  T:201.74 /205.00 B:60.16 /60.00 @:86 B@:12
Recv:  T:201.74 /205.00 B:60.17 /60.00 @:89 B@:8 W:?
Recv: echo:busy: processing
Recv:  T:202.15 /205.00 B:60.16 /60.00 @:84 B@:6 W:?
Recv:  T:202.22 /205.00 B:60.15 /60.00 @:84 B@:7
Recv:  T:202.43 /205.00 B:60.15 /60.00 @:82 B@:4 W:?
Recv: echo:busy: processing
Recv:  T:202.78 /205.00 B:60.14 /60.00 @:80 B@:3 W:?
Recv:  T:202.85 /205.00 B:60.10 /60.00 @:80 B@:9
Recv:  T:203.13 /205.00 B:60.05 /60.00 @:77 B@:16 W:?
Recv: echo:busy: processing
Recv:  T:203.26 /205.00 B:60.00 /60.00 @:78 B@:23 W:?
Recv:  T:203.40 /205.00 B:60.00 /60.00 @:77 B@:22
Recv:  T:203.82 /205.00 B:60.00 /60.00 @:71 B@:21 W:?
Recv: echo:busy: processing
Recv:  T:203.92 /205.00 B:59.96 /60.00 @:73 B@:27 W:?
Recv:  T:204.10 /205.00 B:59.98 /60.00 @:71 B@:25
Recv:  T:204.24 /205.00 B:59.93 /60.00 @:70 B@:33 W:9
Recv: echo:busy: processing
Recv:  T:204.44 /205.00 B:59.87 /60.00 @:70 B@:45 W:8
Recv:  T:204.48 /205.00 B:59.83 /60.00 @:71 B@:52
Recv:  T:204.65 /205.00 B:59.82 /60.00 @:69 B@:56 W:7
Recv: echo:busy: processing
Recv:  T:204.97 /205.00 B:59.83 /60.00 @:66 B@:56 W:6
Recv:  T:205.00 /205.00 B:59.82 /60.00 @:66 B@:59
Recv:  T:205.00 /205.00 B:59.80 /60.00 @:68 B@:64 W:5
Recv: echo:busy: processing
Recv:  T:205.23 /205.00 B:59.80 /60.00 @:66 B@:67 W:4
Recv:  T:205.31 /205.00 B:59.82 /60.00 @:65 B@:67
Recv:  T:205.59 /205.00 B:59.80 /60.00 @:61 B@:71 W:3
Recv: echo:busy: processing
Recv:  T:205.70 /205.00 B:59.83 /60.00 @:61 B@:71 W:2
Recv:  T:205.55 /205.00 B:59.83 /60.00 @:64 B@:72
Recv:  T:205.63 /205.00 B:59.89 /60.00 @:64 B@:64 W:1
Recv: echo:busy: processing
Recv:  T:205.63 /205.00 B:59.95 /60.00 @:65 B@:56 W:0
Recv: ok
Send: N20 M82*43
Recv: ok
Send: N21 G28*32
Recv:  T:205.63 /205.00 B:60.00 /60.00 @:65 B@:48
Recv: echo:busy: processing
Recv:  T:206.05 /205.00 B:60.00 /60.00 @:58 B@:51
Recv: echo:busy: processing
Recv:  T:207.19 /205.00 B:60.14 /60.00 @:39 B@:26
Recv: echo:busy: processing
Recv:  T:208.32 /205.00 B:60.16 /60.00 @:24 B@:20
Recv: X:-6.00 Y:0.00 Z:0.00 E:4.00 Count X:-600 Y:0 Z:0
Recv: ok
Send: N22 M420 S1*87
Recv: echo:Invalid mesh.
Recv: Error:Failed to enable Bed Leveling
Changing monitoring state from "Printing" to "Error: Failed to enable Bed Leveling"
Send: M112
Send: N23 M112*16
Send: N24 M104 T0 S0*23
Send: N25 M140 S0*82
Changing monitoring state from "Error: Failed to enable Bed Leveling" to "Offline (Error: Failed to enable Bed Leveling)"
Connection closed, closing down monitor`

Any suggestions welcome!

**Comment by knutwurst** [comment]
I don't know what's the difference to the 4MAX pro, but the 1.2.0 seems to work on all supported printers. :/
