### ISSUE TITLE
Using M117 command (TFT Display)

### ISSUE THREAD

**Issue by 777chmod777** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#81]
Hi,

is it possible to use the M117 command?
I tried it and the printer responds with "ok" but in the display from my Anycubic I3 Mega S is nothing to see.

Here is the description of the command:

https://marlinfw.org/docs/gcode/M117.html

Thank You!

**Comment by knutwurst** [comment]
Nope, that's not possible on anycubic touchscreens. See: https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/wiki/FAQ-(english)

I'm sorry :)
