### ISSUE TITLE
Question: Marlin 2.0.7.2 with your configfiles?

### ISSUE THREAD

**Issue by raindancer2204** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#83]
##############
Deutsch:
##############

Hi Knutwurst,

ich muss sagen erstmal ein Lob für das super Projekt Daumen hoch was ihr hier geleistet habt. 

Die aktuelle Marlin Firmware ist **2.0.7.2.** 

Kann man die aktuelle Marlin Firmware und deine Configfiles 1 zu 1 verwenden? zum kompilieren im MS Visual Studio Code?
Configuration.h
Configuration_adv.h

Das ich noch die Stepper und Richtungen setzen muss ist mir soweit klar. 

Muss da sonst noch was beachtet werden?

Danke Dir
raini

#########
English:
#########
Hi Knutwurst,

First of all I have to say praise for the great project thumbs up what you have done here.

The current Marlin firmware is 2.0.7.2.

Can I use the current Marlin firmware and your config files 1 to 1 to compile in Visual Studio Code?
Configuration.h
Configuration_adv.h

That I still have to set the stepper and directions is clear to me.

Is there anything else that needs to be considered?

Thank you
raini

**Comment by knutwurst** [comment]
Hallo,
vielen Dank! :) 

Tja.. nein.. leider kannst du das nicht einfach machen. Also klar kannst du die Configs nehmen, aber dann wird es nicht funktionieren. Die eigentliche Arbeit und Logik steckt im Display-Code und in der Seriellen Kommunikation. Die configs sind nur nettes Beiwerk.

Bisher läuft Marlin >2.0.6 auch absolut nicht zufriedenstellend auf den Atmega256x Boards. Wieso das so ist, weiß ich auch nicht. Ich hatte auch einen Marlin 2.0.7 Branch, aber den wieder eingestampft, da grundlegende Funktionen nicht ordentlich laufen. Die Display-Implementierung nimmt auch unfassbar viel RAM weg, so dass kaum noch etwas für "mich" übrig blieb. Deshalb habe ich das erst mal vernachlässigt und konzentriere mich auf den Support von Chriron, 4MAX und dem Mega Pro Laser.
