### ISSUE TITLE
(Question) What are the offset values of my BLTOUCH

### ISSUE THREAD

**Issue by phyex0** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#84]
Hi dear developer.

I'd like to install BLTouch into my printer and you say that 

> The offset of the sensor is X=-2 Y=-25 and Z=0. These values ​​are already set as a standard.

Those values don't depend on the mount stuff?  How can I be sure about my BLTouch's offset values? There is one more question about mount size. I didn't change the size of the mount that you add the link in the guide. Does the size matter?

Regards

**Comment by knutwurst** [comment]
Hi @phyex0 :)

Of course the offset represents the actual position of the sensor pin. If you change the mount, you need to edit the offset. This can be done via gcode commands.

best
Olli
