### ISSUE TITLE
[BUG] (short description)print will not resume after filament sensor pause.  

### ISSUE THREAD

**Issue by paigewilliamson1** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#92]
### My Configurations

**Required:** Please include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

#### Additional Information

* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by Sn0wStorm** [comment]
Works fine for me, no problem. Just click on continue on the touch screen

**Comment by paigewilliamson1** [comment]
hmm, it doesn't at all for me. 
    On Tuesday, March 9, 2021, 07:04:44 AM MST, Sn0wStorm <notifications@github.com> wrote:  
 
 


Works fine for me, no problem. Just click on continue on the touch screen

**Comment by knutwurst** [comment]
What printer do you use? Can you make a video like this? https://www.youtube.com/watch?v=MRSr3vZjFYU
