### ISSUE TITLE
[FR] MEATPACK enabled?

### ISSUE THREAD

**Issue by MrBill1234** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#97]
Is the MEATPACK pre-compiler option set in the pre-compiled binaries?

More info here:

https://github.com/scottmudge/OctoPrint-MeatPack/

**Comment by MrBill1234** [comment]
Looking at the Marlin repository - it looks like it is only in the bugfix branch

https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/src/feature/meatpack.cpp

Could it be manually added and compiled in?

**Comment by knutwurst** [comment]
At this point in time it is unfortunately not possible, as this feature is only available in the latest bugfix branch from Marlin, and I never update the entire branch, only individual elements. So I would have to extract the feature.

I don't know if I'll do that yet :) Maybe ... if there is a lot of time ...

:)

**Comment by MrBill1234** [comment]
If it made its way into a main release branch, in theory it would be in your next release?
