### ISSUE TITLE
[FR] Update for BLTouch installation / Fix for problems with pin not releasing

### ISSUE THREAD

**Issue by hawkeyexp** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#98]
In my case i had some issues the pin was not released from time to time (BLTouch 3.1) - not always and after power on the selftest was working without any problems.

Solution:
the BLTouch has a screw on bottom side which is usually not visible when it is mounted.
During the search how to fix my problem i was on the way to replace the pin and had a look to the manucaturers manual how to replace the pin. This way i noticed a small hint that this screw is the core of the electromagnet which holds the pin and the field intensity can be adjusted by unscrew a bit to lower the field intesity or screwing deeper in to enhance the field intesity. This solved my problem perfectly! My field intensity was a bit to high so i unscrewed a bit to ensure the pin will always release also after some power on time which cause that the electromagnetic field is fully saturated.

I think this hint would be really helpfull for many other users which has possible problems with 3.1 not releasing in some cases. I was searching for a solution for ~2 weeks and solving the problem takes only 5 minutes if you know how :-)

**Comment by knutwurst** [comment]
Thank you for the Information! I'll update the BLTouch Installation guide <3
